# Phase 4.1 - Aggressive Model Compression

**Author:** Rafael  **Dataset:** Tiny-ImageNet-200 (200 classes, 64x64 RGB)

Push the best Phase 1-3 models below INT8. PyTorch-native quantization
strategies, evaluated on the same axis so bit-widths are directly comparable:

| Method | Bits | Mode | Models |
|---|---|---|---|
| INT8 | W8/A8 | PTQ (calibrate) | all 5 (anchor) |
| INT4 PTQ | W4/A8 | PTQ (calibrate) | all 5 |
| INT4 QAT | W4/A8 | retrain | 3 tiny |
| Mixed | W4-8/A8 per-layer | retrain | 3 tiny |
| INT2 PTQ | W2/A8 | PTQ (calibrate) | all 5 |
| Ternary (TWN) | `{-α,0,+α}` weight-only | PTQ (no calib) | all 5 |
| Binary (BWN) | `{-α,+α}` weight-only | PTQ (no calib) | all 5 |

INT4/mixed/INT2 use **FakeQuantize simulation** (fbgemm has no INT4 kernel): accuracy is
faithful, size is the theoretical packed size (`theoretical_size_mb`). Ternary/binary
quantize weights directly (`apply_weight_ptq`), activations FP32. All eval on GPU.

**Targets:** `mobilenetv2`, `alexnet_bottleneck`, `alexnet_fire`,
`alexnet_depthwisesep` (QAT-unstable edge case), `alexnet_final_fire_residual`.

Layout: 1. Imports 2. Data 3. FP32 baselines 4. Compression helpers
5. INT8 6. INT4 PTQ 7. INT4 QAT 8. Mixed precision 8b. Sub-INT4 (INT2/ternary/binary) 9. Comparison & summaries

## 1. Imports & reproducibility

In [ ]:
import json
import os
import random
import sys
import time
from dataclasses import asdict, replace
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torchinfo
import wandb

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

from ml import (
    DataConfig, TrainerConfig, QATConfig,
    create_imagenet_loaders,
    Trainer, make_qat_callback, auto_resume_path, compress_checkpoint,
    load_best_model, build_comparison_table, create_results_summary,
    disk_mb, gzip_mb, compute_flops,
    make_qconfig, prepare_sim, calibrate,
    compute_layer_sensitivity, assign_mixed_precision, apply_weight_qat, theoretical_size_mb,
)
from ml import find_fuse_groups
from configs.loader import load_config

from models import (
    MobileNetV2TV, AlexNetBottleneck, AlexNetFire,
    AlexNetDepthwiseSep, AlexNetFinalFireResidual,
)

torch.backends.quantized.engine = "fbgemm"

In [3]:
SEED = 42
random.seed(SEED); np.random.seed(SEED)
torch.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

SAVE_DIR    = project_root / "checkpoints" / "compression_phase4_1"
RESULTS_DIR = project_root / "results" / "compression_phase4_1"
SAVE_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

data_cfg = DataConfig(**load_config("data.yaml"))
data_cfg.seed = SEED
fp32_cfg = TrainerConfig(**load_config("training.yaml"))
comp_cfg = load_config("compression.yaml")
print(device)

cuda

## 2. Dataset & loaders

Standard train/val loaders plus a small **calibration loader** (single-worker, no shuffle) used for PTQ range collection and sensitivity analysis.

In [4]:
import kagglehub

dataset_path = kagglehub.dataset_download("akash2sharma/tiny-imagenet")
train_path = os.path.join(dataset_path, "tiny-imagenet-200", "train")
data_cfg.dataset_path = train_path

train_ds, val_ds, train_loader, val_loader = create_imagenet_loaders(data_cfg)

calib_loader = torch.utils.data.DataLoader(
    train_ds, batch_size=data_cfg.batch_size, shuffle=False, num_workers=2, pin_memory=True,
)

print(f"Train {len(train_ds):,} | Val {len(val_ds):,} | classes {data_cfg.num_classes}")
print(f"Batches: train={len(train_loader)} val={len(val_loader)}")

Train 90,000 | Val 10,000 | classes 200
Batches: train=1406 val=157

## 3. Target models & FP32 baselines

The 5 targets live in three different Phase 1-3 checkpoint dirs. We load each
FP32 `*_best.pth`, evaluate it, and record its baseline (accuracy, disk size, params, MACs).

In [5]:
TARGETS = {
    "mobilenetv2":                 dict(ctor=MobileNetV2TV,            src="baselines_qat_phase1"),
    "alexnet_bottleneck":          dict(ctor=AlexNetBottleneck,        src="compensation_phase3"),
    "alexnet_fire":                dict(ctor=AlexNetFire,              src="compensation_phase3"),
    "alexnet_depthwisesep":        dict(ctor=AlexNetDepthwiseSep,      src="compensation_phase3"),
    "alexnet_final_fire_residual": dict(ctor=AlexNetFinalFireResidual, src="final_architecture_phase4"),
}
ALL_MODELS  = list(TARGETS)
TINY_MODELS = ["alexnet_bottleneck", "alexnet_fire", "alexnet_depthwisesep"]

IMG = data_cfg.img_size
INPUT_SIZE = (1, 3, IMG, IMG)


def load_fp32(name):
    """Load the best FP32 checkpoint for a target from its source phase dir."""
    spec = TARGETS[name]
    src_dir = project_root / "checkpoints" / spec["src"]
    return load_best_model(name, spec["ctor"], src_dir, device, eval_mode=True)


def eval_on(model, loader):
    """Top-1/Top-5/loss via Trainer.evaluate (device follows model)."""
    t = Trainer(model, train_loader, loader, replace(fp32_cfg, use_amp=False),
                next(model.parameters()).device, SAVE_DIR, "eval",
                num_classes=data_cfg.num_classes)
    return t.evaluate(topk=(1, 5))

In [ ]:
fp32_baseline = {}
for name in ALL_MODELS:
    m = load_fp32(name)
    info = torchinfo.summary(m, input_size=INPUT_SIZE, verbose=0)
    ev = eval_on(m, val_loader)
    flops = compute_flops(m.cpu().eval(), input_size=INPUT_SIZE)
    src_dir = project_root / "checkpoints" / TARGETS[name]["src"]
    compress_checkpoint(src_dir / f"{name}_best.pth")
    fp32_baseline[name] = {
        "top1": ev["top1"], "top5": ev["top5"],
        "params_m": info.total_params / 1e6,
        "disk_mb": disk_mb(src_dir / f"{name}_best.pth"),
        "gzip_mb": gzip_mb(src_dir / f"{name}_best.pth"),
        "size_mb_32": theoretical_size_mb(m, w_bits=32),
        "macs": flops["macs"],
    }
    print(f"{name:30s} top1={ev['top1']:.2f}% top5={ev['top5']:.2f}% "
          f"params={info.total_params/1e6:.2f}M size={fp32_baseline[name]['disk_mb']:.1f}MB")
    del m; torch.cuda.empty_cache()

## 4. Compression helpers

`fuse_map_for` auto-detects Conv-BN(-ReLU) groups. `run_ptq` calibrates a
fake-quant model (no retraining). `run_qat` fine-tunes one. Every result is
appended to `ROWS` in the shared schema and mirrored to a per-model record.

In [7]:
ROWS = []
per_model = {n: {"fp32_baseline": fp32_baseline[n], "methods": []} for n in ALL_MODELS}


def fuse_map_for(name):
    """Best-effort auto fuse map (find_fuse_groups recurses into .features etc.)."""
    return find_fuse_groups(TARGETS[name]["ctor"]())


def _load_best_into(model, run_name):
    ckpt = torch.load(SAVE_DIR / f"{run_name}_best.pth", map_location=str(device), weights_only=False)
    model.load_state_dict(ckpt.get("model_state_dict", ckpt))
    return model


def record(name, method, precision, ev, size_mb, bench, notes,
           train_hrs=None, calib_min=None, bits_map=None):
    base = fp32_baseline[name]
    ratio = base["size_mb_32"] / size_mb if size_mb else None
    row = {
        "model": name, "method": method, "precision": precision,
        "fp32_baseline_acc": base["top1"], "compressed_top1_acc": ev["top1"],
        "top5_acc": ev["top5"], "acc_drop_pp": base["top1"] - ev["top1"],
        "compression_ratio": ratio,
        "fp32_size_mb": base["size_mb_32"], "compressed_size_mb": size_mb,
        "latency_ms": bench["latency_ms_per_image"],
        "throughput_img_s": bench["throughput_img_per_s"],
        "params_m": base["params_m"], "acc_per_mb": ev["top1"] / size_mb if size_mb else None,
        "training_time_hrs": train_hrs, "calibration_time_min": calib_min,
        "top1_%": ev["top1"], "top5_%": ev["top5"], "size_MB": size_mb,
        "notes": notes,
    }
    ROWS.append(row)
    rec = dict(row); rec["bits_map"] = bits_map
    per_model[name]["methods"].append(rec)
    print(f"  -> {method:12s} top1={ev['top1']:.2f}% ({row['acc_drop_pp']:+.2f}pp) "
          f"size={size_mb:.2f}MB ratio={ratio:.1f}x")


def wandb_run(name, method, cfg_extra):
    return wandb.init(
        project="alexnet-compression", group="phase-4-1-compression",
        name=f"{name}_{method}",
        config={"arch": name, "method": method, "phase": "4.1",
                "dataset": "tiny-imagenet-200", **cfg_extra},
        tags=["phase-4-1", method, name, "tiny-imagenet", "compression"],
        mode="offline", reinit=True,
    )

In [8]:
def run_ptq(name, method, w_bits, a_bits, n_calib, precision, notes):
    """Post-training: fuse -> fake-quant -> calibrate -> eval. No retraining."""
    model = load_fp32(name)
    qconfig = make_qconfig(w_bits=w_bits, a_bits=a_bits, per_channel=True)
    sim = prepare_sim(model, fuse_map_for(name), qconfig, device)
    t0 = time.perf_counter()
    sim = calibrate(sim, calib_loader, device, n_samples=n_calib)
    calib_min = (time.perf_counter() - t0) / 60
    ev = eval_on(sim, val_loader)
    bench = Trainer(sim, train_loader, val_loader, replace(fp32_cfg, use_amp=False),
                    device, SAVE_DIR, "bench", num_classes=data_cfg.num_classes).benchmark(warmup=50)
    size_mb = theoretical_size_mb(model, w_bits=w_bits)
    run = wandb_run(name, method, {"w_bits": w_bits, "a_bits": a_bits, "calib_samples": n_calib})
    run.summary.update({"top1": ev["top1"], "top5": ev["top5"], "size_mb": size_mb})
    wandb.finish()
    record(name, method, precision, ev, size_mb, bench, notes, calib_min=calib_min)
    del model, sim; torch.cuda.empty_cache()


def run_qat(name, method, w_bits, a_bits, mcfg, precision, notes, bits_map=None, sim=None):
    """QAT: fine-tune a fake-quant (or mixed) model, reload best, eval."""
    model = load_fp32(name)
    if sim is None:
        qconfig = make_qconfig(w_bits=w_bits, a_bits=a_bits, per_channel=mcfg.get("per_channel", True))
        sim = prepare_sim(model, fuse_map_for(name), qconfig, device)
    run_name = f"{method}_{name}"
    qat_cfg = replace(fp32_cfg, epochs=mcfg["epochs"], lr=mcfg["lr"],
                      weight_decay=mcfg["weight_decay"], use_amp=False)
    cb = make_qat_callback(mcfg["freeze_bn_epoch"], mcfg["disable_observer_epoch"])
    resume = auto_resume_path(SAVE_DIR, run_name)

    if (SAVE_DIR / f"{run_name}_best.pth").exists() and not resume:
        print(f"  (reusing {run_name}_best.pth)")
    else:
        run = wandb_run(name, method, {"w_bits": w_bits, "a_bits": a_bits, **mcfg})
        tr = Trainer(sim, train_loader, val_loader, qat_cfg, device, SAVE_DIR, run_name,
                     num_classes=data_cfg.num_classes, wandb_run=run, epoch_callback=cb,
                     log_file=SAVE_DIR / f"{run_name}.log")
        fit = tr.fit(resume_from=resume)
        wandb.finish()
        per_model[name].setdefault("train_time_hrs", {})[method] = fit["total_training_time_s"] / 3600

    sim = _load_best_into(sim, run_name).eval()
    ev = eval_on(sim, val_loader)
    bench = Trainer(sim, train_loader, val_loader, qat_cfg, device, SAVE_DIR, "bench",
                    num_classes=data_cfg.num_classes).benchmark(warmup=50)
    size_mb = theoretical_size_mb(model, w_bits=w_bits, bits_map=bits_map)
    train_hrs = per_model[name].get("train_time_hrs", {}).get(method)
    record(name, method, precision, ev, size_mb, bench, notes,
           train_hrs=train_hrs, bits_map=bits_map)
    del model, sim; torch.cuda.empty_cache()

## 5. INT8 (anchor)

Uniform fake-quant W8/A8 PTQ across all 5 models - the known-good reference point. (Real INT8-QAT numbers from Phases 1-3 remain valid cross-checks.)

In [9]:
for name in ALL_MODELS:
    print(name)
    run_ptq(name, "int8", w_bits=8, a_bits=8,
            n_calib=comp_cfg["int4_ptq"]["calibration_samples"],
            precision="int8", notes="fake-quant W8/A8 PTQ")

mobilenetv2

wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

  -> int8         top1=55.41% (+2.58pp) size=2.37MB ratio=4.0x
alexnet_bottleneck

  -> int8         top1=44.24% (+0.39pp) size=0.37MB ratio=4.0x
alexnet_fire

  -> int8         top1=43.94% (+0.04pp) size=0.49MB ratio=4.0x
alexnet_depthwisesep

  -> int8         top1=43.65% (+0.74pp) size=0.30MB ratio=4.0x
alexnet_final_fire_residual

  -> int8         top1=49.76% (+0.04pp) size=0.67MB ratio=4.0x

## 6. INT4 PTQ

Weights to 4-bit post-training (per-channel), activations INT8. The fast low-bit baseline.

In [10]:
for name in ALL_MODELS:
    print(name)
    run_ptq(name, "int4_ptq", w_bits=4, a_bits=8,
            n_calib=comp_cfg["int4_ptq"]["calibration_samples"],
            precision="int4", notes="fake-quant W4/A8 PTQ, per-channel")

mobilenetv2

  -> int4_ptq     top1=3.50% (+54.49pp) size=1.20MB ratio=7.8x
alexnet_bottleneck

  -> int4_ptq     top1=35.32% (+9.30pp) size=0.19MB ratio=7.9x
alexnet_fire

  -> int4_ptq     top1=37.72% (+6.26pp) size=0.25MB ratio=7.9x
alexnet_depthwisesep

  -> int4_ptq     top1=10.00% (+34.39pp) size=0.15MB ratio=7.8x
alexnet_final_fire_residual

  -> int4_ptq     top1=40.01% (+9.78pp) size=0.34MB ratio=7.9x

## 7. INT4 QAT

Retrain under 4-bit weight fake-quant on the 3 tiny models - does training recover the PTQ gap? (Watch **alexnet_depthwisesep**, the -2.92 pp QAT edge case.)

In [11]:
mcfg_int4 = comp_cfg["int4_qat"]
for name in TINY_MODELS:
    print(name)
    run_qat(name, "int4_qat", w_bits=4, a_bits=8, mcfg=mcfg_int4,
            precision="int4", notes="fake-quant W4/A8 QAT, per-channel")

alexnet_bottleneck

================= Run Summary =================
Model          : int4_qat_alexnet_bottleneck
Epochs         : 20
Best Val Top-1 : 44.46%
Best Val Top-5 : 70.71%
Final Val Top-1: 40.83%
Final Val Top-5: 67.64%
Best Val Loss  : inf
Total Time     : 00:00:00
===============================================

  -> int4_qat     top1=44.34% (+0.29pp) size=0.19MB ratio=7.9x
alexnet_fire

Training: 100%|██████████| 1406/1406 [01:53<00:00, 12.38it/s, acc=42.18%, loss=3.0276]
Validation: 100%|██████████| 157/157 [00:05<00:00, 28.02it/s, loss=3.0319, top1=42.99%, top5=69.62%]
Epoch  20/20 | train_loss=3.0276 train_acc=42.18% | val_loss=3.0319 val_acc=42.99% val_top5=69.62% | lr=0.00e+00 peak_mem=1058MB time=119.3s
Early stopping at epoch 20

================= Run Summary =================
Model          : int4_qat_alexnet_fire
Epochs         : 20
Best Val Top-1 : 44.41%
Best Val Top-5 : 70.60%
Final Val Top-1: 42.99%
Final Val Top-5: 69.62%
Best Val Loss  : inf
Total Time     : 00:01:59
===============================================

  -> int4_qat     top1=44.26% (-0.28pp) size=0.25MB ratio=7.9x
alexnet_depthwisesep

Training: 100%|██████████| 1406/1406 [00:36<00:00, 38.30it/s, acc=36.51%, loss=3.2590]
Validation: 100%|██████████| 157/157 [00:01<00:00, 89.14it/s, loss=3.6106, top1=30.32%, top5=55.82%]
Epoch  20/20 | train_loss=3.2590 train_acc=36.51% | val_loss=3.6106 val_acc=30.32% val_top5=55.82% | lr=0.00e+00 peak_mem=341MB time=38.5s
Early stopping at epoch 20

================= Run Summary =================
Model          : int4_qat_alexnet_depthwisesep
Epochs         : 20
Best Val Top-1 : 41.38%
Best Val Top-5 : 67.37%
Final Val Top-1: 30.32%
Final Val Top-5: 55.82%
Best Val Loss  : inf
Total Time     : 00:00:38
===============================================

  -> int4_qat     top1=41.32% (+3.07pp) size=0.15MB ratio=7.8x

## 8. Mixed precision (INT4/INT8 per-layer)

Rank layers by INT4 sensitivity, keep the top `int8_ratio` at INT8 and the rest at INT4, then fine-tune. Tests whether per-layer mixing beats uniform INT4.

In [12]:
import copy as _copy
mcfg_mix = comp_cfg["mixed_precision"]
for name in TINY_MODELS:
    print(name)
    model = load_fp32(name)
    base = _copy.deepcopy(model).to(device).train()
    # sensitivity + per-layer qconfig on the UNFUSED graph so layer names match,
    # THEN fuse (carries each conv's qconfig into the fused module) and prepare_qat.
    sens = compute_layer_sensitivity(base, calib_loader, device, w_bits=4)
    bits_map = assign_mixed_precision(base, sens, int8_ratio=mcfg_mix["int8_ratio"],
                                      per_channel=mcfg_mix["per_channel"])
    base.qconfig = make_qconfig(8, 8, mcfg_mix["per_channel"])  # default for unmarked mods
    fm = fuse_map_for(name)
    if fm:
        try:
            torch.ao.quantization.fuse_modules_qat(base, fm, inplace=True)
        except Exception as e:
            print("  fusion skipped:", e)
    base.train()  # fuse_modules_qat flips to eval; prepare_qat requires train mode
    torch.ao.quantization.prepare_qat(base, inplace=True)
    n8 = sum(v == 8 for v in bits_map.values()); n4 = sum(v == 4 for v in bits_map.values())
    print(f"  layers: INT8={n8} INT4={n4}")
    run_qat(name, "mixed", w_bits=4, a_bits=8, mcfg=mcfg_mix,
            precision="int4/8", notes=f"per-layer INT4/INT8 ({n8} hi / {n4} lo)",
            bits_map=bits_map, sim=base)
    del model, base; torch.cuda.empty_cache()

alexnet_bottleneck
  layers: INT8=5 INT4=11

Training: 100%|██████████| 1406/1406 [00:45<00:00, 30.91it/s, acc=42.51%, loss=2.9800]
Validation: 100%|██████████| 157/157 [00:02<00:00, 67.90it/s, loss=2.9410, top1=44.44%, top5=71.02%]
Epoch  11/20 | train_loss=2.9800 train_acc=42.51% | val_loss=2.9410 val_acc=44.44% val_top5=71.02% | lr=4.22e-06 peak_mem=498MB time=47.9s
Early stopping at epoch 11

================= Run Summary =================
Model          : mixed_alexnet_bottleneck
Epochs         : 11
Best Val Top-1 : 44.77%
Best Val Top-5 : 70.69%
Final Val Top-1: 44.44%
Final Val Top-5: 71.02%
Best Val Loss  : inf
Total Time     : 00:00:47
===============================================

  -> mixed        top1=44.61% (+0.01pp) size=0.21MB ratio=6.9x
alexnet_fire
  layers: INT8=5 INT4=11

Training: 100%|██████████| 1406/1406 [01:30<00:00, 15.55it/s, acc=39.75%, loss=3.1171]
Validation: 100%|██████████| 157/157 [00:02<00:00, 57.19it/s, loss=3.0225, top1=43.11%, top5=69.96%]
Epoch  12/20 | train_loss=3.1171 train_acc=39.75% | val_loss=3.0225 val_acc=43.11% val_top5=69.96% | lr=3.45e-06 peak_mem=1069MB time=93.2s
Early stopping at epoch 12

================= Run Summary =================
Model          : mixed_alexnet_fire
Epochs         : 12
Best Val Top-1 : 44.79%
Best Val Top-5 : 70.95%
Final Val Top-1: 43.11%
Final Val Top-5: 69.96%
Best Val Loss  : inf
Total Time     : 00:01:33
===============================================

  -> mixed        top1=44.70% (-0.72pp) size=0.29MB ratio=6.7x
alexnet_depthwisesep
  layers: INT8=3 INT4=8

================= Run Summary =================
Model          : mixed_alexnet_depthwisesep
Epochs         : 20
Best Val Top-1 : 44.35%
Best Val Top-5 : 69.43%
Final Val Top-1: 44.16%
Final Val Top-5: 69.39%
Best Val Loss  : inf
Total Time     : 00:00:00
===============================================

  -> mixed        top1=44.27% (+0.12pp) size=0.16MB ratio=7.5x

## 8b. Sub-INT4: INT2, ternary (TWN) & binary (BWN) QAT

How far can retraining push these below INT8? Three ever-more-aggressive weight
schemes across **all 5 models**, all **quantization-aware trained** (PTQ alone
collapses this aggressively — Section 6 already shows that gap for INT4, no
need to re-demonstrate it at 1-2 bits):

| Method | Weight levels | Bits | Activations |
|---|---|---|---|
| INT2 QAT | 16 uniform | W2 | A8 (fake-quant) |
| Ternary (TWN) QAT | `{-α, 0, +α}` | ~2 | FP32 |
| Binary (BWN) QAT | `{-α, +α}` | 1 | FP32 |

- **INT2** rides the existing fake-quant path (`run_qat`, W2/A8) — same recipe as Section 7's INT4 QAT.
- **Ternary** (Ternary Weight Networks): per-channel threshold `Δ = 0.7·mean|w|`, scale `α = mean|w|` over survivors — the "(-1, 0, 1)" scheme.
- **Binary** (XNOR-Net BWN): `w → sign(w)·α`, `α = mean|w|` per channel.

Ternary/binary are **weight-only** (`apply_weight_qat`), the setup those papers
report — activations stay FP32. Training uses a straight-through estimator (STE):
the forward pass quantizes the weight, the backward pass passes gradient through
unchanged to a latent FP32 weight, which the optimizer actually updates.

In [13]:
def run_weight_qat(name, method, scheme, w_bits_size, mcfg, precision, notes):
    """Weight-only binary/ternary QAT (STE). Activations FP32; retrained."""
    model = load_fp32(name)
    sim = apply_weight_qat(model, scheme).to(device).train()
    run_name = f"{method}_{name}"
    qat_cfg = replace(fp32_cfg, epochs=mcfg["epochs"], lr=mcfg["lr"],
                      weight_decay=mcfg["weight_decay"], use_amp=False)
    resume = auto_resume_path(SAVE_DIR, run_name)

    if (SAVE_DIR / f"{run_name}_best.pth").exists() and not resume:
        print(f"  (reusing {run_name}_best.pth)")
    else:
        run = wandb_run(name, method, {"scheme": scheme, "w_bits": w_bits_size, **mcfg})
        tr = Trainer(sim, train_loader, val_loader, qat_cfg, device, SAVE_DIR, run_name,
                     num_classes=data_cfg.num_classes, wandb_run=run,
                     log_file=SAVE_DIR / f"{run_name}.log")
        fit = tr.fit(resume_from=resume)
        wandb.finish()
        per_model[name].setdefault("train_time_hrs", {})[method] = fit["total_training_time_s"] / 3600

    sim = _load_best_into(sim, run_name).eval()
    ev = eval_on(sim, val_loader)
    bench = Trainer(sim, train_loader, val_loader, qat_cfg, device, SAVE_DIR, "bench",
                    num_classes=data_cfg.num_classes).benchmark(warmup=50)
    size_mb = theoretical_size_mb(model, w_bits=w_bits_size)
    train_hrs = per_model[name].get("train_time_hrs", {}).get(method)
    record(name, method, precision, ev, size_mb, bench, notes, train_hrs=train_hrs)
    del model, sim; torch.cuda.empty_cache()


for name in ALL_MODELS:
    print(name)
    run_qat(name, "int2_qat", w_bits=2, a_bits=8, mcfg=comp_cfg["int2_qat"],
            precision="int2", notes="fake-quant W2/A8 QAT, per-channel")
    run_weight_qat(name, "ternary_qat", "ternary", w_bits_size=2, mcfg=comp_cfg["ternary_qat"],
                   precision="ternary", notes="weight-only TWN QAT (STE), per-channel, A=FP32")
    run_weight_qat(name, "binary_qat", "binary", w_bits_size=1, mcfg=comp_cfg["binary_qat"],
                   precision="binary", notes="weight-only BWN QAT (STE), per-channel, A=FP32")

mobilenetv2

Training: 100%|██████████| 1406/1406 [01:00<00:00, 23.34it/s, acc=1.90%, loss=5.2607]
Validation: 100%|██████████| 157/157 [00:03<00:00, 46.80it/s, loss=5.6332, top1=0.93%, top5=3.32%]
wandb: WARNING Saving files without folders. If you want to preserve subdirectories pass base_path to wandb.save, i.e. wandb.save("/mnt/folder/file.h5", base_path="/mnt")
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   8/20 | train_loss=5.2607 train_acc=1.90% | val_loss=5.6332 val_acc=0.93% val_top5=3.32% | lr=6.55e-06 peak_mem=712MB time=63.7s
Training: 100%|██████████| 1406/1406 [01:03<00:00, 22.11it/s, acc=2.19%, loss=5.1956]
Validation: 100%|██████████| 157/157 [00:03<00:00, 48.63it/s, loss=5.7487, top1=0.51%, top5=2.65%]
Epoch   9/20 | train_loss=5.1956 train_acc=2.19% | val_loss=5.7487 val_acc=0.51% val_top5=2.65% | lr=5.78e-06 peak_mem=676MB time=66.9s
Training: 100%|██████████| 1406/1406 [01:00<00:00, 23.19it/s, acc=2.43%, loss=5.1548]
Validation: 100%|██████████| 157/157 [00:03<00:00, 46.61it/s, loss=5.6554, top1=0.66%, top5=3.15%]
Epoch  10/20 | train_loss=5.1548 train_acc=2.43% | val_loss=5.6554 val_acc=0.66% val_top5=3.15% | lr=5.00e-06 peak_mem=676MB time=64.1s
Training: 100%|██████████| 1406/1406 [01:00<00:00, 23.18it/s, acc=2.51%, loss=5.1247]
Validation: 100%|██████████| 157/157 [00:03<00:00, 44.14it/s, loss=5.7820, top1=0.58%, top5=2.76%]
Epoch  11/20 | train_loss=5.1247 train_acc=2.51% | val_loss=5.7820 val_acc=0.58% val_top5=2.76% | lr=4.22e-06 peak_mem=676MB time=64.3s
Training: 100%|██████████| 1406/1406 [01:00<00:00, 23.23it/s, acc=2.72%, loss=5.1031]
Validation: 100%|██████████| 157/157 [00:03<00:00, 48.48it/s, loss=5.4704, top1=0.57%, top5=2.74%]
Epoch  12/20 | train_loss=5.1031 train_acc=2.72% | val_loss=5.4704 val_acc=0.57% val_top5=2.74% | lr=3.45e-06 peak_mem=676MB time=63.8s
Training: 100%|██████████| 1406/1406 [01:00<00:00, 23.26it/s, acc=2.84%, loss=5.0875]
Validation: 100%|██████████| 157/157 [00:03<00:00, 47.00it/s, loss=5.6497, top1=0.54%, top5=3.10%]
Epoch  13/20 | train_loss=5.0875 train_acc=2.84% | val_loss=5.6497 val_acc=0.54% val_top5=3.10% | lr=2.73e-06 peak_mem=676MB time=63.8s
Early stopping at epoch 13

================= Run Summary =================
Model          : int2_qat_mobilenetv2
Epochs         : 13
Best Val Top-1 : 0.93%
Best Val Top-5 : 3.32%
Final Val Top-1: 0.54%
Final Val Top-5: 3.10%
Best Val Loss  : 5.6332
Total Time     : 00:06:27
===============================================

  -> int2_qat     top1=0.96% (+57.04pp) size=0.62MB ratio=15.2x

Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.70it/s, acc=1.44%, loss=5.3957]
Validation: 100%|██████████| 157/157 [00:02<00:00, 74.42it/s, loss=5.1667, top1=2.78%, top5=9.58%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=5.3957 train_acc=1.44% | val_loss=5.1667 val_acc=2.78% val_top5=9.58% | lr=9.94e-06 peak_mem=486MB time=39.5s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.80it/s, acc=2.18%, loss=5.1879]
Validation: 100%|██████████| 157/157 [00:02<00:00, 62.26it/s, loss=5.0025, top1=3.99%, top5=13.36%]
Epoch   2/20 | train_loss=5.1879 train_acc=2.18% | val_loss=5.0025 val_acc=3.99% val_top5=13.36% | lr=9.76e-06 peak_mem=486MB time=40.8s
Training: 100%|██████████| 1406/1406 [00:43<00:00, 32.52it/s, acc=2.93%, loss=5.0796]
Validation: 100%|██████████| 157/157 [00:02<00:00, 74.81it/s, loss=4.8700, top1=5.19%, top5=17.13%]
Epoch   3/20 | train_loss=5.0796 train_acc=2.93% | val_loss=4.8700 val_acc=5.19% val_top5=17.13% | lr=9.46e-06 peak_mem=486MB time=45.4s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.94it/s, acc=3.70%, loss=4.9914]
Validation: 100%|██████████| 157/157 [00:02<00:00, 69.06it/s, loss=4.7758, top1=6.21%, top5=19.99%]
Epoch   4/20 | train_loss=4.9914 train_acc=3.70% | val_loss=4.7758 val_acc=6.21% val_top5=19.99% | lr=9.05e-06 peak_mem=486MB time=40.4s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.70it/s, acc=4.51%, loss=4.9180]
Validation: 100%|██████████| 157/157 [00:02<00:00, 70.85it/s, loss=4.6672, top1=7.48%, top5=22.43%]
Epoch   5/20 | train_loss=4.9180 train_acc=4.51% | val_loss=4.6672 val_acc=7.48% val_top5=22.43% | lr=8.54e-06 peak_mem=486MB time=40.6s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.40it/s, acc=4.97%, loss=4.8554]
Validation: 100%|██████████| 157/157 [00:02<00:00, 68.53it/s, loss=4.6204, top1=7.95%, top5=23.90%]
Epoch   6/20 | train_loss=4.8554 train_acc=4.97% | val_loss=4.6204 val_acc=7.95% val_top5=23.90% | lr=7.94e-06 peak_mem=486MB time=41.0s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.16it/s, acc=5.96%, loss=4.7954]
Validation: 100%|██████████| 157/157 [00:02<00:00, 74.39it/s, loss=4.8533, top1=4.80%, top5=16.80%]
Epoch   7/20 | train_loss=4.7954 train_acc=5.96% | val_loss=4.8533 val_acc=4.80% val_top5=16.80% | lr=7.27e-06 peak_mem=486MB time=41.1s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.49it/s, acc=6.71%, loss=4.7438]
Validation: 100%|██████████| 157/157 [00:02<00:00, 62.41it/s, loss=4.4786, top1=10.15%, top5=28.43%]
Epoch   8/20 | train_loss=4.7438 train_acc=6.71% | val_loss=4.4786 val_acc=10.15% val_top5=28.43% | lr=6.55e-06 peak_mem=486MB time=42.2s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.95it/s, acc=7.11%, loss=4.7037]
Validation: 100%|██████████| 157/157 [00:02<00:00, 63.01it/s, loss=4.4195, top1=11.09%, top5=30.09%]
Epoch   9/20 | train_loss=4.7037 train_acc=7.11% | val_loss=4.4195 val_acc=11.09% val_top5=30.09% | lr=5.78e-06 peak_mem=486MB time=41.7s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.49it/s, acc=7.45%, loss=4.6709]
Validation: 100%|██████████| 157/157 [00:02<00:00, 66.59it/s, loss=4.3899, top1=11.26%, top5=30.31%]
Epoch  10/20 | train_loss=4.6709 train_acc=7.45% | val_loss=4.3899 val_acc=11.26% val_top5=30.31% | lr=5.00e-06 peak_mem=486MB time=42.0s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 36.04it/s, acc=7.82%, loss=4.6440]
Validation: 100%|██████████| 157/157 [00:02<00:00, 66.21it/s, loss=4.3607, top1=12.06%, top5=31.58%]
Epoch  11/20 | train_loss=4.6440 train_acc=7.82% | val_loss=4.3607 val_acc=12.06% val_top5=31.58% | lr=4.22e-06 peak_mem=486MB time=41.4s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.82it/s, acc=8.29%, loss=4.6113]
Validation: 100%|██████████| 157/157 [00:02<00:00, 59.78it/s, loss=4.3273, top1=12.62%, top5=32.61%]
Epoch  12/20 | train_loss=4.6113 train_acc=8.29% | val_loss=4.3273 val_acc=12.62% val_top5=32.61% | lr=3.45e-06 peak_mem=486MB time=40.9s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.53it/s, acc=8.46%, loss=4.6006]
Validation: 100%|██████████| 157/157 [00:02<00:00, 77.29it/s, loss=4.3696, top1=11.70%, top5=31.26%]
Epoch  13/20 | train_loss=4.6006 train_acc=8.46% | val_loss=4.3696 val_acc=11.70% val_top5=31.26% | lr=2.73e-06 peak_mem=486MB time=41.7s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.50it/s, acc=8.83%, loss=4.5757]
Validation: 100%|██████████| 157/157 [00:02<00:00, 75.83it/s, loss=4.2761, top1=13.84%, top5=34.47%]
Epoch  14/20 | train_loss=4.5757 train_acc=8.83% | val_loss=4.2761 val_acc=13.84% val_top5=34.47% | lr=2.06e-06 peak_mem=486MB time=39.6s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.93it/s, acc=9.09%, loss=4.5620]
Validation: 100%|██████████| 157/157 [00:01<00:00, 81.10it/s, loss=4.3684, top1=11.87%, top5=31.22%]
Epoch  15/20 | train_loss=4.5620 train_acc=9.09% | val_loss=4.3684 val_acc=11.87% val_top5=31.22% | lr=1.46e-06 peak_mem=486MB time=39.1s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.72it/s, acc=9.30%, loss=4.5486]
Validation: 100%|██████████| 157/157 [00:02<00:00, 78.26it/s, loss=4.4169, top1=11.10%, top5=29.90%]
Epoch  16/20 | train_loss=4.5486 train_acc=9.30% | val_loss=4.4169 val_acc=11.10% val_top5=29.90% | lr=9.55e-07 peak_mem=486MB time=40.4s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.98it/s, acc=9.29%, loss=4.5455]
Validation: 100%|██████████| 157/157 [00:02<00:00, 74.95it/s, loss=4.2845, top1=13.54%, top5=33.82%]
Epoch  17/20 | train_loss=4.5455 train_acc=9.29% | val_loss=4.2845 val_acc=13.54% val_top5=33.82% | lr=5.45e-07 peak_mem=486MB time=39.2s
Training: 100%|██████████| 1406/1406 [00:36<00:00, 38.24it/s, acc=9.52%, loss=4.5383]
Validation: 100%|██████████| 157/157 [00:01<00:00, 79.63it/s, loss=4.2338, top1=14.39%, top5=34.99%]
Epoch  18/20 | train_loss=4.5383 train_acc=9.52% | val_loss=4.2338 val_acc=14.39% val_top5=34.99% | lr=2.45e-07 peak_mem=486MB time=38.8s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.71it/s, acc=9.48%, loss=4.5313]
Validation: 100%|██████████| 157/157 [00:02<00:00, 76.70it/s, loss=4.2415, top1=14.29%, top5=34.97%]
Epoch  19/20 | train_loss=4.5313 train_acc=9.48% | val_loss=4.2415 val_acc=14.29% val_top5=34.97% | lr=6.16e-08 peak_mem=486MB time=41.5s
Training: 100%|██████████| 1406/1406 [00:36<00:00, 38.25it/s, acc=9.42%, loss=4.5260]
Validation: 100%|██████████| 157/157 [00:02<00:00, 77.18it/s, loss=4.2451, top1=14.08%, top5=35.04%]
Epoch  20/20 | train_loss=4.5260 train_acc=9.42% | val_loss=4.2451 val_acc=14.08% val_top5=35.04% | lr=0.00e+00 peak_mem=486MB time=38.9s

================= Run Summary =================
Model          : ternary_qat_mobilenetv2
Epochs         : 20
Best Val Top-1 : 14.39%
Best Val Top-5 : 34.99%
Final Val Top-1: 14.08%
Final Val Top-5: 35.04%
Best Val Loss  : 4.2338
Total Time     : 00:13:37
===============================================

  -> ternary_qat  top1=14.41% (+43.58pp) size=0.62MB ratio=15.2x

Training: 100%|██████████| 1406/1406 [00:33<00:00, 42.31it/s, acc=0.59%, loss=5.4708]
Validation: 100%|██████████| 157/157 [00:01<00:00, 96.68it/s, loss=5.3734, top1=0.72%, top5=3.70%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=5.4708 train_acc=0.59% | val_loss=5.3734 val_acc=0.72% val_top5=3.70% | lr=9.94e-06 peak_mem=503MB time=34.9s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.82it/s, acc=0.73%, loss=5.3652]
Validation: 100%|██████████| 157/157 [00:01<00:00, 98.19it/s, loss=5.3484, top1=0.90%, top5=4.06%]
Epoch   2/20 | train_loss=5.3652 train_acc=0.73% | val_loss=5.3484 val_acc=0.90% val_top5=4.06% | lr=9.76e-06 peak_mem=503MB time=33.7s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 42.04it/s, acc=0.88%, loss=5.3209]
Validation: 100%|██████████| 157/157 [00:01<00:00, 101.02it/s, loss=5.2660, top1=1.35%, top5=5.15%]
Epoch   3/20 | train_loss=5.3209 train_acc=0.88% | val_loss=5.2660 val_acc=1.35% val_top5=5.15% | lr=9.46e-06 peak_mem=463MB time=35.1s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.12it/s, acc=1.07%, loss=5.2895]
Validation: 100%|██████████| 157/157 [00:01<00:00, 96.65it/s, loss=5.2357, top1=1.53%, top5=6.27%]
Epoch   4/20 | train_loss=5.2895 train_acc=1.07% | val_loss=5.2357 val_acc=1.53% val_top5=6.27% | lr=9.05e-06 peak_mem=463MB time=34.3s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.33it/s, acc=1.21%, loss=5.2604]
Validation: 100%|██████████| 157/157 [00:01<00:00, 99.81it/s, loss=5.1932, top1=1.62%, top5=7.18%]
Epoch   5/20 | train_loss=5.2604 train_acc=1.21% | val_loss=5.1932 val_acc=1.62% val_top5=7.18% | lr=8.54e-06 peak_mem=463MB time=34.1s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.52it/s, acc=1.37%, loss=5.2354]
Validation: 100%|██████████| 157/157 [00:01<00:00, 101.51it/s, loss=5.1619, top1=1.95%, top5=8.34%]
Epoch   6/20 | train_loss=5.2354 train_acc=1.37% | val_loss=5.1619 val_acc=1.95% val_top5=8.34% | lr=7.94e-06 peak_mem=463MB time=33.9s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.36it/s, acc=1.48%, loss=5.2124]
Validation: 100%|██████████| 157/157 [00:01<00:00, 104.99it/s, loss=5.1750, top1=1.75%, top5=7.63%]
Epoch   7/20 | train_loss=5.2124 train_acc=1.48% | val_loss=5.1750 val_acc=1.75% val_top5=7.63% | lr=7.27e-06 peak_mem=463MB time=34.0s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 41.51it/s, acc=1.64%, loss=5.1925]
Validation: 100%|██████████| 157/157 [00:01<00:00, 100.59it/s, loss=5.1191, top1=2.18%, top5=9.29%]
Epoch   8/20 | train_loss=5.1925 train_acc=1.64% | val_loss=5.1191 val_acc=2.18% val_top5=9.29% | lr=6.55e-06 peak_mem=463MB time=35.5s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 41.75it/s, acc=1.78%, loss=5.1764]
Validation: 100%|██████████| 157/157 [00:01<00:00, 92.84it/s, loss=5.0857, top1=2.40%, top5=10.21%]
Epoch   9/20 | train_loss=5.1764 train_acc=1.78% | val_loss=5.0857 val_acc=2.40% val_top5=10.21% | lr=5.78e-06 peak_mem=463MB time=35.4s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 42.40it/s, acc=1.86%, loss=5.1584]
Validation: 100%|██████████| 157/157 [00:01<00:00, 99.28it/s, loss=5.0675, top1=2.81%, top5=10.79%]
Epoch  10/20 | train_loss=5.1584 train_acc=1.86% | val_loss=5.0675 val_acc=2.81% val_top5=10.79% | lr=5.00e-06 peak_mem=463MB time=34.8s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.28it/s, acc=2.01%, loss=5.1436]
Validation: 100%|██████████| 157/157 [00:01<00:00, 97.55it/s, loss=5.0670, top1=2.77%, top5=10.26%]
Epoch  11/20 | train_loss=5.1436 train_acc=2.01% | val_loss=5.0670 val_acc=2.77% val_top5=10.26% | lr=4.22e-06 peak_mem=463MB time=34.2s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.05it/s, acc=2.03%, loss=5.1361]
Validation: 100%|██████████| 157/157 [00:01<00:00, 89.09it/s, loss=5.0435, top1=2.91%, top5=11.21%]
Epoch  12/20 | train_loss=5.1361 train_acc=2.03% | val_loss=5.0435 val_acc=2.91% val_top5=11.21% | lr=3.45e-06 peak_mem=463MB time=34.5s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.92it/s, acc=2.25%, loss=5.1231]
Validation: 100%|██████████| 157/157 [00:01<00:00, 88.96it/s, loss=5.0246, top1=3.26%, top5=12.06%]
Epoch  13/20 | train_loss=5.1231 train_acc=2.25% | val_loss=5.0246 val_acc=3.26% val_top5=12.06% | lr=2.73e-06 peak_mem=463MB time=37.1s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 41.93it/s, acc=2.16%, loss=5.1218]
Validation: 100%|██████████| 157/157 [00:01<00:00, 100.62it/s, loss=5.0207, top1=3.45%, top5=11.87%]
Epoch  14/20 | train_loss=5.1218 train_acc=2.16% | val_loss=5.0207 val_acc=3.45% val_top5=11.87% | lr=2.06e-06 peak_mem=463MB time=35.2s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 41.66it/s, acc=2.24%, loss=5.1162]
Validation: 100%|██████████| 157/157 [00:01<00:00, 98.94it/s, loss=5.0120, top1=3.25%, top5=12.39%]
Epoch  15/20 | train_loss=5.1162 train_acc=2.24% | val_loss=5.0120 val_acc=3.25% val_top5=12.39% | lr=1.46e-06 peak_mem=463MB time=35.4s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.46it/s, acc=2.37%, loss=5.1089]
Validation: 100%|██████████| 157/157 [00:01<00:00, 84.18it/s, loss=5.0060, top1=3.47%, top5=12.57%]
Epoch  16/20 | train_loss=5.1089 train_acc=2.37% | val_loss=5.0060 val_acc=3.47% val_top5=12.57% | lr=9.55e-07 peak_mem=463MB time=37.6s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 40.00it/s, acc=2.27%, loss=5.1084]
Validation: 100%|██████████| 157/157 [00:01<00:00, 89.58it/s, loss=5.1195, top1=2.12%, top5=9.28%]
Epoch  17/20 | train_loss=5.1084 train_acc=2.27% | val_loss=5.1195 val_acc=2.12% val_top5=9.28% | lr=5.45e-07 peak_mem=463MB time=37.0s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.97it/s, acc=2.32%, loss=5.1068]
Validation: 100%|██████████| 157/157 [00:01<00:00, 79.97it/s, loss=5.0816, top1=2.42%, top5=10.13%]
Epoch  18/20 | train_loss=5.1068 train_acc=2.32% | val_loss=5.0816 val_acc=2.42% val_top5=10.13% | lr=2.45e-07 peak_mem=463MB time=37.2s
Training: 100%|██████████| 1406/1406 [00:41<00:00, 33.93it/s, acc=2.39%, loss=5.1029]
Validation: 100%|██████████| 157/157 [00:01<00:00, 95.20it/s, loss=4.9978, top1=3.30%, top5=12.47%]
Epoch  19/20 | train_loss=5.1029 train_acc=2.39% | val_loss=4.9978 val_acc=3.30% val_top5=12.47% | lr=6.16e-08 peak_mem=463MB time=43.2s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 42.66it/s, acc=2.42%, loss=5.1024]
Validation: 100%|██████████| 157/157 [00:01<00:00, 90.37it/s, loss=4.9970, top1=3.39%, top5=12.82%]
Epoch  20/20 | train_loss=5.1024 train_acc=2.42% | val_loss=4.9970 val_acc=3.39% val_top5=12.82% | lr=0.00e+00 peak_mem=463MB time=34.8s

================= Run Summary =================
Model          : binary_qat_mobilenetv2
Epochs         : 20
Best Val Top-1 : 3.47%
Best Val Top-5 : 12.57%
Final Val Top-1: 3.39%
Final Val Top-5: 12.82%
Best Val Loss  : 5.0060
Total Time     : 00:11:53
===============================================

  -> binary_qat   top1=3.56% (+54.43pp) size=0.32MB ratio=28.9x
alexnet_bottleneck

Training: 100%|██████████| 1406/1406 [00:42<00:00, 33.22it/s, acc=3.50%, loss=5.4810]
Validation: 100%|██████████| 157/157 [00:02<00:00, 56.20it/s, loss=5.4962, top1=4.70%, top5=14.29%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=5.4810 train_acc=3.50% | val_loss=5.4962 val_acc=4.70% val_top5=14.29% | lr=9.94e-06 peak_mem=487MB time=45.2s
Training: 100%|██████████| 1406/1406 [00:41<00:00, 33.65it/s, acc=6.00%, loss=5.0240]
Validation: 100%|██████████| 157/157 [00:02<00:00, 57.04it/s, loss=5.0029, top1=7.46%, top5=21.92%]
Epoch   2/20 | train_loss=5.0240 train_acc=6.00% | val_loss=5.0029 val_acc=7.46% val_top5=21.92% | lr=9.76e-06 peak_mem=487MB time=44.6s
Training: 100%|██████████| 1406/1406 [00:42<00:00, 32.93it/s, acc=7.97%, loss=4.8015]
Validation: 100%|██████████| 157/157 [00:02<00:00, 55.90it/s, loss=4.9596, top1=7.82%, top5=22.09%]
Epoch   3/20 | train_loss=4.8015 train_acc=7.97% | val_loss=4.9596 val_acc=7.82% val_top5=22.09% | lr=9.46e-06 peak_mem=487MB time=45.6s
Training: 100%|██████████| 1406/1406 [00:42<00:00, 33.44it/s, acc=9.28%, loss=4.6565]
Validation: 100%|██████████| 157/157 [00:02<00:00, 54.27it/s, loss=4.3389, top1=13.46%, top5=33.79%]
Epoch   4/20 | train_loss=4.6565 train_acc=9.28% | val_loss=4.3389 val_acc=13.46% val_top5=33.79% | lr=9.05e-06 peak_mem=487MB time=45.0s
Training: 100%|██████████| 1406/1406 [00:41<00:00, 33.91it/s, acc=10.58%, loss=4.5490]
Validation: 100%|██████████| 157/157 [00:02<00:00, 54.88it/s, loss=4.2710, top1=14.68%, top5=35.56%]
Epoch   5/20 | train_loss=4.5490 train_acc=10.58% | val_loss=4.2710 val_acc=14.68% val_top5=35.56% | lr=8.54e-06 peak_mem=487MB time=44.4s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.69it/s, acc=11.75%, loss=4.4624]
Validation: 100%|██████████| 157/157 [00:01<00:00, 90.95it/s, loss=4.2150, top1=15.83%, top5=37.42%]
Epoch   6/20 | train_loss=4.4624 train_acc=11.75% | val_loss=4.2150 val_acc=15.83% val_top5=37.42% | lr=7.94e-06 peak_mem=487MB time=34.0s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 41.69it/s, acc=12.57%, loss=4.3998]
Validation: 100%|██████████| 157/157 [00:01<00:00, 78.53it/s, loss=4.0990, top1=17.64%, top5=40.87%]
Epoch   7/20 | train_loss=4.3998 train_acc=12.57% | val_loss=4.0990 val_acc=17.64% val_top5=40.87% | lr=7.27e-06 peak_mem=487MB time=35.8s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 41.72it/s, acc=13.58%, loss=4.3558]
Validation: 100%|██████████| 157/157 [00:01<00:00, 85.16it/s, loss=4.1321, top1=17.35%, top5=40.39%]
Epoch   8/20 | train_loss=4.3558 train_acc=13.58% | val_loss=4.1321 val_acc=17.35% val_top5=40.39% | lr=6.55e-06 peak_mem=487MB time=35.6s
Training: 100%|██████████| 1406/1406 [00:31<00:00, 44.03it/s, acc=13.82%, loss=4.3294]
Validation: 100%|██████████| 157/157 [00:01<00:00, 92.20it/s, loss=4.1988, top1=16.36%, top5=38.18%]
Epoch   9/20 | train_loss=4.3294 train_acc=13.82% | val_loss=4.1988 val_acc=16.36% val_top5=38.18% | lr=5.78e-06 peak_mem=487MB time=33.7s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.40it/s, acc=14.03%, loss=4.3102]
Validation: 100%|██████████| 157/157 [00:01<00:00, 89.89it/s, loss=4.0710, top1=18.03%, top5=41.17%]
Epoch  10/20 | train_loss=4.3102 train_acc=14.03% | val_loss=4.0710 val_acc=18.03% val_top5=41.17% | lr=5.00e-06 peak_mem=487MB time=34.2s
Training: 100%|██████████| 1406/1406 [00:31<00:00, 44.27it/s, acc=14.29%, loss=4.2999]
Validation: 100%|██████████| 157/157 [00:01<00:00, 91.51it/s, loss=4.0579, top1=18.55%, top5=41.82%]
Epoch  11/20 | train_loss=4.2999 train_acc=14.29% | val_loss=4.0579 val_acc=18.55% val_top5=41.82% | lr=4.22e-06 peak_mem=487MB time=33.5s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 42.91it/s, acc=14.65%, loss=4.2884]
Validation: 100%|██████████| 157/157 [00:01<00:00, 81.46it/s, loss=4.0445, top1=18.92%, top5=42.13%]
Epoch  12/20 | train_loss=4.2884 train_acc=14.65% | val_loss=4.0445 val_acc=18.92% val_top5=42.13% | lr=3.45e-06 peak_mem=487MB time=34.8s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 42.15it/s, acc=14.67%, loss=4.2808]
Validation: 100%|██████████| 157/157 [00:01<00:00, 93.07it/s, loss=4.0090, top1=19.61%, top5=43.47%]
Epoch  13/20 | train_loss=4.2808 train_acc=14.67% | val_loss=4.0090 val_acc=19.61% val_top5=43.47% | lr=2.73e-06 peak_mem=487MB time=35.1s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.10it/s, acc=15.04%, loss=4.2562]
Validation: 100%|██████████| 157/157 [00:01<00:00, 83.56it/s, loss=3.9993, top1=19.37%, top5=43.87%]
Epoch  14/20 | train_loss=4.2562 train_acc=15.04% | val_loss=3.9993 val_acc=19.37% val_top5=43.87% | lr=2.06e-06 peak_mem=487MB time=34.6s
Training: 100%|██████████| 1406/1406 [00:34<00:00, 41.22it/s, acc=15.30%, loss=4.2412]
Validation: 100%|██████████| 157/157 [00:02<00:00, 77.22it/s, loss=4.0305, top1=19.04%, top5=42.77%]
Epoch  15/20 | train_loss=4.2412 train_acc=15.30% | val_loss=4.0305 val_acc=19.04% val_top5=42.77% | lr=1.46e-06 peak_mem=487MB time=36.2s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.23it/s, acc=15.31%, loss=4.2382]
Validation: 100%|██████████| 157/157 [00:01<00:00, 95.88it/s, loss=4.0172, top1=19.12%, top5=43.11%]
Epoch  16/20 | train_loss=4.2382 train_acc=15.31% | val_loss=4.0172 val_acc=19.12% val_top5=43.11% | lr=9.55e-07 peak_mem=487MB time=34.2s
Training: 100%|██████████| 1406/1406 [00:32<00:00, 43.53it/s, acc=15.38%, loss=4.2305]
Validation: 100%|██████████| 157/157 [00:01<00:00, 94.42it/s, loss=4.0592, top1=18.35%, top5=42.17%]
Epoch  17/20 | train_loss=4.2305 train_acc=15.38% | val_loss=4.0592 val_acc=18.35% val_top5=42.17% | lr=5.45e-07 peak_mem=487MB time=34.0s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 42.44it/s, acc=15.42%, loss=4.2356]
Validation: 100%|██████████| 157/157 [00:01<00:00, 83.63it/s, loss=3.9859, top1=19.97%, top5=43.88%]
Epoch  18/20 | train_loss=4.2356 train_acc=15.42% | val_loss=3.9859 val_acc=19.97% val_top5=43.88% | lr=2.45e-07 peak_mem=487MB time=35.1s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 42.47it/s, acc=15.70%, loss=4.2163]
Validation: 100%|██████████| 157/157 [00:01<00:00, 86.26it/s, loss=4.0152, top1=19.00%, top5=43.80%]
Epoch  19/20 | train_loss=4.2163 train_acc=15.70% | val_loss=4.0152 val_acc=19.00% val_top5=43.80% | lr=6.16e-08 peak_mem=487MB time=35.0s
Training: 100%|██████████| 1406/1406 [00:33<00:00, 42.50it/s, acc=16.00%, loss=4.2026]
Validation: 100%|██████████| 157/157 [00:01<00:00, 92.54it/s, loss=3.9539, top1=20.55%, top5=45.53%]
Epoch  20/20 | train_loss=4.2026 train_acc=16.00% | val_loss=3.9539 val_acc=20.55% val_top5=45.53% | lr=0.00e+00 peak_mem=487MB time=34.8s

================= Run Summary =================
Model          : int2_qat_alexnet_bottleneck
Epochs         : 20
Best Val Top-1 : 20.55%
Best Val Top-5 : 45.53%
Final Val Top-1: 20.55%
Final Val Top-5: 45.53%
Best Val Loss  : 3.9539
Total Time     : 00:12:26
===============================================

  -> int2_qat     top1=20.46% (+24.16pp) size=0.09MB ratio=15.4x

Training: 100%|██████████| 1406/1406 [00:25<00:00, 54.18it/s, acc=7.25%, loss=4.8316]
Validation: 100%|██████████| 157/157 [00:01<00:00, 119.79it/s, loss=4.2974, top1=14.16%, top5=35.15%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=4.8316 train_acc=7.25% | val_loss=4.2974 val_acc=14.16% val_top5=35.15% | lr=9.94e-06 peak_mem=273MB time=27.3s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 51.92it/s, acc=13.27%, loss=4.3399]
Validation: 100%|██████████| 157/157 [00:01<00:00, 125.75it/s, loss=3.9828, top1=19.87%, top5=44.49%]
Epoch   2/20 | train_loss=4.3399 train_acc=13.27% | val_loss=3.9828 val_acc=19.87% val_top5=44.49% | lr=9.76e-06 peak_mem=273MB time=28.4s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.33it/s, acc=16.89%, loss=4.1346]
Validation: 100%|██████████| 157/157 [00:01<00:00, 125.26it/s, loss=3.8307, top1=23.26%, top5=48.27%]
Epoch   3/20 | train_loss=4.1346 train_acc=16.89% | val_loss=3.8307 val_acc=23.26% val_top5=48.27% | lr=9.46e-06 peak_mem=273MB time=25.8s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.86it/s, acc=19.07%, loss=4.0220]
Validation: 100%|██████████| 157/157 [00:01<00:00, 123.07it/s, loss=3.7487, top1=24.68%, top5=51.12%]
Epoch   4/20 | train_loss=4.0220 train_acc=19.07% | val_loss=3.7487 val_acc=24.68% val_top5=51.12% | lr=9.05e-06 peak_mem=273MB time=25.6s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.52it/s, acc=20.99%, loss=3.9284]
Validation: 100%|██████████| 157/157 [00:01<00:00, 124.24it/s, loss=3.7197, top1=25.11%, top5=51.50%]
Epoch   5/20 | train_loss=3.9284 train_acc=20.99% | val_loss=3.7197 val_acc=25.11% val_top5=51.50% | lr=8.54e-06 peak_mem=273MB time=25.8s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 55.42it/s, acc=22.47%, loss=3.8581]
Validation: 100%|██████████| 157/157 [00:01<00:00, 113.57it/s, loss=3.6039, top1=27.81%, top5=54.39%]
Epoch   6/20 | train_loss=3.8581 train_acc=22.47% | val_loss=3.6039 val_acc=27.81% val_top5=54.39% | lr=7.94e-06 peak_mem=273MB time=26.8s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.65it/s, acc=23.27%, loss=3.8101]
Validation: 100%|██████████| 157/157 [00:01<00:00, 114.66it/s, loss=3.5789, top1=28.27%, top5=55.14%]
Epoch   7/20 | train_loss=3.8101 train_acc=23.27% | val_loss=3.5789 val_acc=28.27% val_top5=55.14% | lr=7.27e-06 peak_mem=273MB time=27.6s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 54.13it/s, acc=23.82%, loss=3.7847]
Validation: 100%|██████████| 157/157 [00:01<00:00, 123.48it/s, loss=3.5520, top1=28.78%, top5=55.86%]
Epoch   8/20 | train_loss=3.7847 train_acc=23.82% | val_loss=3.5520 val_acc=28.78% val_top5=55.86% | lr=6.55e-06 peak_mem=273MB time=27.3s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 55.82it/s, acc=24.50%, loss=3.7545]
Validation: 100%|██████████| 157/157 [00:01<00:00, 116.98it/s, loss=3.5315, top1=29.54%, top5=56.06%]
Epoch   9/20 | train_loss=3.7545 train_acc=24.50% | val_loss=3.5315 val_acc=29.54% val_top5=56.06% | lr=5.78e-06 peak_mem=273MB time=26.6s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.04it/s, acc=25.15%, loss=3.7290]
Validation: 100%|██████████| 157/157 [00:01<00:00, 123.82it/s, loss=3.5210, top1=29.74%, top5=56.28%]
Epoch  10/20 | train_loss=3.7290 train_acc=25.15% | val_loss=3.5210 val_acc=29.74% val_top5=56.28% | lr=5.00e-06 peak_mem=273MB time=27.8s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 54.04it/s, acc=25.59%, loss=3.7058]
Validation: 100%|██████████| 157/157 [00:01<00:00, 117.91it/s, loss=3.4940, top1=30.41%, top5=57.42%]
Epoch  11/20 | train_loss=3.7058 train_acc=25.59% | val_loss=3.4940 val_acc=30.41% val_top5=57.42% | lr=4.22e-06 peak_mem=273MB time=27.4s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 54.80it/s, acc=25.92%, loss=3.6989]
Validation: 100%|██████████| 157/157 [00:01<00:00, 116.15it/s, loss=3.4837, top1=30.72%, top5=57.49%]
Epoch  12/20 | train_loss=3.6989 train_acc=25.92% | val_loss=3.4837 val_acc=30.72% val_top5=57.49% | lr=3.45e-06 peak_mem=273MB time=27.1s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 56.93it/s, acc=26.07%, loss=3.6819]
Validation: 100%|██████████| 157/157 [00:01<00:00, 122.42it/s, loss=3.5121, top1=30.30%, top5=56.70%]
Epoch  13/20 | train_loss=3.6819 train_acc=26.07% | val_loss=3.5121 val_acc=30.30% val_top5=56.70% | lr=2.73e-06 peak_mem=273MB time=26.0s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 55.27it/s, acc=26.13%, loss=3.6776]
Validation: 100%|██████████| 157/157 [00:01<00:00, 115.62it/s, loss=3.4639, top1=31.44%, top5=58.11%]
Epoch  14/20 | train_loss=3.6776 train_acc=26.13% | val_loss=3.4639 val_acc=31.44% val_top5=58.11% | lr=2.06e-06 peak_mem=273MB time=26.9s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.09it/s, acc=26.45%, loss=3.6696]
Validation: 100%|██████████| 157/157 [00:01<00:00, 111.36it/s, loss=3.4711, top1=30.82%, top5=57.85%]
Epoch  15/20 | train_loss=3.6696 train_acc=26.45% | val_loss=3.4711 val_acc=30.82% val_top5=57.85% | lr=1.46e-06 peak_mem=273MB time=28.0s
Training: 100%|██████████| 1406/1406 [00:30<00:00, 45.96it/s, acc=26.60%, loss=3.6625]
Validation: 100%|██████████| 157/157 [00:01<00:00, 100.85it/s, loss=3.4675, top1=31.22%, top5=57.97%]
Epoch  16/20 | train_loss=3.6625 train_acc=26.60% | val_loss=3.4675 val_acc=31.22% val_top5=57.97% | lr=9.55e-07 peak_mem=273MB time=32.2s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.67it/s, acc=26.60%, loss=3.6542]
Validation: 100%|██████████| 157/157 [00:01<00:00, 125.99it/s, loss=3.5327, top1=29.83%, top5=55.81%]
Epoch  17/20 | train_loss=3.6542 train_acc=26.60% | val_loss=3.5327 val_acc=29.83% val_top5=55.81% | lr=5.45e-07 peak_mem=273MB time=29.0s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.45it/s, acc=26.74%, loss=3.6589]
Validation: 100%|██████████| 157/157 [00:01<00:00, 107.48it/s, loss=3.4607, top1=31.40%, top5=58.11%]
Epoch  18/20 | train_loss=3.6589 train_acc=26.74% | val_loss=3.4607 val_acc=31.40% val_top5=58.11% | lr=2.45e-07 peak_mem=273MB time=29.4s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 51.87it/s, acc=26.80%, loss=3.6559]
Validation: 100%|██████████| 157/157 [00:01<00:00, 108.33it/s, loss=3.4674, top1=30.91%, top5=58.04%]
Epoch  19/20 | train_loss=3.6559 train_acc=26.80% | val_loss=3.4674 val_acc=30.91% val_top5=58.04% | lr=6.16e-08 peak_mem=273MB time=28.6s
Early stopping at epoch 19

================= Run Summary =================
Model          : ternary_qat_alexnet_bottleneck
Epochs         : 19
Best Val Top-1 : 31.44%
Best Val Top-5 : 58.11%
Final Val Top-1: 30.91%
Final Val Top-5: 58.04%
Best Val Loss  : 3.4639
Total Time     : 00:08:44
===============================================

  -> ternary_qat  top1=31.35% (+13.27pp) size=0.09MB ratio=15.4x

Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.35it/s, acc=1.19%, loss=5.6929]
Validation: 100%|██████████| 157/157 [00:01<00:00, 111.18it/s, loss=5.3876, top1=1.91%, top5=8.00%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=5.6929 train_acc=1.19% | val_loss=5.3876 val_acc=1.91% val_top5=8.00% | lr=9.94e-06 peak_mem=276MB time=27.8s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 51.60it/s, acc=1.87%, loss=5.3393]
Validation: 100%|██████████| 157/157 [00:01<00:00, 128.51it/s, loss=5.1076, top1=3.30%, top5=11.93%]
Epoch   2/20 | train_loss=5.3393 train_acc=1.87% | val_loss=5.1076 val_acc=3.30% val_top5=11.93% | lr=9.76e-06 peak_mem=276MB time=28.5s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 52.23it/s, acc=2.90%, loss=5.1408]
Validation: 100%|██████████| 157/157 [00:01<00:00, 118.89it/s, loss=4.9567, top1=4.35%, top5=16.00%]
Epoch   3/20 | train_loss=5.1408 train_acc=2.90% | val_loss=4.9567 val_acc=4.35% val_top5=16.00% | lr=9.46e-06 peak_mem=276MB time=28.3s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.58it/s, acc=3.78%, loss=5.0252]
Validation: 100%|██████████| 157/157 [00:01<00:00, 123.83it/s, loss=4.8097, top1=5.80%, top5=19.49%]
Epoch   4/20 | train_loss=5.0252 train_acc=3.78% | val_loss=4.8097 val_acc=5.80% val_top5=19.49% | lr=9.05e-06 peak_mem=276MB time=29.1s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 51.40it/s, acc=4.52%, loss=4.9428]
Validation: 100%|██████████| 157/157 [00:01<00:00, 122.80it/s, loss=4.7141, top1=6.74%, top5=21.76%]
Epoch   5/20 | train_loss=4.9428 train_acc=4.52% | val_loss=4.7141 val_acc=6.74% val_top5=21.76% | lr=8.54e-06 peak_mem=276MB time=28.7s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 55.00it/s, acc=5.20%, loss=4.8719]
Validation: 100%|██████████| 157/157 [00:01<00:00, 132.34it/s, loss=4.7393, top1=6.28%, top5=21.41%]
Epoch   6/20 | train_loss=4.8719 train_acc=5.20% | val_loss=4.7393 val_acc=6.28% val_top5=21.41% | lr=7.94e-06 peak_mem=276MB time=26.8s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.91it/s, acc=5.94%, loss=4.8170]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.99it/s, loss=4.6021, top1=8.37%, top5=25.90%]
Epoch   7/20 | train_loss=4.8170 train_acc=5.94% | val_loss=4.6021 val_acc=8.37% val_top5=25.90% | lr=7.27e-06 peak_mem=276MB time=25.5s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.78it/s, acc=6.66%, loss=4.7707]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.11it/s, loss=4.5872, top1=8.39%, top5=25.81%]
Epoch   8/20 | train_loss=4.7707 train_acc=6.66% | val_loss=4.5872 val_acc=8.39% val_top5=25.81% | lr=6.55e-06 peak_mem=276MB time=24.7s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 54.14it/s, acc=6.96%, loss=4.7348]
Validation: 100%|██████████| 157/157 [00:01<00:00, 131.77it/s, loss=4.5248, top1=9.07%, top5=27.98%]
Epoch   9/20 | train_loss=4.7348 train_acc=6.96% | val_loss=4.5248 val_acc=9.07% val_top5=27.98% | lr=5.78e-06 peak_mem=276MB time=27.2s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 56.48it/s, acc=7.45%, loss=4.6994]
Validation: 100%|██████████| 157/157 [00:01<00:00, 135.97it/s, loss=4.4717, top1=10.21%, top5=29.39%]
Epoch  10/20 | train_loss=4.6994 train_acc=7.45% | val_loss=4.4717 val_acc=10.21% val_top5=29.39% | lr=5.00e-06 peak_mem=276MB time=26.1s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 55.71it/s, acc=7.91%, loss=4.6741]
Validation: 100%|██████████| 157/157 [00:01<00:00, 128.10it/s, loss=4.5027, top1=10.11%, top5=28.06%]
Epoch  11/20 | train_loss=4.6741 train_acc=7.91% | val_loss=4.5027 val_acc=10.11% val_top5=28.06% | lr=4.22e-06 peak_mem=276MB time=26.5s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 58.08it/s, acc=8.16%, loss=4.6533]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.23it/s, loss=4.4410, top1=10.78%, top5=29.84%]
Epoch  12/20 | train_loss=4.6533 train_acc=8.16% | val_loss=4.4410 val_acc=10.78% val_top5=29.84% | lr=3.45e-06 peak_mem=276MB time=25.4s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.60it/s, acc=8.31%, loss=4.6388]
Validation: 100%|██████████| 157/157 [00:01<00:00, 152.24it/s, loss=4.4224, top1=11.17%, top5=30.41%]
Epoch  13/20 | train_loss=4.6388 train_acc=8.31% | val_loss=4.4224 val_acc=11.17% val_top5=30.41% | lr=2.73e-06 peak_mem=276MB time=24.7s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.79it/s, acc=8.42%, loss=4.6222]
Validation: 100%|██████████| 157/157 [00:01<00:00, 136.79it/s, loss=4.4235, top1=11.13%, top5=30.30%]
Epoch  14/20 | train_loss=4.6222 train_acc=8.42% | val_loss=4.4235 val_acc=11.13% val_top5=30.30% | lr=2.06e-06 peak_mem=276MB time=24.7s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.47it/s, acc=8.71%, loss=4.6128]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.37it/s, loss=4.3655, top1=12.19%, top5=32.30%]
Epoch  15/20 | train_loss=4.6128 train_acc=8.71% | val_loss=4.3655 val_acc=12.19% val_top5=32.30% | lr=1.46e-06 peak_mem=276MB time=24.7s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 58.81it/s, acc=8.78%, loss=4.6056]
Validation: 100%|██████████| 157/157 [00:01<00:00, 141.57it/s, loss=4.3781, top1=11.67%, top5=32.03%]
Epoch  16/20 | train_loss=4.6056 train_acc=8.78% | val_loss=4.3781 val_acc=11.67% val_top5=32.03% | lr=9.55e-07 peak_mem=276MB time=25.1s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.46it/s, acc=9.01%, loss=4.5977]
Validation: 100%|██████████| 157/157 [00:01<00:00, 108.56it/s, loss=4.4808, top1=10.41%, top5=28.77%]
Epoch  17/20 | train_loss=4.5977 train_acc=9.01% | val_loss=4.4808 val_acc=10.41% val_top5=28.77% | lr=5.45e-07 peak_mem=276MB time=27.8s
Training: 100%|██████████| 1406/1406 [00:30<00:00, 46.17it/s, acc=8.93%, loss=4.6016]
Validation: 100%|██████████| 157/157 [00:01<00:00, 97.57it/s, loss=4.4182, top1=10.94%, top5=30.38%]
Epoch  18/20 | train_loss=4.6016 train_acc=8.93% | val_loss=4.4182 val_acc=10.94% val_top5=30.38% | lr=2.45e-07 peak_mem=276MB time=32.1s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.83it/s, acc=8.95%, loss=4.5970]
Validation: 100%|██████████| 157/157 [00:01<00:00, 96.70it/s, loss=4.4218, top1=11.00%, top5=30.05%]
Epoch  19/20 | train_loss=4.5970 train_acc=8.95% | val_loss=4.4218 val_acc=11.00% val_top5=30.05% | lr=6.16e-08 peak_mem=276MB time=29.3s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 51.16it/s, acc=9.02%, loss=4.5921]
Validation: 100%|██████████| 157/157 [00:01<00:00, 110.68it/s, loss=4.3351, top1=12.54%, top5=32.86%]
Epoch  20/20 | train_loss=4.5921 train_acc=9.02% | val_loss=4.3351 val_acc=12.54% val_top5=32.86% | lr=0.00e+00 peak_mem=276MB time=29.0s

================= Run Summary =================
Model          : binary_qat_alexnet_bottleneck
Epochs         : 20
Best Val Top-1 : 12.54%
Best Val Top-5 : 32.86%
Final Val Top-1: 12.54%
Final Val Top-5: 32.86%
Best Val Loss  : 4.3351
Total Time     : 00:09:02
===============================================

  -> binary_qat   top1=12.62% (+32.00pp) size=0.05MB ratio=29.8x
alexnet_fire

Training: 100%|██████████| 1406/1406 [01:14<00:00, 18.85it/s, acc=6.73%, loss=4.9634]
Validation: 100%|██████████| 157/157 [00:03<00:00, 39.64it/s, loss=5.1309, top1=7.80%, top5=22.62%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=4.9634 train_acc=6.73% | val_loss=5.1309 val_acc=7.80% val_top5=22.62% | lr=9.94e-06 peak_mem=1064MB time=78.6s
Training: 100%|██████████| 1406/1406 [01:15<00:00, 18.68it/s, acc=11.18%, loss=4.5002]
Validation: 100%|██████████| 157/157 [00:04<00:00, 38.19it/s, loss=4.4258, top1=13.91%, top5=34.23%]
Epoch   2/20 | train_loss=4.5002 train_acc=11.18% | val_loss=4.4258 val_acc=13.91% val_top5=34.23% | lr=9.76e-06 peak_mem=1064MB time=79.5s
Training: 100%|██████████| 1406/1406 [01:15<00:00, 18.74it/s, acc=13.79%, loss=4.3151]
Validation: 100%|██████████| 157/157 [00:03<00:00, 40.52it/s, loss=4.4735, top1=14.04%, top5=33.79%]
Epoch   3/20 | train_loss=4.3151 train_acc=13.79% | val_loss=4.4735 val_acc=14.04% val_top5=33.79% | lr=9.46e-06 peak_mem=1064MB time=79.0s
Training: 100%|██████████| 1406/1406 [01:13<00:00, 19.07it/s, acc=15.20%, loss=4.2334]
Validation: 100%|██████████| 157/157 [00:04<00:00, 36.14it/s, loss=3.9449, top1=21.23%, top5=45.27%]
Epoch   4/20 | train_loss=4.2334 train_acc=15.20% | val_loss=3.9449 val_acc=21.23% val_top5=45.27% | lr=9.05e-06 peak_mem=1064MB time=78.1s
Training: 100%|██████████| 1406/1406 [01:16<00:00, 18.49it/s, acc=16.56%, loss=4.1540]
Validation: 100%|██████████| 157/157 [00:04<00:00, 37.65it/s, loss=3.9504, top1=20.58%, top5=45.86%]
Epoch   5/20 | train_loss=4.1540 train_acc=16.56% | val_loss=3.9504 val_acc=20.58% val_top5=45.86% | lr=8.54e-06 peak_mem=1064MB time=80.3s
Training: 100%|██████████| 1406/1406 [01:04<00:00, 21.86it/s, acc=17.72%, loss=4.0908]
Validation: 100%|██████████| 157/157 [00:02<00:00, 54.22it/s, loss=3.8424, top1=22.79%, top5=48.57%]
Epoch   6/20 | train_loss=4.0908 train_acc=17.72% | val_loss=3.8424 val_acc=22.79% val_top5=48.57% | lr=7.94e-06 peak_mem=1064MB time=67.3s
Training: 100%|██████████| 1406/1406 [01:03<00:00, 22.03it/s, acc=18.40%, loss=4.0584]
Validation: 100%|██████████| 157/157 [00:02<00:00, 54.45it/s, loss=3.8652, top1=22.31%, top5=47.84%]
Epoch   7/20 | train_loss=4.0584 train_acc=18.40% | val_loss=3.8652 val_acc=22.31% val_top5=47.84% | lr=7.27e-06 peak_mem=1064MB time=66.8s
Training: 100%|██████████| 1406/1406 [01:03<00:00, 22.16it/s, acc=18.91%, loss=4.0285]
Validation: 100%|██████████| 157/157 [00:02<00:00, 54.92it/s, loss=3.7731, top1=24.08%, top5=50.49%]
Epoch   8/20 | train_loss=4.0285 train_acc=18.91% | val_loss=3.7731 val_acc=24.08% val_top5=50.49% | lr=6.55e-06 peak_mem=1064MB time=66.3s
Training: 100%|██████████| 1406/1406 [01:03<00:00, 22.07it/s, acc=19.18%, loss=4.0065]
Validation: 100%|██████████| 157/157 [00:02<00:00, 55.07it/s, loss=3.9642, top1=20.70%, top5=44.43%]
Epoch   9/20 | train_loss=4.0065 train_acc=19.18% | val_loss=3.9642 val_acc=20.70% val_top5=44.43% | lr=5.78e-06 peak_mem=1064MB time=66.6s
Training: 100%|██████████| 1406/1406 [01:03<00:00, 22.11it/s, acc=19.73%, loss=3.9920]
Validation: 100%|██████████| 157/157 [00:02<00:00, 56.42it/s, loss=3.7137, top1=25.62%, top5=52.44%]
Epoch  10/20 | train_loss=3.9920 train_acc=19.73% | val_loss=3.7137 val_acc=25.62% val_top5=52.44% | lr=5.00e-06 peak_mem=1064MB time=66.4s
Training: 100%|██████████| 1406/1406 [01:04<00:00, 21.95it/s, acc=20.07%, loss=3.9747]
Validation: 100%|██████████| 157/157 [00:03<00:00, 48.90it/s, loss=3.7920, top1=23.63%, top5=50.06%]
Epoch  11/20 | train_loss=3.9747 train_acc=20.07% | val_loss=3.7920 val_acc=23.63% val_top5=50.06% | lr=4.22e-06 peak_mem=1064MB time=67.3s
Training: 100%|██████████| 1406/1406 [01:04<00:00, 21.68it/s, acc=20.32%, loss=3.9640]
Validation: 100%|██████████| 157/157 [00:03<00:00, 49.51it/s, loss=3.7205, top1=25.97%, top5=52.05%]
Epoch  12/20 | train_loss=3.9640 train_acc=20.32% | val_loss=3.7205 val_acc=25.97% val_top5=52.05% | lr=3.45e-06 peak_mem=1064MB time=68.1s
Training: 100%|██████████| 1406/1406 [01:05<00:00, 21.46it/s, acc=20.54%, loss=3.9515]
Validation: 100%|██████████| 157/157 [00:02<00:00, 52.87it/s, loss=3.7901, top1=23.72%, top5=50.56%]
Epoch  13/20 | train_loss=3.9515 train_acc=20.54% | val_loss=3.7901 val_acc=23.72% val_top5=50.56% | lr=2.73e-06 peak_mem=1064MB time=68.5s
Training: 100%|██████████| 1406/1406 [01:04<00:00, 21.81it/s, acc=20.58%, loss=3.9403]
Validation: 100%|██████████| 157/157 [00:02<00:00, 52.94it/s, loss=3.7001, top1=26.11%, top5=52.13%]
Epoch  14/20 | train_loss=3.9403 train_acc=20.58% | val_loss=3.7001 val_acc=26.11% val_top5=52.13% | lr=2.06e-06 peak_mem=1064MB time=67.5s
Training: 100%|██████████| 1406/1406 [01:04<00:00, 21.65it/s, acc=21.00%, loss=3.9318]
Validation: 100%|██████████| 157/157 [00:03<00:00, 49.63it/s, loss=3.6416, top1=26.97%, top5=54.37%]
Epoch  15/20 | train_loss=3.9318 train_acc=21.00% | val_loss=3.6416 val_acc=26.97% val_top5=54.37% | lr=1.46e-06 peak_mem=1064MB time=68.2s
Training: 100%|██████████| 1406/1406 [01:04<00:00, 21.95it/s, acc=21.03%, loss=3.9300]
Validation: 100%|██████████| 157/157 [00:02<00:00, 53.84it/s, loss=3.6510, top1=27.32%, top5=53.77%]
Epoch  16/20 | train_loss=3.9300 train_acc=21.03% | val_loss=3.6510 val_acc=27.32% val_top5=53.77% | lr=9.55e-07 peak_mem=1064MB time=67.0s
Training: 100%|██████████| 1406/1406 [01:05<00:00, 21.62it/s, acc=21.23%, loss=3.9215]
Validation: 100%|██████████| 157/157 [00:03<00:00, 49.72it/s, loss=3.6526, top1=27.31%, top5=53.68%]
Epoch  17/20 | train_loss=3.9215 train_acc=21.23% | val_loss=3.6526 val_acc=27.31% val_top5=53.68% | lr=5.45e-07 peak_mem=1064MB time=68.3s
Training: 100%|██████████| 1406/1406 [01:04<00:00, 21.92it/s, acc=21.17%, loss=3.9191]
Validation: 100%|██████████| 157/157 [00:02<00:00, 54.03it/s, loss=3.7290, top1=25.75%, top5=51.63%]
Epoch  18/20 | train_loss=3.9191 train_acc=21.17% | val_loss=3.7290 val_acc=25.75% val_top5=51.63% | lr=2.45e-07 peak_mem=1064MB time=67.1s
Training: 100%|██████████| 1406/1406 [01:04<00:00, 21.91it/s, acc=21.20%, loss=3.9134]
Validation: 100%|██████████| 157/157 [00:02<00:00, 56.26it/s, loss=3.7143, top1=25.45%, top5=51.93%]
Epoch  19/20 | train_loss=3.9134 train_acc=21.20% | val_loss=3.7143 val_acc=25.45% val_top5=51.93% | lr=6.16e-08 peak_mem=1064MB time=67.0s
Training: 100%|██████████| 1406/1406 [01:03<00:00, 22.19it/s, acc=21.55%, loss=3.8960]
Validation: 100%|██████████| 157/157 [00:02<00:00, 56.82it/s, loss=3.6745, top1=26.83%, top5=53.36%]
Epoch  20/20 | train_loss=3.8960 train_acc=21.55% | val_loss=3.6745 val_acc=26.83% val_top5=53.36% | lr=0.00e+00 peak_mem=1064MB time=66.2s

================= Run Summary =================
Model          : int2_qat_alexnet_fire
Epochs         : 20
Best Val Top-1 : 27.32%
Best Val Top-5 : 53.77%
Final Val Top-1: 26.83%
Final Val Top-5: 53.36%
Best Val Loss  : 3.6510
Total Time     : 00:23:24
===============================================

  -> int2_qat     top1=27.15% (+16.83pp) size=0.13MB ratio=15.6x

Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.19it/s, acc=9.36%, loss=4.6735]
Validation: 100%|██████████| 157/157 [00:01<00:00, 88.62it/s, loss=4.0530, top1=18.80%, top5=42.58%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=4.6735 train_acc=9.36% | val_loss=4.0530 val_acc=18.80% val_top5=42.58% | lr=9.94e-06 peak_mem=749MB time=39.6s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.86it/s, acc=17.50%, loss=4.1418]
Validation: 100%|██████████| 157/157 [00:01<00:00, 88.41it/s, loss=3.7462, top1=25.07%, top5=51.65%]
Epoch   2/20 | train_loss=4.1418 train_acc=17.50% | val_loss=3.7462 val_acc=25.07% val_top5=51.65% | lr=9.76e-06 peak_mem=749MB time=40.0s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.07it/s, acc=21.97%, loss=3.9155]
Validation: 100%|██████████| 157/157 [00:01<00:00, 89.02it/s, loss=3.6815, top1=26.32%, top5=53.40%]
Epoch   3/20 | train_loss=3.9155 train_acc=21.97% | val_loss=3.6815 val_acc=26.32% val_top5=53.40% | lr=9.46e-06 peak_mem=749MB time=39.7s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.13it/s, acc=24.14%, loss=3.8084]
Validation: 100%|██████████| 157/157 [00:01<00:00, 86.55it/s, loss=3.5832, top1=28.63%, top5=55.84%]
Epoch   4/20 | train_loss=3.8084 train_acc=24.14% | val_loss=3.5832 val_acc=28.63% val_top5=55.84% | lr=9.05e-06 peak_mem=749MB time=39.7s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.58it/s, acc=25.25%, loss=3.7486]
Validation: 100%|██████████| 157/157 [00:01<00:00, 81.05it/s, loss=3.5202, top1=30.01%, top5=57.72%]
Epoch   5/20 | train_loss=3.7486 train_acc=25.25% | val_loss=3.5202 val_acc=30.01% val_top5=57.72% | lr=8.54e-06 peak_mem=749MB time=40.4s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.64it/s, acc=26.40%, loss=3.6962]
Validation: 100%|██████████| 157/157 [00:01<00:00, 87.25it/s, loss=3.4576, top1=31.42%, top5=59.57%]
Epoch   6/20 | train_loss=3.6962 train_acc=26.40% | val_loss=3.4576 val_acc=31.42% val_top5=59.57% | lr=7.94e-06 peak_mem=749MB time=40.2s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.72it/s, acc=27.29%, loss=3.6590]
Validation: 100%|██████████| 157/157 [00:01<00:00, 85.17it/s, loss=3.4418, top1=31.57%, top5=59.66%]
Epoch   7/20 | train_loss=3.6590 train_acc=27.29% | val_loss=3.4418 val_acc=31.57% val_top5=59.66% | lr=7.27e-06 peak_mem=749MB time=40.2s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.33it/s, acc=27.80%, loss=3.6341]
Validation: 100%|██████████| 157/157 [00:01<00:00, 85.28it/s, loss=3.4425, top1=32.17%, top5=59.62%]
Epoch   8/20 | train_loss=3.6341 train_acc=27.80% | val_loss=3.4425 val_acc=32.17% val_top5=59.62% | lr=6.55e-06 peak_mem=749MB time=40.6s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.59it/s, acc=28.39%, loss=3.6135]
Validation: 100%|██████████| 157/157 [00:01<00:00, 80.79it/s, loss=3.4829, top1=31.20%, top5=58.31%]
Epoch   9/20 | train_loss=3.6135 train_acc=28.39% | val_loss=3.4829 val_acc=31.20% val_top5=58.31% | lr=5.78e-06 peak_mem=749MB time=40.4s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.78it/s, acc=28.83%, loss=3.5954]
Validation: 100%|██████████| 157/157 [00:01<00:00, 86.51it/s, loss=3.4116, top1=32.96%, top5=60.44%]
Epoch  10/20 | train_loss=3.5954 train_acc=28.83% | val_loss=3.4116 val_acc=32.96% val_top5=60.44% | lr=5.00e-06 peak_mem=749MB time=41.2s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.36it/s, acc=28.98%, loss=3.5774]
Validation: 100%|██████████| 157/157 [00:01<00:00, 79.28it/s, loss=3.4643, top1=31.89%, top5=58.78%]
Epoch  11/20 | train_loss=3.5774 train_acc=28.98% | val_loss=3.4643 val_acc=31.89% val_top5=58.78% | lr=4.22e-06 peak_mem=749MB time=40.7s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.39it/s, acc=29.16%, loss=3.5691]
Validation: 100%|██████████| 157/157 [00:01<00:00, 87.49it/s, loss=3.4658, top1=31.37%, top5=58.39%]
Epoch  12/20 | train_loss=3.5691 train_acc=29.16% | val_loss=3.4658 val_acc=31.37% val_top5=58.39% | lr=3.45e-06 peak_mem=749MB time=41.6s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.72it/s, acc=29.31%, loss=3.5613]
Validation: 100%|██████████| 157/157 [00:02<00:00, 72.37it/s, loss=3.4459, top1=32.15%, top5=59.29%]
Epoch  13/20 | train_loss=3.5613 train_acc=29.31% | val_loss=3.4459 val_acc=32.15% val_top5=59.29% | lr=2.73e-06 peak_mem=749MB time=41.6s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.06it/s, acc=29.50%, loss=3.5543]
Validation: 100%|██████████| 157/157 [00:01<00:00, 83.85it/s, loss=3.5272, top1=30.40%, top5=56.94%]
Epoch  14/20 | train_loss=3.5543 train_acc=29.50% | val_loss=3.5272 val_acc=30.40% val_top5=56.94% | lr=2.06e-06 peak_mem=749MB time=40.9s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.58it/s, acc=29.46%, loss=3.5521]
Validation: 100%|██████████| 157/157 [00:01<00:00, 85.38it/s, loss=3.4559, top1=31.78%, top5=59.13%]
Epoch  15/20 | train_loss=3.5521 train_acc=29.46% | val_loss=3.4559 val_acc=31.78% val_top5=59.13% | lr=1.46e-06 peak_mem=749MB time=41.4s
Early stopping at epoch 15

================= Run Summary =================
Model          : ternary_qat_alexnet_fire
Epochs         : 15
Best Val Top-1 : 32.96%
Best Val Top-5 : 60.44%
Final Val Top-1: 31.78%
Final Val Top-5: 59.13%
Best Val Loss  : 3.4116
Total Time     : 00:10:08
===============================================

  -> ternary_qat  top1=32.81% (+11.17pp) size=0.13MB ratio=15.6x

Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.20it/s, acc=1.45%, loss=5.5576]
Validation: 100%|██████████| 157/157 [00:01<00:00, 89.31it/s, loss=5.2129, top1=2.91%, top5=10.58%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=5.5576 train_acc=1.45% | val_loss=5.2129 val_acc=2.91% val_top5=10.58% | lr=9.94e-06 peak_mem=753MB time=39.6s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.45it/s, acc=2.79%, loss=5.1900]
Validation: 100%|██████████| 157/157 [00:01<00:00, 90.57it/s, loss=4.8973, top1=4.76%, top5=16.47%]
Epoch   2/20 | train_loss=5.1900 train_acc=2.79% | val_loss=4.8973 val_acc=4.76% val_top5=16.47% | lr=9.76e-06 peak_mem=753MB time=39.3s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.35it/s, acc=4.14%, loss=5.0053]
Validation: 100%|██████████| 157/157 [00:01<00:00, 90.41it/s, loss=4.7061, top1=6.81%, top5=21.77%]
Epoch   3/20 | train_loss=5.0053 train_acc=4.14% | val_loss=4.7061 val_acc=6.81% val_top5=21.77% | lr=9.46e-06 peak_mem=753MB time=39.4s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.60it/s, acc=5.60%, loss=4.8694]
Validation: 100%|██████████| 157/157 [00:01<00:00, 92.10it/s, loss=4.5783, top1=8.84%, top5=25.84%]
Epoch   4/20 | train_loss=4.8694 train_acc=5.60% | val_loss=4.5783 val_acc=8.84% val_top5=25.84% | lr=9.05e-06 peak_mem=753MB time=39.2s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.83it/s, acc=6.95%, loss=4.7747]
Validation: 100%|██████████| 157/157 [00:01<00:00, 89.33it/s, loss=4.4818, top1=10.19%, top5=28.57%]
Epoch   5/20 | train_loss=4.7747 train_acc=6.95% | val_loss=4.4818 val_acc=10.19% val_top5=28.57% | lr=8.54e-06 peak_mem=753MB time=39.0s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.59it/s, acc=7.93%, loss=4.7022]
Validation: 100%|██████████| 157/157 [00:01<00:00, 93.67it/s, loss=4.4375, top1=10.79%, top5=30.07%]
Epoch   6/20 | train_loss=4.7022 train_acc=7.93% | val_loss=4.4375 val_acc=10.79% val_top5=30.07% | lr=7.94e-06 peak_mem=753MB time=39.1s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.76it/s, acc=8.66%, loss=4.6456]
Validation: 100%|██████████| 157/157 [00:01<00:00, 90.36it/s, loss=4.3636, top1=12.18%, top5=32.69%]
Epoch   7/20 | train_loss=4.6456 train_acc=8.66% | val_loss=4.3636 val_acc=12.18% val_top5=32.69% | lr=7.27e-06 peak_mem=753MB time=39.0s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.81it/s, acc=9.52%, loss=4.5943]
Validation: 100%|██████████| 157/157 [00:01<00:00, 91.47it/s, loss=4.3104, top1=13.03%, top5=34.31%]
Epoch   8/20 | train_loss=4.5943 train_acc=9.52% | val_loss=4.3104 val_acc=13.03% val_top5=34.31% | lr=6.55e-06 peak_mem=753MB time=39.0s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.78it/s, acc=10.02%, loss=4.5578]
Validation: 100%|██████████| 157/157 [00:01<00:00, 91.12it/s, loss=4.3240, top1=13.02%, top5=33.60%]
Epoch   9/20 | train_loss=4.5578 train_acc=10.02% | val_loss=4.3240 val_acc=13.02% val_top5=33.60% | lr=5.78e-06 peak_mem=753MB time=39.0s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.58it/s, acc=10.62%, loss=4.5260]
Validation: 100%|██████████| 157/157 [00:01<00:00, 89.24it/s, loss=4.3423, top1=12.47%, top5=33.48%]
Epoch  10/20 | train_loss=4.5260 train_acc=10.62% | val_loss=4.3423 val_acc=12.47% val_top5=33.48% | lr=5.00e-06 peak_mem=753MB time=39.2s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.57it/s, acc=10.95%, loss=4.4988]
Validation: 100%|██████████| 157/157 [00:01<00:00, 88.85it/s, loss=4.3494, top1=12.41%, top5=32.93%]
Epoch  11/20 | train_loss=4.4988 train_acc=10.95% | val_loss=4.3494 val_acc=12.41% val_top5=32.93% | lr=4.22e-06 peak_mem=753MB time=39.2s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.73it/s, acc=11.29%, loss=4.4765]
Validation: 100%|██████████| 157/157 [00:01<00:00, 93.07it/s, loss=4.1811, top1=15.81%, top5=38.69%]
Epoch  12/20 | train_loss=4.4765 train_acc=11.29% | val_loss=4.1811 val_acc=15.81% val_top5=38.69% | lr=3.45e-06 peak_mem=753MB time=39.0s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.94it/s, acc=11.43%, loss=4.4656]
Validation: 100%|██████████| 157/157 [00:01<00:00, 91.82it/s, loss=4.3281, top1=12.58%, top5=33.67%]
Epoch  13/20 | train_loss=4.4656 train_acc=11.43% | val_loss=4.3281 val_acc=12.58% val_top5=33.67% | lr=2.73e-06 peak_mem=753MB time=39.8s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.52it/s, acc=11.66%, loss=4.4543]
Validation: 100%|██████████| 157/157 [00:01<00:00, 89.19it/s, loss=4.1795, top1=15.67%, top5=38.92%]
Epoch  14/20 | train_loss=4.4543 train_acc=11.66% | val_loss=4.1795 val_acc=15.67% val_top5=38.92% | lr=2.06e-06 peak_mem=753MB time=39.3s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.70it/s, acc=11.89%, loss=4.4411]
Validation: 100%|██████████| 157/157 [00:01<00:00, 91.70it/s, loss=4.3273, top1=13.38%, top5=34.15%]
Epoch  15/20 | train_loss=4.4411 train_acc=11.89% | val_loss=4.3273 val_acc=13.38% val_top5=34.15% | lr=1.46e-06 peak_mem=753MB time=39.1s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.70it/s, acc=12.07%, loss=4.4322]
Validation: 100%|██████████| 157/157 [00:01<00:00, 91.69it/s, loss=4.3536, top1=12.90%, top5=33.31%]
Epoch  16/20 | train_loss=4.4322 train_acc=12.07% | val_loss=4.3536 val_acc=12.90% val_top5=33.31% | lr=9.55e-07 peak_mem=753MB time=39.1s
Training: 100%|██████████| 1406/1406 [00:37<00:00, 37.79it/s, acc=12.19%, loss=4.4261]
Validation: 100%|██████████| 157/157 [00:01<00:00, 90.40it/s, loss=4.3234, top1=12.65%, top5=34.15%]
Epoch  17/20 | train_loss=4.4261 train_acc=12.19% | val_loss=4.3234 val_acc=12.65% val_top5=34.15% | lr=5.45e-07 peak_mem=753MB time=39.0s
Early stopping at epoch 17

================= Run Summary =================
Model          : binary_qat_alexnet_fire
Epochs         : 17
Best Val Top-1 : 15.81%
Best Val Top-5 : 38.69%
Final Val Top-1: 12.65%
Final Val Top-5: 34.15%
Best Val Loss  : 4.1811
Total Time     : 00:11:06
===============================================

  -> binary_qat   top1=15.85% (+28.13pp) size=0.06MB ratio=30.6x
alexnet_depthwisesep

Training: 100%|██████████| 1406/1406 [00:29<00:00, 48.21it/s, acc=2.12%, loss=6.0383]
Validation: 100%|██████████| 157/157 [00:02<00:00, 75.94it/s, loss=8.6448, top1=0.94%, top5=3.48%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=6.0383 train_acc=2.12% | val_loss=8.6448 val_acc=0.94% val_top5=3.48% | lr=9.94e-06 peak_mem=354MB time=31.3s
Training: 100%|██████████| 1406/1406 [00:28<00:00, 48.86it/s, acc=3.63%, loss=5.4486]
Validation: 100%|██████████| 157/157 [00:02<00:00, 76.98it/s, loss=7.8405, top1=1.15%, top5=4.68%]
Epoch   2/20 | train_loss=5.4486 train_acc=3.63% | val_loss=7.8405 val_acc=1.15% val_top5=4.68% | lr=9.76e-06 peak_mem=354MB time=30.9s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 47.38it/s, acc=4.85%, loss=5.1840]
Validation: 100%|██████████| 157/157 [00:02<00:00, 75.67it/s, loss=10.8146, top1=0.66%, top5=3.01%]
Epoch   3/20 | train_loss=5.1840 train_acc=4.85% | val_loss=10.8146 val_acc=0.66% val_top5=3.01% | lr=9.46e-06 peak_mem=354MB time=31.8s
Training: 100%|██████████| 1406/1406 [00:30<00:00, 46.56it/s, acc=3.04%, loss=5.2982]
Validation: 100%|██████████| 157/157 [00:01<00:00, 79.97it/s, loss=5.1198, top1=3.42%, top5=12.40%]
Epoch   4/20 | train_loss=5.2982 train_acc=3.04% | val_loss=5.1198 val_acc=3.42% val_top5=12.40% | lr=9.05e-06 peak_mem=354MB time=32.2s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 47.17it/s, acc=3.85%, loss=5.0770]
Validation: 100%|██████████| 157/157 [00:02<00:00, 75.84it/s, loss=4.9255, top1=5.13%, top5=17.10%]
Epoch   5/20 | train_loss=5.0770 train_acc=3.85% | val_loss=4.9255 val_acc=5.13% val_top5=17.10% | lr=8.54e-06 peak_mem=354MB time=31.9s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.07it/s, acc=4.92%, loss=4.9723]
Validation: 100%|██████████| 157/157 [00:01<00:00, 119.51it/s, loss=4.7165, top1=7.95%, top5=22.45%]
Epoch   6/20 | train_loss=4.9723 train_acc=4.92% | val_loss=4.7165 val_acc=7.95% val_top5=22.45% | lr=7.94e-06 peak_mem=354MB time=27.9s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.61it/s, acc=5.21%, loss=4.9450]
Validation: 100%|██████████| 157/157 [00:01<00:00, 110.47it/s, loss=4.9174, top1=5.02%, top5=16.48%]
Epoch   7/20 | train_loss=4.9450 train_acc=5.21% | val_loss=4.9174 val_acc=5.02% val_top5=16.48% | lr=7.27e-06 peak_mem=354MB time=27.7s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.26it/s, acc=5.70%, loss=4.8993]
Validation: 100%|██████████| 157/157 [00:01<00:00, 112.35it/s, loss=4.6924, top1=8.10%, top5=23.04%]
Epoch   8/20 | train_loss=4.8993 train_acc=5.70% | val_loss=4.6924 val_acc=8.10% val_top5=23.04% | lr=6.55e-06 peak_mem=354MB time=27.9s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 52.62it/s, acc=6.06%, loss=4.8673]
Validation: 100%|██████████| 157/157 [00:01<00:00, 115.35it/s, loss=4.7711, top1=6.91%, top5=20.78%]
Epoch   9/20 | train_loss=4.8673 train_acc=6.06% | val_loss=4.7711 val_acc=6.91% val_top5=20.78% | lr=5.78e-06 peak_mem=354MB time=28.1s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 55.22it/s, acc=5.99%, loss=4.8827]
Validation: 100%|██████████| 157/157 [00:01<00:00, 116.64it/s, loss=4.5970, top1=9.24%, top5=26.05%]
Epoch  10/20 | train_loss=4.8827 train_acc=5.99% | val_loss=4.5970 val_acc=9.24% val_top5=26.05% | lr=5.00e-06 peak_mem=354MB time=26.9s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 55.39it/s, acc=5.94%, loss=4.8813]
Validation: 100%|██████████| 157/157 [00:01<00:00, 119.24it/s, loss=4.6467, top1=8.72%, top5=23.88%]
Epoch  11/20 | train_loss=4.8813 train_acc=5.94% | val_loss=4.6467 val_acc=8.72% val_top5=23.88% | lr=4.22e-06 peak_mem=354MB time=26.8s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 56.88it/s, acc=6.28%, loss=4.8669]
Validation: 100%|██████████| 157/157 [00:01<00:00, 119.87it/s, loss=4.6315, top1=8.91%, top5=24.51%]
Epoch  12/20 | train_loss=4.8669 train_acc=6.28% | val_loss=4.6315 val_acc=8.91% val_top5=24.51% | lr=3.45e-06 peak_mem=354MB time=26.1s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 54.50it/s, acc=6.27%, loss=4.8676]
Validation: 100%|██████████| 157/157 [00:01<00:00, 119.41it/s, loss=4.6071, top1=9.50%, top5=25.77%]
Epoch  13/20 | train_loss=4.8676 train_acc=6.27% | val_loss=4.6071 val_acc=9.50% val_top5=25.77% | lr=2.73e-06 peak_mem=354MB time=27.2s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 52.35it/s, acc=6.19%, loss=4.8599]
Validation: 100%|██████████| 157/157 [00:01<00:00, 112.04it/s, loss=4.7456, top1=7.52%, top5=22.12%]
Epoch  14/20 | train_loss=4.8599 train_acc=6.19% | val_loss=4.7456 val_acc=7.52% val_top5=22.12% | lr=2.06e-06 peak_mem=354MB time=28.3s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 54.49it/s, acc=6.50%, loss=4.8367]
Validation: 100%|██████████| 157/157 [00:01<00:00, 116.67it/s, loss=4.6537, top1=8.33%, top5=23.77%]
Epoch  15/20 | train_loss=4.8367 train_acc=6.50% | val_loss=4.6537 val_acc=8.33% val_top5=23.77% | lr=1.46e-06 peak_mem=354MB time=27.2s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 51.25it/s, acc=6.71%, loss=4.8225]
Validation: 100%|██████████| 157/157 [00:01<00:00, 111.64it/s, loss=4.5744, top1=9.47%, top5=26.61%]
Epoch  16/20 | train_loss=4.8225 train_acc=6.71% | val_loss=4.5744 val_acc=9.47% val_top5=26.61% | lr=9.55e-07 peak_mem=354MB time=28.9s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 51.70it/s, acc=6.73%, loss=4.8261]
Validation: 100%|██████████| 157/157 [00:01<00:00, 112.08it/s, loss=4.6163, top1=8.86%, top5=25.35%]
Epoch  17/20 | train_loss=4.8261 train_acc=6.73% | val_loss=4.6163 val_acc=8.86% val_top5=25.35% | lr=5.45e-07 peak_mem=354MB time=28.7s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 52.46it/s, acc=6.74%, loss=4.8231]
Validation: 100%|██████████| 157/157 [00:01<00:00, 106.66it/s, loss=4.6183, top1=9.34%, top5=25.06%]
Epoch  18/20 | train_loss=4.8231 train_acc=6.74% | val_loss=4.6183 val_acc=9.34% val_top5=25.06% | lr=2.45e-07 peak_mem=354MB time=28.3s
Early stopping at epoch 18

================= Run Summary =================
Model          : int2_qat_alexnet_depthwisesep
Epochs         : 18
Best Val Top-1 : 9.50%
Best Val Top-5 : 25.77%
Final Val Top-1: 9.34%
Final Val Top-5: 25.06%
Best Val Loss  : 4.6071
Total Time     : 00:08:38
===============================================

  -> int2_qat     top1=9.48% (+34.91pp) size=0.08MB ratio=15.2x

Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.52it/s, acc=3.75%, loss=5.2963]
Validation: 100%|██████████| 157/157 [00:01<00:00, 130.32it/s, loss=4.9069, top1=6.37%, top5=19.89%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=5.2963 train_acc=3.75% | val_loss=4.9069 val_acc=6.37% val_top5=19.89% | lr=9.94e-06 peak_mem=222MB time=25.7s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.33it/s, acc=6.05%, loss=4.9425]
Validation: 100%|██████████| 157/157 [00:01<00:00, 128.50it/s, loss=4.8401, top1=7.01%, top5=21.51%]
Epoch   2/20 | train_loss=4.9425 train_acc=6.05% | val_loss=4.8401 val_acc=7.01% val_top5=21.51% | lr=9.76e-06 peak_mem=222MB time=25.8s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.30it/s, acc=8.07%, loss=4.7474]
Validation: 100%|██████████| 157/157 [00:01<00:00, 122.80it/s, loss=6.4078, top1=2.07%, top5=8.30%]
Epoch   3/20 | train_loss=4.7474 train_acc=8.07% | val_loss=6.4078 val_acc=2.07% val_top5=8.30% | lr=9.46e-06 peak_mem=222MB time=25.9s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.44it/s, acc=9.82%, loss=4.6184]
Validation: 100%|██████████| 157/157 [00:01<00:00, 136.53it/s, loss=4.6761, top1=9.50%, top5=24.98%]
Epoch   4/20 | train_loss=4.6184 train_acc=9.82% | val_loss=4.6761 val_acc=9.50% val_top5=24.98% | lr=9.05e-06 peak_mem=222MB time=24.9s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 61.02it/s, acc=11.24%, loss=4.5199]
Validation: 100%|██████████| 157/157 [00:01<00:00, 136.77it/s, loss=4.6923, top1=9.60%, top5=26.11%]
Epoch   5/20 | train_loss=4.5199 train_acc=11.24% | val_loss=4.6923 val_acc=9.60% val_top5=26.11% | lr=8.54e-06 peak_mem=222MB time=24.2s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.68it/s, acc=12.43%, loss=4.4454]
Validation: 100%|██████████| 157/157 [00:01<00:00, 136.63it/s, loss=4.2853, top1=15.33%, top5=35.73%]
Epoch   6/20 | train_loss=4.4454 train_acc=12.43% | val_loss=4.2853 val_acc=15.33% val_top5=35.73% | lr=7.94e-06 peak_mem=222MB time=24.4s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.08it/s, acc=13.35%, loss=4.3888]
Validation: 100%|██████████| 157/157 [00:01<00:00, 125.54it/s, loss=5.4948, top1=4.62%, top5=14.09%]
Epoch   7/20 | train_loss=4.3888 train_acc=13.35% | val_loss=5.4948 val_acc=4.62% val_top5=14.09% | lr=7.27e-06 peak_mem=222MB time=24.7s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 61.09it/s, acc=14.21%, loss=4.3465]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.17it/s, loss=4.7053, top1=10.06%, top5=26.14%]
Epoch   8/20 | train_loss=4.3465 train_acc=14.21% | val_loss=4.7053 val_acc=10.06% val_top5=26.14% | lr=6.55e-06 peak_mem=222MB time=24.2s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 62.33it/s, acc=14.55%, loss=4.3199]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.24it/s, loss=4.4937, top1=13.32%, top5=31.97%]
Epoch   9/20 | train_loss=4.3199 train_acc=14.55% | val_loss=4.4937 val_acc=13.32% val_top5=31.97% | lr=5.78e-06 peak_mem=222MB time=23.8s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.59it/s, acc=14.95%, loss=4.2941]
Validation: 100%|██████████| 157/157 [00:01<00:00, 121.75it/s, loss=4.4930, top1=12.75%, top5=31.87%]
Epoch  10/20 | train_loss=4.2941 train_acc=14.95% | val_loss=4.4930 val_acc=12.75% val_top5=31.87% | lr=5.00e-06 peak_mem=222MB time=25.8s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 56.39it/s, acc=15.12%, loss=4.2815]
Validation: 100%|██████████| 157/157 [00:01<00:00, 119.34it/s, loss=4.8375, top1=8.05%, top5=22.53%]
Epoch  11/20 | train_loss=4.2815 train_acc=15.12% | val_loss=4.8375 val_acc=8.05% val_top5=22.53% | lr=4.22e-06 peak_mem=222MB time=26.3s
Early stopping at epoch 11

================= Run Summary =================
Model          : ternary_qat_alexnet_depthwisesep
Epochs         : 11
Best Val Top-1 : 15.33%
Best Val Top-5 : 35.73%
Final Val Top-1: 8.05%
Final Val Top-5: 22.53%
Best Val Loss  : 4.2853
Total Time     : 00:04:35
===============================================

  -> ternary_qat  top1=15.17% (+29.22pp) size=0.08MB ratio=15.2x

Training: 100%|██████████| 1406/1406 [00:23<00:00, 58.63it/s, acc=0.83%, loss=5.9415]
Validation: 100%|██████████| 157/157 [00:01<00:00, 136.43it/s, loss=5.6847, top1=1.31%, top5=5.40%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=5.9415 train_acc=0.83% | val_loss=5.6847 val_acc=1.31% val_top5=5.40% | lr=9.94e-06 peak_mem=225MB time=25.2s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.80it/s, acc=1.17%, loss=5.6054]
Validation: 100%|██████████| 157/157 [00:01<00:00, 128.70it/s, loss=5.6379, top1=1.25%, top5=5.51%]
Epoch   2/20 | train_loss=5.6054 train_acc=1.17% | val_loss=5.6379 val_acc=1.25% val_top5=5.51% | lr=9.76e-06 peak_mem=225MB time=24.8s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.60it/s, acc=1.46%, loss=5.4615]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.64it/s, loss=5.3596, top1=1.85%, top5=7.90%]
Epoch   3/20 | train_loss=5.4615 train_acc=1.46% | val_loss=5.3596 val_acc=1.85% val_top5=7.90% | lr=9.46e-06 peak_mem=225MB time=24.4s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 58.63it/s, acc=1.71%, loss=5.3579]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.42it/s, loss=5.2457, top1=2.66%, top5=9.61%]
Epoch   4/20 | train_loss=5.3579 train_acc=1.71% | val_loss=5.2457 val_acc=2.66% val_top5=9.61% | lr=9.05e-06 peak_mem=225MB time=25.2s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.51it/s, acc=2.11%, loss=5.2888]
Validation: 100%|██████████| 157/157 [00:01<00:00, 132.14it/s, loss=5.2108, top1=3.10%, top5=10.67%]
Epoch   5/20 | train_loss=5.2888 train_acc=2.11% | val_loss=5.2108 val_acc=3.10% val_top5=10.67% | lr=8.54e-06 peak_mem=225MB time=24.9s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.14it/s, acc=2.31%, loss=5.2344]
Validation: 100%|██████████| 157/157 [00:01<00:00, 131.41it/s, loss=5.2170, top1=2.94%, top5=10.51%]
Epoch   6/20 | train_loss=5.2344 train_acc=2.31% | val_loss=5.2170 val_acc=2.94% val_top5=10.51% | lr=7.94e-06 peak_mem=225MB time=25.0s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.19it/s, acc=2.58%, loss=5.1961]
Validation: 100%|██████████| 157/157 [00:01<00:00, 126.79it/s, loss=5.0626, top1=4.16%, top5=13.53%]
Epoch   7/20 | train_loss=5.1961 train_acc=2.58% | val_loss=5.0626 val_acc=4.16% val_top5=13.53% | lr=7.27e-06 peak_mem=225MB time=24.7s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.81it/s, acc=2.87%, loss=5.1644]
Validation: 100%|██████████| 157/157 [00:01<00:00, 131.15it/s, loss=5.1685, top1=3.11%, top5=11.07%]
Epoch   8/20 | train_loss=5.1644 train_acc=2.87% | val_loss=5.1685 val_acc=3.11% val_top5=11.07% | lr=6.55e-06 peak_mem=225MB time=24.8s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.16it/s, acc=3.06%, loss=5.1387]
Validation: 100%|██████████| 157/157 [00:01<00:00, 131.11it/s, loss=5.0740, top1=3.62%, top5=12.85%]
Epoch   9/20 | train_loss=5.1387 train_acc=3.06% | val_loss=5.0740 val_acc=3.62% val_top5=12.85% | lr=5.78e-06 peak_mem=225MB time=25.0s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.92it/s, acc=3.21%, loss=5.1115]
Validation: 100%|██████████| 157/157 [00:01<00:00, 132.03it/s, loss=5.0631, top1=3.90%, top5=13.28%]
Epoch  10/20 | train_loss=5.1115 train_acc=3.21% | val_loss=5.0631 val_acc=3.90% val_top5=13.28% | lr=5.00e-06 peak_mem=225MB time=24.7s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.32it/s, acc=3.35%, loss=5.0983]
Validation: 100%|██████████| 157/157 [00:01<00:00, 132.17it/s, loss=5.0387, top1=4.05%, top5=13.81%]
Epoch  11/20 | train_loss=5.0983 train_acc=3.35% | val_loss=5.0387 val_acc=4.05% val_top5=13.81% | lr=4.22e-06 peak_mem=225MB time=24.5s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.96it/s, acc=3.44%, loss=5.0842]
Validation: 100%|██████████| 157/157 [00:01<00:00, 145.95it/s, loss=5.0017, top1=4.43%, top5=14.98%]
Epoch  12/20 | train_loss=5.0842 train_acc=3.44% | val_loss=5.0017 val_acc=4.43% val_top5=14.98% | lr=3.45e-06 peak_mem=225MB time=24.6s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.79it/s, acc=3.59%, loss=5.0676]
Validation: 100%|██████████| 157/157 [00:01<00:00, 129.98it/s, loss=5.2466, top1=2.54%, top5=10.12%]
Epoch  13/20 | train_loss=5.0676 train_acc=3.59% | val_loss=5.2466 val_acc=2.54% val_top5=10.12% | lr=2.73e-06 peak_mem=225MB time=24.4s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 58.93it/s, acc=3.64%, loss=5.0597]
Validation: 100%|██████████| 157/157 [00:01<00:00, 126.79it/s, loss=5.2239, top1=2.67%, top5=11.09%]
Epoch  14/20 | train_loss=5.0597 train_acc=3.64% | val_loss=5.2239 val_acc=2.67% val_top5=11.09% | lr=2.06e-06 peak_mem=225MB time=25.1s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.65it/s, acc=3.74%, loss=5.0541]
Validation: 100%|██████████| 157/157 [00:01<00:00, 133.59it/s, loss=5.2406, top1=2.78%, top5=10.97%]
Epoch  15/20 | train_loss=5.0541 train_acc=3.74% | val_loss=5.2406 val_acc=2.78% val_top5=10.97% | lr=1.46e-06 peak_mem=225MB time=24.8s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 58.34it/s, acc=3.83%, loss=5.0487]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.01it/s, loss=4.9465, top1=4.59%, top5=15.92%]
Epoch  16/20 | train_loss=5.0487 train_acc=3.83% | val_loss=4.9465 val_acc=4.59% val_top5=15.92% | lr=9.55e-07 peak_mem=225MB time=25.3s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.08it/s, acc=3.73%, loss=5.0462]
Validation: 100%|██████████| 157/157 [00:01<00:00, 124.44it/s, loss=5.0692, top1=3.99%, top5=13.32%]
Epoch  17/20 | train_loss=5.0462 train_acc=3.73% | val_loss=5.0692 val_acc=3.99% val_top5=13.32% | lr=5.45e-07 peak_mem=225MB time=24.7s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 58.11it/s, acc=3.85%, loss=5.0489]
Validation: 100%|██████████| 157/157 [00:01<00:00, 135.26it/s, loss=5.4195, top1=2.44%, top5=9.00%]
Epoch  18/20 | train_loss=5.0489 train_acc=3.85% | val_loss=5.4195 val_acc=2.44% val_top5=9.00% | lr=2.45e-07 peak_mem=225MB time=25.4s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 58.37it/s, acc=3.84%, loss=5.0449]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.91it/s, loss=5.0721, top1=4.30%, top5=14.22%]
Epoch  19/20 | train_loss=5.0449 train_acc=3.84% | val_loss=5.0721 val_acc=4.30% val_top5=14.22% | lr=6.16e-08 peak_mem=225MB time=25.3s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.44it/s, acc=3.91%, loss=5.0396]
Validation: 100%|██████████| 157/157 [00:01<00:00, 127.74it/s, loss=5.1855, top1=3.14%, top5=11.17%]
Epoch  20/20 | train_loss=5.0396 train_acc=3.91% | val_loss=5.1855 val_acc=3.14% val_top5=11.17% | lr=0.00e+00 peak_mem=225MB time=24.6s

================= Run Summary =================
Model          : binary_qat_alexnet_depthwisesep
Epochs         : 20
Best Val Top-1 : 4.59%
Best Val Top-5 : 15.92%
Final Val Top-1: 3.14%
Final Val Top-5: 11.17%
Best Val Loss  : 4.9465
Total Time     : 00:08:17
===============================================

  -> binary_qat   top1=4.68% (+39.71pp) size=0.04MB ratio=28.9x
alexnet_final_fire_residual

Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.91it/s, acc=6.33%, loss=5.3127]
Validation: 100%|██████████| 157/157 [00:02<00:00, 54.89it/s, loss=4.9756, top1=9.41%, top5=25.26%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=5.3127 train_acc=6.33% | val_loss=4.9756 val_acc=9.41% val_top5=25.26% | lr=9.94e-06 peak_mem=382MB time=42.1s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.94it/s, acc=10.67%, loss=4.6852]
Validation: 100%|██████████| 157/157 [00:03<00:00, 46.64it/s, loss=4.5677, top1=13.02%, top5=31.60%]
Epoch   2/20 | train_loss=4.6852 train_acc=10.67% | val_loss=4.5677 val_acc=13.02% val_top5=31.60% | lr=9.76e-06 peak_mem=382MB time=42.6s
Training: 100%|██████████| 1406/1406 [00:39<00:00, 35.65it/s, acc=13.89%, loss=4.4006]
Validation: 100%|██████████| 157/157 [00:02<00:00, 54.80it/s, loss=4.1960, top1=17.46%, top5=40.12%]
Epoch   3/20 | train_loss=4.4006 train_acc=13.89% | val_loss=4.1960 val_acc=17.46% val_top5=40.12% | lr=9.46e-06 peak_mem=333MB time=42.4s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.48it/s, acc=16.58%, loss=4.2087]
Validation: 100%|██████████| 157/157 [00:02<00:00, 54.04it/s, loss=3.9045, top1=22.20%, top5=47.51%]
Epoch   4/20 | train_loss=4.2087 train_acc=16.58% | val_loss=3.9045 val_acc=22.20% val_top5=47.51% | lr=9.05e-06 peak_mem=333MB time=41.5s
Training: 100%|██████████| 1406/1406 [00:38<00:00, 36.24it/s, acc=18.08%, loss=4.1127]
Validation: 100%|██████████| 157/157 [00:02<00:00, 55.46it/s, loss=3.7763, top1=24.77%, top5=50.58%]
Epoch   5/20 | train_loss=4.1127 train_acc=18.08% | val_loss=3.7763 val_acc=24.77% val_top5=50.58% | lr=8.54e-06 peak_mem=333MB time=41.7s
Training: 100%|██████████| 1406/1406 [00:28<00:00, 49.38it/s, acc=19.67%, loss=4.0214]
Validation: 100%|██████████| 157/157 [00:01<00:00, 96.07it/s, loss=3.7858, top1=24.88%, top5=50.12%]
Epoch   6/20 | train_loss=4.0214 train_acc=19.67% | val_loss=3.7858 val_acc=24.88% val_top5=50.12% | lr=7.94e-06 peak_mem=333MB time=30.2s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.55it/s, acc=20.32%, loss=3.9861]
Validation: 100%|██████████| 157/157 [00:01<00:00, 92.95it/s, loss=3.6697, top1=27.25%, top5=52.94%]
Epoch   7/20 | train_loss=3.9861 train_acc=20.32% | val_loss=3.6697 val_acc=27.25% val_top5=52.94% | lr=7.27e-06 peak_mem=333MB time=29.6s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 48.03it/s, acc=20.98%, loss=3.9479]
Validation: 100%|██████████| 157/157 [00:01<00:00, 91.87it/s, loss=3.6668, top1=27.03%, top5=53.03%]
Epoch   8/20 | train_loss=3.9479 train_acc=20.98% | val_loss=3.6668 val_acc=27.03% val_top5=53.03% | lr=6.55e-06 peak_mem=333MB time=31.0s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 48.19it/s, acc=21.24%, loss=3.9345]
Validation: 100%|██████████| 157/157 [00:01<00:00, 95.61it/s, loss=3.7260, top1=26.08%, top5=51.84%]
Epoch   9/20 | train_loss=3.9345 train_acc=21.24% | val_loss=3.7260 val_acc=26.08% val_top5=51.84% | lr=5.78e-06 peak_mem=333MB time=30.9s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 47.04it/s, acc=21.63%, loss=3.9212]
Validation: 100%|██████████| 157/157 [00:01<00:00, 86.56it/s, loss=3.7217, top1=26.24%, top5=52.16%]
Epoch  10/20 | train_loss=3.9212 train_acc=21.63% | val_loss=3.7217 val_acc=26.24% val_top5=52.16% | lr=5.00e-06 peak_mem=333MB time=31.8s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 48.18it/s, acc=21.91%, loss=3.9090]
Validation: 100%|██████████| 157/157 [00:01<00:00, 93.24it/s, loss=3.6502, top1=27.42%, top5=53.40%]
Epoch  11/20 | train_loss=3.9090 train_acc=21.91% | val_loss=3.6502 val_acc=27.42% val_top5=53.40% | lr=4.22e-06 peak_mem=333MB time=30.9s
Training: 100%|██████████| 1406/1406 [01:07<00:00, 20.78it/s, acc=22.07%, loss=3.8962]
Validation: 100%|██████████| 157/157 [00:01<00:00, 100.42it/s, loss=3.6242, top1=28.12%, top5=54.22%]
Epoch  12/20 | train_loss=3.8962 train_acc=22.07% | val_loss=3.6242 val_acc=28.12% val_top5=54.22% | lr=3.45e-06 peak_mem=333MB time=69.3s
Training: 100%|██████████| 1406/1406 [00:34<00:00, 40.88it/s, acc=22.51%, loss=3.8744]
Validation: 100%|██████████| 157/157 [00:01<00:00, 101.80it/s, loss=3.7327, top1=25.86%, top5=51.70%]
Epoch  13/20 | train_loss=3.8744 train_acc=22.51% | val_loss=3.7327 val_acc=25.86% val_top5=51.70% | lr=2.73e-06 peak_mem=333MB time=36.0s
Training: 100%|██████████| 1406/1406 [00:31<00:00, 44.64it/s, acc=22.48%, loss=3.8696]
Validation: 100%|██████████| 157/157 [00:01<00:00, 96.36it/s, loss=3.7035, top1=26.97%, top5=52.60%]
Epoch  14/20 | train_loss=3.8696 train_acc=22.48% | val_loss=3.7035 val_acc=26.97% val_top5=52.60% | lr=2.06e-06 peak_mem=333MB time=33.2s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 48.45it/s, acc=22.39%, loss=3.8708]
Validation: 100%|██████████| 157/157 [00:01<00:00, 93.27it/s, loss=3.5997, top1=28.44%, top5=54.78%]
Epoch  15/20 | train_loss=3.8708 train_acc=22.39% | val_loss=3.5997 val_acc=28.44% val_top5=54.78% | lr=1.46e-06 peak_mem=333MB time=30.8s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 47.56it/s, acc=22.56%, loss=3.8634]
Validation: 100%|██████████| 157/157 [00:01<00:00, 91.73it/s, loss=3.7121, top1=26.44%, top5=52.01%]
Epoch  16/20 | train_loss=3.8634 train_acc=22.56% | val_loss=3.7121 val_acc=26.44% val_top5=52.01% | lr=9.55e-07 peak_mem=333MB time=31.3s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 48.05it/s, acc=22.84%, loss=3.8534]
Validation: 100%|██████████| 157/157 [00:01<00:00, 93.68it/s, loss=3.6205, top1=28.69%, top5=54.32%]
Epoch  17/20 | train_loss=3.8534 train_acc=22.84% | val_loss=3.6205 val_acc=28.69% val_top5=54.32% | lr=5.45e-07 peak_mem=333MB time=31.0s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 47.51it/s, acc=23.11%, loss=3.8411]
Validation: 100%|██████████| 157/157 [00:01<00:00, 96.23it/s, loss=3.5736, top1=29.11%, top5=55.81%]
Epoch  18/20 | train_loss=3.8411 train_acc=23.11% | val_loss=3.5736 val_acc=29.11% val_top5=55.81% | lr=2.45e-07 peak_mem=333MB time=31.3s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 47.00it/s, acc=23.02%, loss=3.8473]
Validation: 100%|██████████| 157/157 [00:01<00:00, 91.80it/s, loss=3.6812, top1=26.59%, top5=52.91%]
Epoch  19/20 | train_loss=3.8473 train_acc=23.02% | val_loss=3.6812 val_acc=26.59% val_top5=52.91% | lr=6.16e-08 peak_mem=333MB time=31.7s
Training: 100%|██████████| 1406/1406 [00:29<00:00, 47.32it/s, acc=23.47%, loss=3.8222]
Validation: 100%|██████████| 157/157 [00:01<00:00, 90.13it/s, loss=3.5990, top1=28.46%, top5=54.91%]
Epoch  20/20 | train_loss=3.8222 train_acc=23.47% | val_loss=3.5990 val_acc=28.46% val_top5=54.91% | lr=0.00e+00 peak_mem=333MB time=31.5s

================= Run Summary =================
Model          : int2_qat_alexnet_final_fire_residual
Epochs         : 20
Best Val Top-1 : 29.11%
Best Val Top-5 : 55.81%
Final Val Top-1: 28.46%
Final Val Top-5: 54.91%
Best Val Loss  : 3.5736
Total Time     : 00:12:01
===============================================

  -> int2_qat     top1=28.98% (+20.82pp) size=0.17MB ratio=15.6x

Training: 100%|██████████| 1406/1406 [00:27<00:00, 52.05it/s, acc=9.32%, loss=4.7917]
Validation: 100%|██████████| 157/157 [00:01<00:00, 110.62it/s, loss=4.2035, top1=17.00%, top5=38.96%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=4.7917 train_acc=9.32% | val_loss=4.2035 val_acc=17.00% val_top5=38.96% | lr=9.94e-06 peak_mem=217MB time=28.5s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 54.97it/s, acc=17.21%, loss=4.1704]
Validation: 100%|██████████| 157/157 [00:01<00:00, 111.28it/s, loss=3.8140, top1=24.53%, top5=49.45%]
Epoch   2/20 | train_loss=4.1704 train_acc=17.21% | val_loss=3.8140 val_acc=24.53% val_top5=49.45% | lr=9.76e-06 peak_mem=217MB time=27.0s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 54.12it/s, acc=21.64%, loss=3.9230]
Validation: 100%|██████████| 157/157 [00:01<00:00, 114.02it/s, loss=3.6305, top1=28.19%, top5=54.28%]
Epoch   3/20 | train_loss=3.9230 train_acc=21.64% | val_loss=3.6305 val_acc=28.19% val_top5=54.28% | lr=9.46e-06 peak_mem=217MB time=27.4s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 52.97it/s, acc=24.26%, loss=3.7939]
Validation: 100%|██████████| 157/157 [00:01<00:00, 114.60it/s, loss=3.5161, top1=30.77%, top5=57.31%]
Epoch   4/20 | train_loss=3.7939 train_acc=24.26% | val_loss=3.5161 val_acc=30.77% val_top5=57.31% | lr=9.05e-06 peak_mem=217MB time=28.0s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.24it/s, acc=26.18%, loss=3.7125]
Validation: 100%|██████████| 157/157 [00:01<00:00, 111.51it/s, loss=3.4462, top1=32.45%, top5=58.94%]
Epoch   5/20 | train_loss=3.7125 train_acc=26.18% | val_loss=3.4462 val_acc=32.45% val_top5=58.94% | lr=8.54e-06 peak_mem=217MB time=27.9s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.48it/s, acc=27.38%, loss=3.6537]
Validation: 100%|██████████| 157/157 [00:01<00:00, 120.85it/s, loss=3.4076, top1=33.48%, top5=60.23%]
Epoch   6/20 | train_loss=3.6537 train_acc=27.38% | val_loss=3.4076 val_acc=33.48% val_top5=60.23% | lr=7.94e-06 peak_mem=217MB time=27.6s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.01it/s, acc=28.19%, loss=3.6056]
Validation: 100%|██████████| 157/157 [00:01<00:00, 109.87it/s, loss=3.4252, top1=32.64%, top5=59.41%]
Epoch   7/20 | train_loss=3.6056 train_acc=28.19% | val_loss=3.4252 val_acc=32.64% val_top5=59.41% | lr=7.27e-06 peak_mem=217MB time=28.0s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 52.84it/s, acc=29.02%, loss=3.5708]
Validation: 100%|██████████| 157/157 [00:01<00:00, 108.81it/s, loss=3.4075, top1=33.31%, top5=59.65%]
Epoch   8/20 | train_loss=3.5708 train_acc=29.02% | val_loss=3.4075 val_acc=33.31% val_top5=59.65% | lr=6.55e-06 peak_mem=217MB time=28.1s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 52.94it/s, acc=29.64%, loss=3.5435]
Validation: 100%|██████████| 157/157 [00:01<00:00, 110.63it/s, loss=3.4095, top1=33.03%, top5=59.93%]
Epoch   9/20 | train_loss=3.5435 train_acc=29.64% | val_loss=3.4095 val_acc=33.03% val_top5=59.93% | lr=5.78e-06 peak_mem=217MB time=28.0s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.90it/s, acc=29.96%, loss=3.5264]
Validation: 100%|██████████| 157/157 [00:01<00:00, 117.70it/s, loss=3.3312, top1=35.23%, top5=61.11%]
Epoch  10/20 | train_loss=3.5264 train_acc=29.96% | val_loss=3.3312 val_acc=35.23% val_top5=61.11% | lr=5.00e-06 peak_mem=217MB time=27.5s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 52.11it/s, acc=30.33%, loss=3.5078]
Validation: 100%|██████████| 157/157 [00:01<00:00, 112.45it/s, loss=3.3152, top1=35.60%, top5=62.25%]
Epoch  11/20 | train_loss=3.5078 train_acc=30.33% | val_loss=3.3152 val_acc=35.60% val_top5=62.25% | lr=4.22e-06 peak_mem=217MB time=28.4s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.35it/s, acc=30.46%, loss=3.5006]
Validation: 100%|██████████| 157/157 [00:01<00:00, 113.22it/s, loss=3.3030, top1=35.42%, top5=62.66%]
Epoch  12/20 | train_loss=3.5006 train_acc=30.46% | val_loss=3.3030 val_acc=35.42% val_top5=62.66% | lr=3.45e-06 peak_mem=217MB time=27.8s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.30it/s, acc=30.96%, loss=3.4786]
Validation: 100%|██████████| 157/157 [00:01<00:00, 108.90it/s, loss=3.2918, top1=36.23%, top5=62.55%]
Epoch  13/20 | train_loss=3.4786 train_acc=30.96% | val_loss=3.2918 val_acc=36.23% val_top5=62.55% | lr=2.73e-06 peak_mem=217MB time=27.9s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 52.05it/s, acc=30.79%, loss=3.4832]
Validation: 100%|██████████| 157/157 [00:01<00:00, 121.95it/s, loss=3.4128, top1=33.00%, top5=59.86%]
Epoch  14/20 | train_loss=3.4832 train_acc=30.79% | val_loss=3.4128 val_acc=33.00% val_top5=59.86% | lr=2.06e-06 peak_mem=217MB time=28.4s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.77it/s, acc=31.05%, loss=3.4726]
Validation: 100%|██████████| 157/157 [00:01<00:00, 110.31it/s, loss=3.3008, top1=36.59%, top5=62.36%]
Epoch  15/20 | train_loss=3.4726 train_acc=31.05% | val_loss=3.3008 val_acc=36.59% val_top5=62.36% | lr=1.46e-06 peak_mem=217MB time=27.6s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 52.14it/s, acc=31.31%, loss=3.4698]
Validation: 100%|██████████| 157/157 [00:01<00:00, 113.68it/s, loss=3.3202, top1=36.01%, top5=61.92%]
Epoch  16/20 | train_loss=3.4698 train_acc=31.31% | val_loss=3.3202 val_acc=36.01% val_top5=61.92% | lr=9.55e-07 peak_mem=217MB time=28.4s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 54.86it/s, acc=31.28%, loss=3.4609]
Validation: 100%|██████████| 157/157 [00:01<00:00, 120.14it/s, loss=3.3386, top1=34.75%, top5=61.35%]
Epoch  17/20 | train_loss=3.4609 train_acc=31.28% | val_loss=3.3386 val_acc=34.75% val_top5=61.35% | lr=5.45e-07 peak_mem=217MB time=27.0s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 56.95it/s, acc=31.45%, loss=3.4620]
Validation: 100%|██████████| 157/157 [00:01<00:00, 120.28it/s, loss=3.2915, top1=36.18%, top5=62.56%]
Epoch  18/20 | train_loss=3.4620 train_acc=31.45% | val_loss=3.2915 val_acc=36.18% val_top5=62.56% | lr=2.45e-07 peak_mem=217MB time=26.1s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.61it/s, acc=31.48%, loss=3.4576]
Validation: 100%|██████████| 157/157 [00:01<00:00, 118.17it/s, loss=3.3108, top1=35.28%, top5=62.44%]
Epoch  19/20 | train_loss=3.4576 train_acc=31.48% | val_loss=3.3108 val_acc=35.28% val_top5=62.44% | lr=6.16e-08 peak_mem=217MB time=25.0s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 58.55it/s, acc=31.46%, loss=3.4565]
Validation: 100%|██████████| 157/157 [00:01<00:00, 128.36it/s, loss=3.3009, top1=36.31%, top5=62.38%]
Epoch  20/20 | train_loss=3.4565 train_acc=31.46% | val_loss=3.3009 val_acc=36.31% val_top5=62.38% | lr=0.00e+00 peak_mem=217MB time=25.3s
Early stopping at epoch 20

================= Run Summary =================
Model          : ternary_qat_alexnet_final_fire_residual
Epochs         : 20
Best Val Top-1 : 36.59%
Best Val Top-5 : 62.36%
Final Val Top-1: 36.31%
Final Val Top-5: 62.38%
Best Val Loss  : 3.3008
Total Time     : 00:09:10
===============================================

  -> ternary_qat  top1=36.54% (+13.26pp) size=0.17MB ratio=15.6x

Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.16it/s, acc=1.40%, loss=5.7841]
Validation: 100%|██████████| 157/157 [00:01<00:00, 151.52it/s, loss=5.3571, top1=2.27%, top5=9.48%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=5.7841 train_acc=1.40% | val_loss=5.3571 val_acc=2.27% val_top5=9.48% | lr=9.94e-06 peak_mem=222MB time=23.0s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.09it/s, acc=2.51%, loss=5.3164]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.83it/s, loss=5.0095, top1=4.25%, top5=15.06%]
Epoch   2/20 | train_loss=5.3164 train_acc=2.51% | val_loss=5.0095 val_acc=4.25% val_top5=15.06% | lr=9.76e-06 peak_mem=222MB time=22.5s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.46it/s, acc=3.70%, loss=5.0891]
Validation: 100%|██████████| 157/157 [00:01<00:00, 144.65it/s, loss=4.8150, top1=6.09%, top5=19.62%]
Epoch   3/20 | train_loss=5.0891 train_acc=3.70% | val_loss=4.8150 val_acc=6.09% val_top5=19.62% | lr=9.46e-06 peak_mem=222MB time=22.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.21it/s, acc=4.92%, loss=4.9486]
Validation: 100%|██████████| 157/157 [00:01<00:00, 137.71it/s, loss=4.6816, top1=7.79%, top5=24.18%]
Epoch   4/20 | train_loss=4.9486 train_acc=4.92% | val_loss=4.6816 val_acc=7.79% val_top5=24.18% | lr=9.05e-06 peak_mem=222MB time=21.8s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.06it/s, acc=5.81%, loss=4.8550]
Validation: 100%|██████████| 157/157 [00:01<00:00, 137.26it/s, loss=4.5926, top1=9.38%, top5=26.31%]
Epoch   5/20 | train_loss=4.8550 train_acc=5.81% | val_loss=4.5926 val_acc=9.38% val_top5=26.31% | lr=8.54e-06 peak_mem=222MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.24it/s, acc=6.81%, loss=4.7709]
Validation: 100%|██████████| 157/157 [00:01<00:00, 135.36it/s, loss=4.5055, top1=10.38%, top5=28.95%]
Epoch   6/20 | train_loss=4.7709 train_acc=6.81% | val_loss=4.5055 val_acc=10.38% val_top5=28.95% | lr=7.94e-06 peak_mem=222MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.97it/s, acc=7.63%, loss=4.7107]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.73it/s, loss=4.4270, top1=11.74%, top5=31.04%]
Epoch   7/20 | train_loss=4.7107 train_acc=7.63% | val_loss=4.4270 val_acc=11.74% val_top5=31.04% | lr=7.27e-06 peak_mem=222MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.59it/s, acc=8.29%, loss=4.6640]
Validation: 100%|██████████| 157/157 [00:01<00:00, 154.13it/s, loss=4.4031, top1=12.67%, top5=31.85%]
Epoch   8/20 | train_loss=4.6640 train_acc=8.29% | val_loss=4.4031 val_acc=12.67% val_top5=31.85% | lr=6.55e-06 peak_mem=222MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.64it/s, acc=9.00%, loss=4.6223]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.60it/s, loss=4.3907, top1=12.42%, top5=32.34%]
Epoch   9/20 | train_loss=4.6223 train_acc=9.00% | val_loss=4.3907 val_acc=12.42% val_top5=32.34% | lr=5.78e-06 peak_mem=222MB time=22.0s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.60it/s, acc=9.67%, loss=4.5832]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.70it/s, loss=4.3188, top1=13.53%, top5=34.34%]
Epoch  10/20 | train_loss=4.5832 train_acc=9.67% | val_loss=4.3188 val_acc=13.53% val_top5=34.34% | lr=5.00e-06 peak_mem=222MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 66.98it/s, acc=10.02%, loss=4.5543]
Validation: 100%|██████████| 157/157 [00:01<00:00, 143.76it/s, loss=4.3203, top1=13.57%, top5=34.75%]
Epoch  11/20 | train_loss=4.5543 train_acc=10.02% | val_loss=4.3203 val_acc=13.57% val_top5=34.75% | lr=4.22e-06 peak_mem=222MB time=22.1s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.67it/s, acc=10.59%, loss=4.5193]
Validation: 100%|██████████| 157/157 [00:01<00:00, 133.21it/s, loss=4.2588, top1=14.84%, top5=36.64%]
Epoch  12/20 | train_loss=4.5193 train_acc=10.59% | val_loss=4.2588 val_acc=14.84% val_top5=36.64% | lr=3.45e-06 peak_mem=222MB time=22.0s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.31it/s, acc=10.92%, loss=4.5019]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.84it/s, loss=4.2442, top1=14.81%, top5=36.97%]
Epoch  13/20 | train_loss=4.5019 train_acc=10.92% | val_loss=4.2442 val_acc=14.81% val_top5=36.97% | lr=2.73e-06 peak_mem=222MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.66it/s, acc=11.10%, loss=4.4872]
Validation: 100%|██████████| 157/157 [00:01<00:00, 148.03it/s, loss=4.1916, top1=15.81%, top5=38.53%]
Epoch  14/20 | train_loss=4.4872 train_acc=11.10% | val_loss=4.1916 val_acc=15.81% val_top5=38.53% | lr=2.06e-06 peak_mem=222MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.99it/s, acc=11.27%, loss=4.4712]
Validation: 100%|██████████| 157/157 [00:01<00:00, 143.88it/s, loss=4.2007, top1=16.26%, top5=37.85%]
Epoch  15/20 | train_loss=4.4712 train_acc=11.27% | val_loss=4.2007 val_acc=16.26% val_top5=37.85% | lr=1.46e-06 peak_mem=222MB time=21.5s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.11it/s, acc=11.59%, loss=4.4601]
Validation: 100%|██████████| 157/157 [00:01<00:00, 156.15it/s, loss=4.2065, top1=15.89%, top5=37.70%]
Epoch  16/20 | train_loss=4.4601 train_acc=11.59% | val_loss=4.2065 val_acc=15.89% val_top5=37.70% | lr=9.55e-07 peak_mem=222MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.98it/s, acc=11.75%, loss=4.4513]
Validation: 100%|██████████| 157/157 [00:01<00:00, 152.17it/s, loss=4.1831, top1=16.71%, top5=38.33%]
Epoch  17/20 | train_loss=4.4513 train_acc=11.75% | val_loss=4.1831 val_acc=16.71% val_top5=38.33% | lr=5.45e-07 peak_mem=222MB time=21.5s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.39it/s, acc=11.62%, loss=4.4499]
Validation: 100%|██████████| 157/157 [00:01<00:00, 142.86it/s, loss=4.1855, top1=16.25%, top5=38.64%]
Epoch  18/20 | train_loss=4.4499 train_acc=11.62% | val_loss=4.1855 val_acc=16.25% val_top5=38.64% | lr=2.45e-07 peak_mem=222MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.40it/s, acc=11.74%, loss=4.4470]
Validation: 100%|██████████| 157/157 [00:01<00:00, 135.78it/s, loss=4.1603, top1=16.89%, top5=38.97%]
Epoch  19/20 | train_loss=4.4470 train_acc=11.74% | val_loss=4.1603 val_acc=16.89% val_top5=38.97% | lr=6.16e-08 peak_mem=222MB time=22.1s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.30it/s, acc=11.77%, loss=4.4461]
Validation: 100%|██████████| 157/157 [00:01<00:00, 132.33it/s, loss=4.1650, top1=16.53%, top5=39.24%]
Epoch  20/20 | train_loss=4.4461 train_acc=11.77% | val_loss=4.1650 val_acc=16.53% val_top5=39.24% | lr=0.00e+00 peak_mem=222MB time=22.4s

================= Run Summary =================
Model          : binary_qat_alexnet_final_fire_residual
Epochs         : 20
Best Val Top-1 : 16.89%
Best Val Top-5 : 38.97%
Final Val Top-1: 16.53%
Final Val Top-5: 39.24%
Best Val Loss  : 4.1603
Total Time     : 00:07:20
===============================================

  -> binary_qat   top1=16.92% (+32.87pp) size=0.09MB ratio=30.4x

## 9. Comparison table, per-model summaries & experiment summary

In [14]:
df = build_comparison_table(ROWS)
cols = ["model","method","precision","fp32_baseline_acc","compressed_top1_acc","acc_drop_pp",
        "compression_ratio","compressed_size_mb","latency_ms","acc_per_mb","notes"]
df_out = df[[c for c in cols if c in df.columns]].copy()
df.to_csv(RESULTS_DIR / "final_comparison.csv", index=False)

by_method = (df.groupby("method")
               .agg(mean_top1=("compressed_top1_acc","mean"),
                    mean_drop_pp=("acc_drop_pp","mean"),
                    mean_ratio=("compression_ratio","mean"),
                    mean_acc_per_mb=("acc_per_mb","mean"),
                    n=("model","count"))
               .reset_index())
by_method.to_csv(RESULTS_DIR / "compression_by_method.csv", index=False)

for name, rec in per_model.items():
    with open(RESULTS_DIR / f"{name}_compression_summary.json", "w") as f:
        json.dump(rec, f, indent=2, default=str)

df_out

,model,method,precision,fp32_baseline_acc,compressed_top1_acc,acc_drop_pp,compression_ratio,compressed_size_mb,latency_ms,acc_per_mb,notes
0,alexnet_final_fire_residual,binary_qat,binary,49.793291,16.922915,32.870376,30.402817,0.087219,0.083508,194.027319,"weight-only BWN QAT (STE), per-channel, A=FP32"
1,alexnet_fire,binary_qat,binary,43.976474,15.851358,28.125116,30.579463,0.064100,0.143487,247.290046,"weight-only BWN QAT (STE), per-channel, A=FP32"
2,alexnet_bottleneck,binary_qat,binary,44.622979,12.624389,31.998590,29.755547,0.049000,0.102137,257.641714,"weight-only BWN QAT (STE), per-channel, A=FP32"
3,alexnet_depthwisesep,binary_qat,binary,44.390011,4.683565,39.706446,28.896348,0.040979,0.108463,114.292419,"weight-only BWN QAT (STE), per-channel, A=FP32"
4,mobilenetv2,binary_qat,binary,57.995582,3.561827,54.433754,28.871847,0.324280,0.124406,10.983809,"weight-only BWN QAT (STE), per-channel, A=FP32"
5,alexnet_final_fire_residual,int2_qat,int2,49.793291,28.976917,20.816374,15.603367,0.169945,0.133692,170.507856,"fake-quant W2/A8 QAT, per-channel"
6,alexnet_fire,int2_qat,int2,43.976474,27.147138,16.829336,15.648263,0.125263,0.246888,216.720753,"fake-quant W2/A8 QAT, per-channel"
7,alexnet_bottleneck,int2_qat,int2,44.622979,20.460297,24.162681,15.436591,0.094452,0.134241,216.621330,"fake-quant W2/A8 QAT, per-channel"
8,alexnet_depthwisesep,int2_qat,int2,44.390011,9.482220,34.907791,15.209547,0.077855,0.102341,121.793532,"fake-quant W2/A8 QAT, per-channel"
9,mobilenetv2,int2_qat,int2,57.995582,0.958424,57.037158,15.202976,0.615837,0.295502,1.556294,"fake-quant W2/A8 QAT, per-channel"
10,alexnet_bottleneck,int4_qat,int4,44.622979,44.337183,0.285795,7.866022,0.185356,0.190940,239.199970,"fake-quant W4/A8 QAT, per-channel"
11,alexnet_fire,int4_qat,int4,43.976474,44.255564,-0.279090,7.916954,0.247589,0.483793,178.746001,"fake-quant W4/A8 QAT, per-channel"
12,alexnet_depthwisesep,int4_qat,int4,44.390011,41.324723,3.065288,7.810570,0.151607,0.123792,272.577868,"fake-quant W4/A8 QAT, per-channel"
13,alexnet_final_fire_residual,int4_ptq,int4,49.793291,40.011069,9.782222,7.906212,0.335396,0.193735,119.295077,"fake-quant W4/A8 PTQ, per-channel"
14,alexnet_fire,int4_ptq,int4,43.976474,37.718636,6.257838,7.916954,0.247589,0.471935,152.343678,"fake-quant W4/A8 PTQ, per-channel"
15,alexnet_bottleneck,int4_ptq,int4,44.622979,35.324445,9.298533,7.866022,0.185356,0.190252,190.576073,"fake-quant W4/A8 PTQ, per-channel"
16,alexnet_depthwisesep,int4_ptq,int4,44.390011,9.996489,34.393522,7.810570,0.151607,0.135756,65.936839,"fake-quant W4/A8 PTQ, per-channel"
17,mobilenetv2,int4_ptq,int4,57.995582,3.502605,54.492977,7.808952,1.198952,0.346189,2.921389,"fake-quant W4/A8 PTQ, per-channel"
18,alexnet_fire,mixed,int4/8,43.976474,44.696173,-0.719699,6.706719,0.292267,0.331698,152.929331,per-layer INT4/INT8 (5 hi / 11 lo)
19,alexnet_bottleneck,mixed,int4/8,44.622979,44.609120,0.013858,6.946494,0.209892,0.300873,212.533410,per-layer INT4/INT8 (5 hi / 11 lo)
20,alexnet_depthwisesep,mixed,int4/8,44.390011,44.269145,0.120866,7.502488,0.157833,0.094335,280.481588,per-layer INT4/INT8 (3 hi / 8 lo)
21,mobilenetv2,int8,int8,57.995582,55.413032,2.582550,3.958495,2.365181,0.318327,23.428665,fake-quant W8/A8 PTQ
22,alexnet_final_fire_residual,int8,int8,49.793291,49.757361,0.035930,3.979767,0.666298,0.198092,74.677348,fake-quant W8/A8 PTQ
23,alexnet_bottleneck,int8,int8,44.622979,44.235250,0.387728,3.971013,0.367165,0.180258,120.477979,fake-quant W8/A8 PTQ
24,alexnet_fire,int8,int8,43.976474,43.939316,0.037158,3.982098,0.492241,0.478559,89.263846,fake-quant W8/A8 PTQ
25,alexnet_depthwisesep,int8,int8,44.390011,43.654713,0.735298,3.958851,0.299111,0.127405,145.948025,fake-quant W8/A8 PTQ
26,alexnet_final_fire_residual,ternary_qat,ternary,49.793291,36.537331,13.255960,15.603367,0.169945,0.090011,214.995335,"weight-only TWN QAT (STE), per-channel, A=FP32"
27,alexnet_fire,ternary_qat,ternary,43.976474,32.809520,11.166954,15.648263,0.125263,0.157997,261.924620,"weight-only TWN QAT (STE), per-channel, A=FP32"
28,alexnet_bottleneck,ternary_qat,ternary,44.622979,31.351751,13.271227,15.436591,0.094452,0.118686,331.933499,"weight-only TWN QAT (STE), per-channel, A=FP32"
29,alexnet_depthwisesep,ternary_qat,ternary,44.390011,15.165412,29.224598,15.209547,0.077855,0.102119,194.790796,"weight-only TWN QAT (STE), per-channel, A=FP32"
30,mobilenetv2,ternary_qat,ternary,57.995582,14.413607,43.581975,15.202976,0.615837,0.175517,23.404902,"weight-only TWN QAT (STE), per-channel, A=FP32"

In [15]:
def dominated(r, others):
    for o in others:
        if (o["compressed_top1_acc"] >= r["compressed_top1_acc"]
                and o["compressed_size_mb"] <= r["compressed_size_mb"]
                and o["latency_ms"] <= r["latency_ms"]
                and (o["compressed_top1_acc"] > r["compressed_top1_acc"]
                     or o["compressed_size_mb"] < r["compressed_size_mb"]
                     or o["latency_ms"] < r["latency_ms"])):
            return True
    return False

recs = df.to_dict("records")
pareto = [r for r in recs if not dominated(r, recs)]
pareto_df = pd.DataFrame(pareto).sort_values("compressed_top1_acc", ascending=False)
pareto_df[[c for c in cols if c in pareto_df.columns]].to_csv(RESULTS_DIR / "pareto_frontier.csv", index=False)
print(f"Pareto-optimal: {len(pareto)} of {len(recs)}")
pareto_df[["model","method","compressed_top1_acc","compressed_size_mb","latency_ms"]]

Pareto-optimal: 15 of 31

,model,method,compressed_top1_acc,compressed_size_mb,latency_ms
9,mobilenetv2,int8,55.413032,2.365181,0.318327
10,alexnet_final_fire_residual,int8,49.757361,0.666298,0.198092
6,alexnet_fire,mixed,44.696173,0.292267,0.331698
7,alexnet_bottleneck,mixed,44.609120,0.209892,0.300873
4,alexnet_bottleneck,int4_qat,44.337183,0.185356,0.190940
8,alexnet_depthwisesep,mixed,44.269145,0.157833,0.094335
5,alexnet_depthwisesep,int4_qat,41.324723,0.151607,0.123792
11,alexnet_final_fire_residual,ternary_qat,36.537331,0.169945,0.090011
12,alexnet_fire,ternary_qat,32.809520,0.125263,0.157997
13,alexnet_bottleneck,ternary_qat,31.351751,0.094452,0.118686
0,alexnet_final_fire_residual,binary_qat,16.922915,0.087219,0.083508
1,alexnet_fire,binary_qat,15.851358,0.064100,0.143487
14,alexnet_depthwisesep,ternary_qat,15.165412,0.077855,0.102119
2,alexnet_bottleneck,binary_qat,12.624389,0.049000,0.102137
3,alexnet_depthwisesep,binary_qat,4.683565,0.040979,0.108463

In [16]:
create_results_summary(
    results={
        "phase": "4.1", "title": "Aggressive Model Compression",
        "models": ALL_MODELS,
        "methods": ["int8", "int4_ptq", "int4_qat", "mixed", "int2_ptq", "ternary_ptq", "binary_ptq"],
        "fp32_baseline": fp32_baseline,
        "rows": ROWS,
        "by_method": by_method.to_dict("records"),
        "pareto": pareto_df[["model","method","compressed_top1_acc","compressed_size_mb"]].to_dict("records"),
    },
    config=fp32_cfg,
    output_path=RESULTS_DIR / "experiment_summary.json",
)
print("Saved:", RESULTS_DIR / "experiment_summary.json")

Saved: /home/rafael/Documents/alexnet_rafael/results/compression_phase4_1/experiment_summary.json

## W&B - syncing offline runs

All runs logged offline under project **`alexnet-compression`**, group
**`phase-4-1-compression`**, phase tag `4.1`. Sync when ready:

```bash
wandb sync --sync-all
```