# Final Architecture Study — Phase 4 (FP32 & QAT INT8)

**Author:** Rafael
**Dataset:** Tiny-ImageNet-200 (200 classes, 64x64 RGB)
**Goal:** Combine Phase 3's most successful compensation mechanisms (Bottleneck,
Fire, Residual, Depthwise-Separable) into four hybrid architectures, train each
in FP32, QAT fine-tune, convert to INT8, and compare against every prior phase.

| Model | Mechanisms combined | QAT |
|---|---|---|
| AlexNetFinalBottleneckFire | Bottleneck stem + Fire body | Yes |
| AlexNetFinalFireResidual | Fire + residual shortcuts | Yes |
| AlexNetFinalBottleneckResidual | Bottleneck + residual shortcuts | Yes |
| AlexNetFinalDepthwiseFire | Depthwise-separable stem + Fire body | Yes |

## Notebook layout

1. Imports & reproducibility
2. Dataset & loaders
3. Model shape check
4. Model registration (fuse maps via `find_fuse_groups`)
5. FP32 training
6. QAT training
7. INT8 conversion & CPU evaluation
8. FP32 evaluation (reload best checkpoints)
9. Final comparison table + benchmarks + per-model summaries
10. Ablation study (component contribution)
11. Cross-phase comparison (Phases 1-4)
12. Persist experiment summary

## 1. Imports & reproducibility

In [ ]:
import json
import os
import random
import sys
from dataclasses import asdict, replace
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torchinfo
import wandb

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

from ml import (
    DataConfig, TrainerConfig, QATConfig,
    create_imagenet_loaders,
    MODEL_REGISTRY, register_model,
    Trainer, make_qat_callback,
    build_qat, build_comparison_table,
    load_best_model, convert_to_int8,
    find_fuse_groups,
    auto_resume_path, compress_checkpoint,
    create_results_summary, disk_mb, gzip_mb,
    compute_flops, make_run_summary,
)
from configs.loader import load_config

from models import (
    AlexNetFinalBottleneckFire,
    AlexNetFinalFireResidual,
    AlexNetFinalBottleneckResidual,
    AlexNetFinalDepthwiseFire,
)

torch.backends.quantized.engine = "fbgemm"

In [2]:
SEED = 42
random.seed(SEED); np.random.seed(SEED)
torch.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

SAVE_DIR    = project_root / "checkpoints" / "final_architecture_phase4"
RESULTS_DIR = project_root / "results" / "phase_4_compression_and_final_architecture_training"
SAVE_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

data_cfg = DataConfig(**load_config("data.yaml"))
data_cfg.seed = SEED
fp32_cfg = TrainerConfig(**load_config("training.yaml"))
qat_cfg  = QATConfig(**load_config("qat.yaml"))
print(device)

cuda

## 2. Dataset & loaders

In [3]:
import kagglehub

dataset_path = kagglehub.dataset_download("akash2sharma/tiny-imagenet")
train_path = os.path.join(dataset_path, "tiny-imagenet-200", "train")
data_cfg.dataset_path = train_path
print("Tiny-ImageNet train path:", train_path)

train_ds, val_ds, train_loader, val_loader = create_imagenet_loaders(data_cfg)

print(f"Train samples: {len(train_ds):,}")
print(f"Val   samples: {len(val_ds):,}")
print(f"Classes:       {data_cfg.num_classes}")
print(f"Batches/epoch: train={len(train_loader)}, val={len(val_loader)}")

Tiny-ImageNet train path: /home/rafael/.cache/kagglehub/datasets/akash2sharma/tiny-imagenet/versions/1/tiny-imagenet-200/train
Train samples: 90,000
Val   samples: 10,000
Classes:       200
Batches/epoch: train=1406, val=157

## 3. Model shape check

Four Phase 4 hybrid architectures — all from `models/final_architecture.py`:

| Name | Mechanisms | Head |
|---|---|---|
| AlexNetFinalBottleneckFire | Bottleneck stem + Fire body | Linear(256, 200) |
| AlexNetFinalFireResidual | Fire + residual shortcuts | Linear(256, 200) |
| AlexNetFinalBottleneckResidual | Bottleneck + residual shortcuts | Linear(256, 200) |
| AlexNetFinalDepthwiseFire | Depthwise-separable stem + Fire body | Linear(256, 200) |

All use GAP heads (Phase 3's smallest, most quantization-stable pattern) and are
fully QAT-compatible — no Sigmoid, all skip-adds via `FloatFunctional`.

In [4]:
x = torch.randn(2, 3, data_cfg.img_size, data_cfg.img_size)
for label, ctor in [
    ("AlexNetFinalBottleneckFire",     AlexNetFinalBottleneckFire),
    ("AlexNetFinalFireResidual",       AlexNetFinalFireResidual),
    ("AlexNetFinalBottleneckResidual", AlexNetFinalBottleneckResidual),
    ("AlexNetFinalDepthwiseFire",      AlexNetFinalDepthwiseFire),
]:
    m = ctor().eval()
    with torch.no_grad():
        y = m(x)
    assert y.shape == (2, data_cfg.num_classes), f"{label}: unexpected shape {y.shape}"
    params = sum(p.numel() for p in m.parameters())
    print(f"{label:32s} | params={params/1e6:.3f}M")

AlexNetFinalBottleneckFire       | params=0.506M
AlexNetFinalFireResidual         | params=0.699M
AlexNetFinalBottleneckResidual   | params=0.571M
AlexNetFinalDepthwiseFire        | params=0.475M

## 4. Model registration

All four models use nested block classes (`_AlexBottleneck`, `_FireModule`,
`_FireResBlock`, `_BottleneckResBlock`) — fuse maps are auto-detected via
`find_fuse_groups()`, same approach used for Phase 3's Bottleneck/Residual/Fire.

In [5]:
FUSE_BOTTLENECK_FIRE     = find_fuse_groups(AlexNetFinalBottleneckFire())
FUSE_FIRE_RESIDUAL       = find_fuse_groups(AlexNetFinalFireResidual())
FUSE_BOTTLENECK_RESIDUAL = find_fuse_groups(AlexNetFinalBottleneckResidual())
FUSE_DEPTHWISE_FIRE      = find_fuse_groups(AlexNetFinalDepthwiseFire())

MODEL_REGISTRY.clear()
register_model("alexnet_final_bottleneck_fire",     AlexNetFinalBottleneckFire,     fuse_map=FUSE_BOTTLENECK_FIRE,     lr=1e-3)
register_model("alexnet_final_fire_residual",       AlexNetFinalFireResidual,       fuse_map=FUSE_FIRE_RESIDUAL,       lr=1e-3)
register_model("alexnet_final_bottleneck_residual", AlexNetFinalBottleneckResidual, fuse_map=FUSE_BOTTLENECK_RESIDUAL, lr=1e-3)
register_model("alexnet_final_depthwise_fire",      AlexNetFinalDepthwiseFire,      fuse_map=FUSE_DEPTHWISE_FIRE,      lr=1e-3)

print("Registered:", list(MODEL_REGISTRY))

Registered: ['alexnet_final_bottleneck_fire', 'alexnet_final_fire_residual', 'alexnet_final_bottleneck_residual', 'alexnet_final_depthwise_fire']

## 5. FP32 training

In [6]:
fp32_training_results = {}

for name, spec in MODEL_REGISTRY.items():
    resume_from = auto_resume_path(SAVE_DIR, name)

    run_id = None
    if resume_from:
        meta_path = SAVE_DIR / f"{name}_meta.json"
        if meta_path.exists():
            run_id = json.loads(meta_path.read_text()).get("wandb_run_id")

    model_cfg = replace(fp32_cfg, lr=spec.get("lr", fp32_cfg.lr))
    print("=" * 72)
    print(f"Training: {name}  lr={model_cfg.lr}  epochs={model_cfg.epochs}")
    if resume_from:
        print("(Resuming from checkpoint)")
    print("=" * 72)

    model = spec["ctor"]().to(device)

    run = wandb.init(
        project="alexnet-phase4",
        group="fp32-phase4",
        name=f"{name}_fp32",
        id=run_id,
        resume="allow" if run_id else None,
        config={**asdict(model_cfg), "arch": name, "phase": "fp32",
                "num_classes": data_cfg.num_classes, "img_size": data_cfg.img_size,
                "dataset": "tiny-imagenet-200"},
        tags=["phase4", "final-architecture", "tiny-imagenet", "fp32"],
        mode="offline",
    )

    trainer = Trainer(
        model, train_loader, val_loader, model_cfg,
        device, SAVE_DIR, name, num_classes=data_cfg.num_classes,
        wandb_run=run,
        log_file=SAVE_DIR / f"{name}.log",
    )
    results = trainer.fit(resume_from=resume_from)
    wandb.finish()

    fp32_training_results[name] = results

    del model
    torch.cuda.empty_cache()

print("\nFP32 training complete.")

========================================================================
Training: alexnet_final_bottleneck_fire  lr=0.001  epochs=100
(Resuming from checkpoint)
========================================================================

wandb: WARNING `resume` will be ignored since W&B syncing is set to `offline`. Starting a new run with run id 2rlfwz6x.

Training: 100%|██████████| 1406/1406 [00:22<00:00, 61.69it/s, acc=10.54%, loss=4.4332]
Validation: 100%|██████████| 157/157 [00:01<00:00, 114.03it/s, loss=4.2320, top1=13.92%, top5=35.15%]
wandb: WARNING Saving files without folders. If you want to preserve subdirectories pass base_path to wandb.save, i.e. wandb.save("/mnt/folder/file.h5", base_path="/mnt")
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   3/100 | train_loss=4.4332 train_acc=10.54% | val_loss=4.2320 val_acc=13.92% val_top5=35.15% | lr=9.98e-04 peak_mem=147MB time=24.2s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.62it/s, acc=13.22%, loss=4.2798]
Validation: 100%|██████████| 157/157 [00:01<00:00, 151.44it/s, loss=3.9782, top1=18.84%, top5=42.88%]
Epoch   4/100 | train_loss=4.2798 train_acc=13.22% | val_loss=3.9782 val_acc=18.84% val_top5=42.88% | lr=9.96e-04 peak_mem=147MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.73it/s, acc=15.20%, loss=4.1757]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.71it/s, loss=3.8699, top1=21.45%, top5=47.00%]
Epoch   5/100 | train_loss=4.1757 train_acc=15.20% | val_loss=3.8699 val_acc=21.45% val_top5=47.00% | lr=9.94e-04 peak_mem=147MB time=20.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.23it/s, acc=17.39%, loss=4.0680]
Validation: 100%|██████████| 157/157 [00:01<00:00, 151.27it/s, loss=3.8196, top1=22.50%, top5=48.10%]
Epoch   6/100 | train_loss=4.0680 train_acc=17.39% | val_loss=3.8196 val_acc=22.50% val_top5=48.10% | lr=9.91e-04 peak_mem=147MB time=21.4s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.88it/s, acc=19.12%, loss=3.9797]
Validation: 100%|██████████| 157/157 [00:01<00:00, 133.25it/s, loss=3.6630, top1=24.94%, top5=52.36%]
Epoch   7/100 | train_loss=3.9797 train_acc=19.12% | val_loss=3.6630 val_acc=24.94% val_top5=52.36% | lr=9.88e-04 peak_mem=147MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.42it/s, acc=20.84%, loss=3.9077]
Validation: 100%|██████████| 157/157 [00:01<00:00, 154.35it/s, loss=3.6074, top1=27.00%, top5=54.56%]
Epoch   8/100 | train_loss=3.9077 train_acc=20.84% | val_loss=3.6074 val_acc=27.00% val_top5=54.56% | lr=9.84e-04 peak_mem=147MB time=20.8s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.83it/s, acc=22.18%, loss=3.8365]
Validation: 100%|██████████| 157/157 [00:00<00:00, 158.53it/s, loss=3.5643, top1=28.01%, top5=55.44%]
Epoch   9/100 | train_loss=3.8365 train_acc=22.18% | val_loss=3.5643 val_acc=28.01% val_top5=55.44% | lr=9.80e-04 peak_mem=147MB time=20.9s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.88it/s, acc=23.71%, loss=3.7754]
Validation: 100%|██████████| 157/157 [00:01<00:00, 137.14it/s, loss=3.5307, top1=29.16%, top5=56.49%]
Epoch  10/100 | train_loss=3.7754 train_acc=23.71% | val_loss=3.5307 val_acc=29.16% val_top5=56.49% | lr=9.76e-04 peak_mem=147MB time=22.2s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.69it/s, acc=24.78%, loss=3.7208]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.15it/s, loss=3.4786, top1=30.39%, top5=57.36%]
Epoch  11/100 | train_loss=3.7208 train_acc=24.78% | val_loss=3.4786 val_acc=30.39% val_top5=57.36% | lr=9.70e-04 peak_mem=147MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 62.17it/s, acc=25.85%, loss=3.6753]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.50it/s, loss=3.4691, top1=31.34%, top5=58.51%]
Epoch  12/100 | train_loss=3.6753 train_acc=25.85% | val_loss=3.4691 val_acc=31.34% val_top5=58.51% | lr=9.65e-04 peak_mem=147MB time=23.8s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.42it/s, acc=26.84%, loss=3.6305]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.26it/s, loss=3.3654, top1=33.29%, top5=60.68%]
Epoch  13/100 | train_loss=3.6305 train_acc=26.84% | val_loss=3.3654 val_acc=33.29% val_top5=60.68% | lr=9.59e-04 peak_mem=147MB time=23.0s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.92it/s, acc=27.90%, loss=3.5940]
Validation: 100%|██████████| 157/157 [00:00<00:00, 158.83it/s, loss=3.3386, top1=33.80%, top5=61.81%]
Epoch  14/100 | train_loss=3.5940 train_acc=27.90% | val_loss=3.3386 val_acc=33.80% val_top5=61.81% | lr=9.52e-04 peak_mem=147MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.48it/s, acc=28.70%, loss=3.5556]
Validation: 100%|██████████| 157/157 [00:01<00:00, 150.18it/s, loss=3.3080, top1=34.82%, top5=62.71%]
Epoch  15/100 | train_loss=3.5556 train_acc=28.70% | val_loss=3.3080 val_acc=34.82% val_top5=62.71% | lr=9.46e-04 peak_mem=147MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.94it/s, acc=29.16%, loss=3.5294]
Validation: 100%|██████████| 157/157 [00:01<00:00, 137.68it/s, loss=3.2744, top1=35.11%, top5=63.60%]
Epoch  16/100 | train_loss=3.5294 train_acc=29.16% | val_loss=3.2744 val_acc=35.11% val_top5=63.60% | lr=9.38e-04 peak_mem=147MB time=22.2s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.66it/s, acc=30.01%, loss=3.5010]
Validation: 100%|██████████| 157/157 [00:01<00:00, 141.03it/s, loss=3.3076, top1=34.70%, top5=62.57%]
Epoch  17/100 | train_loss=3.5010 train_acc=30.01% | val_loss=3.3076 val_acc=34.70% val_top5=62.57% | lr=9.30e-04 peak_mem=147MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.75it/s, acc=30.65%, loss=3.4712]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.21it/s, loss=3.2501, top1=36.25%, top5=64.05%]
Epoch  18/100 | train_loss=3.4712 train_acc=30.65% | val_loss=3.2501 val_acc=36.25% val_top5=64.05% | lr=9.22e-04 peak_mem=147MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 63.80it/s, acc=31.17%, loss=3.4478]
Validation: 100%|██████████| 157/157 [00:01<00:00, 147.97it/s, loss=3.2166, top1=37.41%, top5=64.58%]
Epoch  19/100 | train_loss=3.4478 train_acc=31.17% | val_loss=3.2166 val_acc=37.41% val_top5=64.58% | lr=9.14e-04 peak_mem=147MB time=23.2s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.39it/s, acc=31.78%, loss=3.4182]
Validation: 100%|██████████| 157/157 [00:01<00:00, 133.12it/s, loss=3.2269, top1=36.88%, top5=64.43%]
Epoch  20/100 | train_loss=3.4182 train_acc=31.78% | val_loss=3.2269 val_acc=36.88% val_top5=64.43% | lr=9.05e-04 peak_mem=147MB time=24.5s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 63.24it/s, acc=32.31%, loss=3.3996]
Validation: 100%|██████████| 157/157 [00:01<00:00, 136.77it/s, loss=3.2560, top1=36.15%, top5=63.46%]
Epoch  21/100 | train_loss=3.3996 train_acc=32.31% | val_loss=3.2560 val_acc=36.15% val_top5=63.46% | lr=8.95e-04 peak_mem=147MB time=23.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.23it/s, acc=32.86%, loss=3.3769]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.65it/s, loss=3.1717, top1=38.58%, top5=65.53%]
Epoch  22/100 | train_loss=3.3769 train_acc=32.86% | val_loss=3.1717 val_acc=38.58% val_top5=65.53% | lr=8.85e-04 peak_mem=147MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.21it/s, acc=33.30%, loss=3.3563]
Validation: 100%|██████████| 157/157 [00:01<00:00, 122.86it/s, loss=3.2152, top1=37.56%, top5=64.70%]
Epoch  23/100 | train_loss=3.3563 train_acc=33.30% | val_loss=3.2152 val_acc=37.56% val_top5=64.70% | lr=8.75e-04 peak_mem=147MB time=22.6s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.19it/s, acc=33.73%, loss=3.3365]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.26it/s, loss=3.1425, top1=39.31%, top5=66.16%]
Epoch  24/100 | train_loss=3.3365 train_acc=33.73% | val_loss=3.1425 val_acc=39.31% val_top5=66.16% | lr=8.64e-04 peak_mem=147MB time=22.8s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.68it/s, acc=34.30%, loss=3.3179]
Validation: 100%|██████████| 157/157 [00:01<00:00, 144.81it/s, loss=3.1842, top1=37.66%, top5=65.12%]
Epoch  25/100 | train_loss=3.3179 train_acc=34.30% | val_loss=3.1842 val_acc=37.66% val_top5=65.12% | lr=8.54e-04 peak_mem=147MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.80it/s, acc=34.96%, loss=3.2929]
Validation: 100%|██████████| 157/157 [00:01<00:00, 141.85it/s, loss=3.1908, top1=38.14%, top5=65.11%]
Epoch  26/100 | train_loss=3.2929 train_acc=34.96% | val_loss=3.1908 val_acc=38.14% val_top5=65.11% | lr=8.42e-04 peak_mem=147MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.55it/s, acc=35.41%, loss=3.2793]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.44it/s, loss=3.1435, top1=38.97%, top5=66.76%]
Epoch  27/100 | train_loss=3.2793 train_acc=35.41% | val_loss=3.1435 val_acc=38.97% val_top5=66.76% | lr=8.31e-04 peak_mem=147MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.34it/s, acc=35.64%, loss=3.2648]
Validation: 100%|██████████| 157/157 [00:01<00:00, 137.36it/s, loss=3.1399, top1=39.43%, top5=66.60%]
Epoch  28/100 | train_loss=3.2648 train_acc=35.64% | val_loss=3.1399 val_acc=39.43% val_top5=66.60% | lr=8.19e-04 peak_mem=147MB time=21.8s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.53it/s, acc=35.97%, loss=3.2521]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.31it/s, loss=3.0815, top1=40.88%, top5=68.00%]
Epoch  29/100 | train_loss=3.2521 train_acc=35.97% | val_loss=3.0815 val_acc=40.88% val_top5=68.00% | lr=8.06e-04 peak_mem=147MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.08it/s, acc=36.28%, loss=3.2333]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.53it/s, loss=3.1082, top1=40.20%, top5=67.47%]
Epoch  30/100 | train_loss=3.2333 train_acc=36.28% | val_loss=3.1082 val_acc=40.20% val_top5=67.47% | lr=7.94e-04 peak_mem=147MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.14it/s, acc=36.73%, loss=3.2207]
Validation: 100%|██████████| 157/157 [00:00<00:00, 163.87it/s, loss=3.1124, top1=39.73%, top5=67.32%]
Epoch  31/100 | train_loss=3.2207 train_acc=36.73% | val_loss=3.1124 val_acc=39.73% val_top5=67.32% | lr=7.81e-04 peak_mem=147MB time=20.8s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.82it/s, acc=37.14%, loss=3.2006]
Validation: 100%|██████████| 157/157 [00:01<00:00, 153.76it/s, loss=3.0511, top1=41.53%, top5=68.52%]
Epoch  32/100 | train_loss=3.2006 train_acc=37.14% | val_loss=3.0511 val_acc=41.53% val_top5=68.52% | lr=7.68e-04 peak_mem=147MB time=20.9s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.35it/s, acc=37.56%, loss=3.1901]
Validation: 100%|██████████| 157/157 [00:01<00:00, 144.60it/s, loss=3.0530, top1=41.51%, top5=68.54%]
Epoch  33/100 | train_loss=3.1901 train_acc=37.56% | val_loss=3.0530 val_acc=41.51% val_top5=68.54% | lr=7.55e-04 peak_mem=147MB time=20.9s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.13it/s, acc=37.79%, loss=3.1792]
Validation: 100%|██████████| 157/157 [00:01<00:00, 154.74it/s, loss=3.0590, top1=41.62%, top5=67.97%]
Epoch  34/100 | train_loss=3.1792 train_acc=37.79% | val_loss=3.0590 val_acc=41.62% val_top5=67.97% | lr=7.41e-04 peak_mem=147MB time=20.8s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.47it/s, acc=37.96%, loss=3.1686]
Validation: 100%|██████████| 157/157 [00:01<00:00, 154.69it/s, loss=3.0535, top1=42.32%, top5=68.51%]
Epoch  35/100 | train_loss=3.1686 train_acc=37.96% | val_loss=3.0535 val_acc=42.32% val_top5=68.51% | lr=7.27e-04 peak_mem=147MB time=21.0s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.04it/s, acc=38.42%, loss=3.1515]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.34it/s, loss=3.0244, top1=42.19%, top5=69.03%]
Epoch  36/100 | train_loss=3.1515 train_acc=38.42% | val_loss=3.0244 val_acc=42.19% val_top5=69.03% | lr=7.13e-04 peak_mem=147MB time=21.0s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.23it/s, acc=38.88%, loss=3.1388]
Validation: 100%|██████████| 157/157 [00:01<00:00, 145.12it/s, loss=3.0449, top1=41.93%, top5=68.29%]
Epoch  37/100 | train_loss=3.1388 train_acc=38.88% | val_loss=3.0449 val_acc=41.93% val_top5=68.29% | lr=6.99e-04 peak_mem=147MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.23it/s, acc=38.78%, loss=3.1308]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.16it/s, loss=3.0408, top1=41.91%, top5=68.65%]
Epoch  38/100 | train_loss=3.1308 train_acc=38.78% | val_loss=3.0408 val_acc=41.91% val_top5=68.65% | lr=6.84e-04 peak_mem=147MB time=21.4s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.65it/s, acc=39.05%, loss=3.1183]
Validation: 100%|██████████| 157/157 [00:01<00:00, 144.97it/s, loss=3.0933, top1=41.14%, top5=67.40%]
Epoch  39/100 | train_loss=3.1183 train_acc=39.05% | val_loss=3.0933 val_acc=41.14% val_top5=67.40% | lr=6.69e-04 peak_mem=147MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.14it/s, acc=39.39%, loss=3.1080]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.48it/s, loss=3.0613, top1=41.25%, top5=68.04%]
Epoch  40/100 | train_loss=3.1080 train_acc=39.39% | val_loss=3.0613 val_acc=41.25% val_top5=68.04% | lr=6.55e-04 peak_mem=147MB time=21.8s
Early stopping at epoch 40

================= Run Summary =================
Model          : alexnet_final_bottleneck_fire
Epochs         : 40
Best Val Top-1 : 42.32%
Best Val Top-5 : 68.51%
Final Val Top-1: 41.25%
Final Val Top-5: 68.04%
Best Val Loss  : 3.0535
Total Time     : 00:13:56
===============================================

========================================================================
Training: alexnet_final_fire_residual  lr=0.001  epochs=100
========================================================================

Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.09it/s, acc=5.09%, loss=4.8533]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.20it/s, loss=4.4798, top1=10.57%, top5=28.56%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/100 | train_loss=4.8533 train_acc=5.09% | val_loss=4.4798 val_acc=10.57% val_top5=28.56% | lr=1.00e-03 peak_mem=142MB time=20.9s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.57it/s, acc=10.22%, loss=4.4664]
Validation: 100%|██████████| 157/157 [00:01<00:00, 154.91it/s, loss=4.2184, top1=14.59%, top5=36.28%]
Epoch   2/100 | train_loss=4.4664 train_acc=10.22% | val_loss=4.2184 val_acc=14.59% val_top5=36.28% | lr=9.99e-04 peak_mem=142MB time=20.7s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.71it/s, acc=14.03%, loss=4.2477]
Validation: 100%|██████████| 157/157 [00:00<00:00, 158.17it/s, loss=3.9744, top1=18.62%, top5=44.04%]
Epoch   3/100 | train_loss=4.2477 train_acc=14.03% | val_loss=3.9744 val_acc=18.62% val_top5=44.04% | lr=9.98e-04 peak_mem=142MB time=20.7s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.71it/s, acc=16.79%, loss=4.0990]
Validation: 100%|██████████| 157/157 [00:01<00:00, 150.20it/s, loss=3.8260, top1=22.97%, top5=48.18%]
Epoch   4/100 | train_loss=4.0990 train_acc=16.79% | val_loss=3.8260 val_acc=22.97% val_top5=48.18% | lr=9.96e-04 peak_mem=142MB time=20.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.74it/s, acc=19.51%, loss=3.9774]
Validation: 100%|██████████| 157/157 [00:00<00:00, 165.02it/s, loss=3.7621, top1=24.54%, top5=50.05%]
Epoch   5/100 | train_loss=3.9774 train_acc=19.51% | val_loss=3.7621 val_acc=24.54% val_top5=50.05% | lr=9.94e-04 peak_mem=142MB time=21.8s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.48it/s, acc=21.65%, loss=3.8736]
Validation: 100%|██████████| 157/157 [00:00<00:00, 158.01it/s, loss=3.6740, top1=26.52%, top5=52.57%]
Epoch   6/100 | train_loss=3.8736 train_acc=21.65% | val_loss=3.6740 val_acc=26.52% val_top5=52.57% | lr=9.91e-04 peak_mem=142MB time=22.5s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.21it/s, acc=23.42%, loss=3.7926]
Validation: 100%|██████████| 157/157 [00:01<00:00, 145.50it/s, loss=3.5541, top1=29.11%, top5=56.11%]
Epoch   7/100 | train_loss=3.7926 train_acc=23.42% | val_loss=3.5541 val_acc=29.11% val_top5=56.11% | lr=9.88e-04 peak_mem=142MB time=21.5s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.43it/s, acc=25.20%, loss=3.7182]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.53it/s, loss=3.5353, top1=29.52%, top5=56.71%]
Epoch   8/100 | train_loss=3.7182 train_acc=25.20% | val_loss=3.5353 val_acc=29.52% val_top5=56.71% | lr=9.84e-04 peak_mem=142MB time=22.3s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.58it/s, acc=26.37%, loss=3.6596]
Validation: 100%|██████████| 157/157 [00:01<00:00, 137.13it/s, loss=3.4869, top1=30.89%, top5=57.73%]
Epoch   9/100 | train_loss=3.6596 train_acc=26.37% | val_loss=3.4869 val_acc=30.89% val_top5=57.73% | lr=9.80e-04 peak_mem=142MB time=22.0s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.38it/s, acc=27.68%, loss=3.6027]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.49it/s, loss=3.4265, top1=31.98%, top5=59.43%]
Epoch  10/100 | train_loss=3.6027 train_acc=27.68% | val_loss=3.4265 val_acc=31.98% val_top5=59.43% | lr=9.76e-04 peak_mem=142MB time=22.7s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 63.65it/s, acc=28.88%, loss=3.5469]
Validation: 100%|██████████| 157/157 [00:01<00:00, 130.32it/s, loss=3.2869, top1=35.65%, top5=62.84%]
Epoch  11/100 | train_loss=3.5469 train_acc=28.88% | val_loss=3.2869 val_acc=35.65% val_top5=62.84% | lr=9.70e-04 peak_mem=142MB time=23.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.92it/s, acc=30.22%, loss=3.5023]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.65it/s, loss=3.2760, top1=35.86%, top5=63.28%]
Epoch  12/100 | train_loss=3.5023 train_acc=30.22% | val_loss=3.2760 val_acc=35.86% val_top5=63.28% | lr=9.65e-04 peak_mem=142MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.35it/s, acc=31.08%, loss=3.4630]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.73it/s, loss=3.2809, top1=35.67%, top5=63.47%]
Epoch  13/100 | train_loss=3.4630 train_acc=31.08% | val_loss=3.2809 val_acc=35.67% val_top5=63.47% | lr=9.59e-04 peak_mem=142MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.27it/s, acc=31.81%, loss=3.4279]
Validation: 100%|██████████| 157/157 [00:01<00:00, 127.63it/s, loss=3.2202, top1=37.18%, top5=64.20%]
Epoch  14/100 | train_loss=3.4279 train_acc=31.81% | val_loss=3.2202 val_acc=37.18% val_top5=64.20% | lr=9.52e-04 peak_mem=142MB time=22.8s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 62.39it/s, acc=32.60%, loss=3.3911]
Validation: 100%|██████████| 157/157 [00:01<00:00, 144.20it/s, loss=3.2286, top1=37.13%, top5=64.58%]
Epoch  15/100 | train_loss=3.3911 train_acc=32.60% | val_loss=3.2286 val_acc=37.13% val_top5=64.58% | lr=9.46e-04 peak_mem=142MB time=23.7s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.39it/s, acc=33.36%, loss=3.3638]
Validation: 100%|██████████| 157/157 [00:01<00:00, 152.66it/s, loss=3.2279, top1=37.11%, top5=64.43%]
Epoch  16/100 | train_loss=3.3638 train_acc=33.36% | val_loss=3.2279 val_acc=37.11% val_top5=64.43% | lr=9.38e-04 peak_mem=142MB time=22.3s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.30it/s, acc=33.93%, loss=3.3347]
Validation: 100%|██████████| 157/157 [00:01<00:00, 145.06it/s, loss=3.1843, top1=38.42%, top5=65.30%]
Epoch  17/100 | train_loss=3.3347 train_acc=33.93% | val_loss=3.1843 val_acc=38.42% val_top5=65.30% | lr=9.30e-04 peak_mem=142MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.45it/s, acc=34.63%, loss=3.3131]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.76it/s, loss=3.1610, top1=38.64%, top5=65.82%]
Epoch  18/100 | train_loss=3.3131 train_acc=34.63% | val_loss=3.1610 val_acc=38.64% val_top5=65.82% | lr=9.22e-04 peak_mem=142MB time=22.0s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 66.97it/s, acc=35.19%, loss=3.2841]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.66it/s, loss=3.1251, top1=40.38%, top5=66.77%]
Epoch  19/100 | train_loss=3.2841 train_acc=35.19% | val_loss=3.1251 val_acc=40.38% val_top5=66.77% | lr=9.14e-04 peak_mem=142MB time=22.2s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.13it/s, acc=35.57%, loss=3.2658]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.22it/s, loss=3.0947, top1=41.06%, top5=67.47%]
Epoch  20/100 | train_loss=3.2658 train_acc=35.57% | val_loss=3.0947 val_acc=41.06% val_top5=67.47% | lr=9.05e-04 peak_mem=142MB time=21.5s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.41it/s, acc=36.12%, loss=3.2428]
Validation: 100%|██████████| 157/157 [00:01<00:00, 143.35it/s, loss=3.1715, top1=39.11%, top5=65.57%]
Epoch  21/100 | train_loss=3.2428 train_acc=36.12% | val_loss=3.1715 val_acc=39.11% val_top5=65.57% | lr=8.95e-04 peak_mem=142MB time=21.1s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.38it/s, acc=36.77%, loss=3.2190]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.40it/s, loss=3.1196, top1=40.15%, top5=66.92%]
Epoch  22/100 | train_loss=3.2190 train_acc=36.77% | val_loss=3.1196 val_acc=40.15% val_top5=66.92% | lr=8.85e-04 peak_mem=142MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.24it/s, acc=37.40%, loss=3.1999]
Validation: 100%|██████████| 157/157 [00:00<00:00, 157.07it/s, loss=3.0957, top1=41.15%, top5=67.59%]
Epoch  23/100 | train_loss=3.1999 train_acc=37.40% | val_loss=3.0957 val_acc=41.15% val_top5=67.59% | lr=8.75e-04 peak_mem=142MB time=21.4s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.46it/s, acc=37.68%, loss=3.1863]
Validation: 100%|██████████| 157/157 [00:01<00:00, 128.25it/s, loss=3.0399, top1=42.39%, top5=68.72%]
Epoch  24/100 | train_loss=3.1863 train_acc=37.68% | val_loss=3.0399 val_acc=42.39% val_top5=68.72% | lr=8.64e-04 peak_mem=142MB time=21.8s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.15it/s, acc=38.11%, loss=3.1672]
Validation: 100%|██████████| 157/157 [00:01<00:00, 144.48it/s, loss=3.0246, top1=42.96%, top5=69.21%]
Epoch  25/100 | train_loss=3.1672 train_acc=38.11% | val_loss=3.0246 val_acc=42.96% val_top5=69.21% | lr=8.54e-04 peak_mem=142MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.68it/s, acc=38.66%, loss=3.1497]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.04it/s, loss=3.0400, top1=41.95%, top5=68.55%]
Epoch  26/100 | train_loss=3.1497 train_acc=38.66% | val_loss=3.0400 val_acc=41.95% val_top5=68.55% | lr=8.42e-04 peak_mem=142MB time=22.3s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.56it/s, acc=38.92%, loss=3.1361]
Validation: 100%|██████████| 157/157 [00:01<00:00, 155.69it/s, loss=3.0081, top1=43.17%, top5=69.61%]
Epoch  27/100 | train_loss=3.1361 train_acc=38.92% | val_loss=3.0081 val_acc=43.17% val_top5=69.61% | lr=8.31e-04 peak_mem=142MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.04it/s, acc=39.21%, loss=3.1177]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.42it/s, loss=3.0344, top1=42.00%, top5=68.41%]
Epoch  28/100 | train_loss=3.1177 train_acc=39.21% | val_loss=3.0344 val_acc=42.00% val_top5=68.41% | lr=8.19e-04 peak_mem=142MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.72it/s, acc=39.80%, loss=3.1084]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.17it/s, loss=3.0083, top1=43.36%, top5=69.31%]
Epoch  29/100 | train_loss=3.1084 train_acc=39.80% | val_loss=3.0083 val_acc=43.36% val_top5=69.31% | lr=8.06e-04 peak_mem=142MB time=22.3s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 63.23it/s, acc=39.99%, loss=3.0923]
Validation: 100%|██████████| 157/157 [00:01<00:00, 135.02it/s, loss=3.0230, top1=42.82%, top5=69.00%]
Epoch  30/100 | train_loss=3.0923 train_acc=39.99% | val_loss=3.0230 val_acc=42.82% val_top5=69.00% | lr=7.94e-04 peak_mem=142MB time=23.5s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.30it/s, acc=40.51%, loss=3.0763]
Validation: 100%|██████████| 157/157 [00:01<00:00, 128.23it/s, loss=2.9642, top1=44.13%, top5=70.37%]
Epoch  31/100 | train_loss=3.0763 train_acc=40.51% | val_loss=2.9642 val_acc=44.13% val_top5=70.37% | lr=7.81e-04 peak_mem=142MB time=22.5s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.63it/s, acc=40.85%, loss=3.0613]
Validation: 100%|██████████| 157/157 [00:01<00:00, 137.41it/s, loss=3.0179, top1=43.00%, top5=69.40%]
Epoch  32/100 | train_loss=3.0613 train_acc=40.85% | val_loss=3.0179 val_acc=43.00% val_top5=69.40% | lr=7.68e-04 peak_mem=142MB time=23.0s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.36it/s, acc=41.11%, loss=3.0477]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.80it/s, loss=2.9578, top1=44.16%, top5=70.60%]
Epoch  33/100 | train_loss=3.0477 train_acc=41.11% | val_loss=2.9578 val_acc=44.16% val_top5=70.60% | lr=7.55e-04 peak_mem=142MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.22it/s, acc=41.50%, loss=3.0341]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.07it/s, loss=2.9569, top1=44.15%, top5=70.78%]
Epoch  34/100 | train_loss=3.0341 train_acc=41.50% | val_loss=2.9569 val_acc=44.15% val_top5=70.78% | lr=7.41e-04 peak_mem=142MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.53it/s, acc=41.77%, loss=3.0227]
Validation: 100%|██████████| 157/157 [00:01<00:00, 135.15it/s, loss=2.9587, top1=44.32%, top5=70.45%]
Epoch  35/100 | train_loss=3.0227 train_acc=41.77% | val_loss=2.9587 val_acc=44.32% val_top5=70.45% | lr=7.27e-04 peak_mem=142MB time=22.1s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.13it/s, acc=41.97%, loss=3.0130]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.95it/s, loss=2.9813, top1=43.83%, top5=69.87%]
Epoch  36/100 | train_loss=3.0130 train_acc=41.97% | val_loss=2.9813 val_acc=43.83% val_top5=69.87% | lr=7.13e-04 peak_mem=142MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.68it/s, acc=42.26%, loss=2.9993]
Validation: 100%|██████████| 157/157 [00:01<00:00, 145.53it/s, loss=2.9546, top1=44.48%, top5=70.85%]
Epoch  37/100 | train_loss=2.9993 train_acc=42.26% | val_loss=2.9546 val_acc=44.48% val_top5=70.85% | lr=6.99e-04 peak_mem=142MB time=22.6s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 61.73it/s, acc=42.59%, loss=2.9841]
Validation: 100%|██████████| 157/157 [00:01<00:00, 126.27it/s, loss=2.9657, top1=44.67%, top5=70.38%]
Epoch  38/100 | train_loss=2.9841 train_acc=42.59% | val_loss=2.9657 val_acc=44.67% val_top5=70.38% | lr=6.84e-04 peak_mem=142MB time=24.1s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.87it/s, acc=42.96%, loss=2.9747]
Validation: 100%|██████████| 157/157 [00:01<00:00, 136.97it/s, loss=2.9319, top1=45.02%, top5=71.18%]
Epoch  39/100 | train_loss=2.9747 train_acc=42.96% | val_loss=2.9319 val_acc=45.02% val_top5=71.18% | lr=6.69e-04 peak_mem=142MB time=25.5s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.36it/s, acc=43.17%, loss=2.9693]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.19it/s, loss=2.9034, top1=45.96%, top5=71.86%]
Epoch  40/100 | train_loss=2.9693 train_acc=43.17% | val_loss=2.9034 val_acc=45.96% val_top5=71.86% | lr=6.55e-04 peak_mem=142MB time=23.1s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.11it/s, acc=43.63%, loss=2.9548]
Validation: 100%|██████████| 157/157 [00:01<00:00, 151.18it/s, loss=2.9130, top1=45.18%, top5=71.58%]
Epoch  41/100 | train_loss=2.9548 train_acc=43.63% | val_loss=2.9130 val_acc=45.18% val_top5=71.58% | lr=6.39e-04 peak_mem=142MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.11it/s, acc=43.61%, loss=2.9478]
Validation: 100%|██████████| 157/157 [00:01<00:00, 151.16it/s, loss=2.9355, top1=45.19%, top5=71.10%]
Epoch  42/100 | train_loss=2.9478 train_acc=43.61% | val_loss=2.9355 val_acc=45.19% val_top5=71.10% | lr=6.24e-04 peak_mem=142MB time=21.5s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.51it/s, acc=44.08%, loss=2.9328]
Validation: 100%|██████████| 157/157 [00:01<00:00, 145.76it/s, loss=2.9294, top1=45.33%, top5=71.07%]
Epoch  43/100 | train_loss=2.9328 train_acc=44.08% | val_loss=2.9294 val_acc=45.33% val_top5=71.07% | lr=6.09e-04 peak_mem=142MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.21it/s, acc=44.06%, loss=2.9274]
Validation: 100%|██████████| 157/157 [00:01<00:00, 136.59it/s, loss=2.8966, top1=45.98%, top5=71.83%]
Epoch  44/100 | train_loss=2.9274 train_acc=44.06% | val_loss=2.8966 val_acc=45.98% val_top5=71.83% | lr=5.94e-04 peak_mem=142MB time=22.5s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.28it/s, acc=44.49%, loss=2.9170]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.99it/s, loss=2.8830, top1=46.46%, top5=71.95%]
Epoch  45/100 | train_loss=2.9170 train_acc=44.49% | val_loss=2.8830 val_acc=46.46% val_top5=71.95% | lr=5.78e-04 peak_mem=142MB time=22.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.95it/s, acc=44.58%, loss=2.9077]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.63it/s, loss=2.8697, top1=46.80%, top5=72.20%]
Epoch  46/100 | train_loss=2.9077 train_acc=44.58% | val_loss=2.8697 val_acc=46.80% val_top5=72.20% | lr=5.63e-04 peak_mem=142MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 63.67it/s, acc=45.02%, loss=2.8960]
Validation: 100%|██████████| 157/157 [00:01<00:00, 143.31it/s, loss=2.8801, top1=46.46%, top5=72.42%]
Epoch  47/100 | train_loss=2.8960 train_acc=45.02% | val_loss=2.8801 val_acc=46.46% val_top5=72.42% | lr=5.47e-04 peak_mem=142MB time=23.2s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.82it/s, acc=45.39%, loss=2.8887]
Validation: 100%|██████████| 157/157 [00:01<00:00, 142.36it/s, loss=2.8600, top1=47.18%, top5=72.79%]
Epoch  48/100 | train_loss=2.8887 train_acc=45.39% | val_loss=2.8600 val_acc=47.18% val_top5=72.79% | lr=5.31e-04 peak_mem=142MB time=22.5s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.57it/s, acc=45.38%, loss=2.8877]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.59it/s, loss=2.8842, top1=46.11%, top5=72.01%]
Epoch  49/100 | train_loss=2.8877 train_acc=45.38% | val_loss=2.8842 val_acc=46.11% val_top5=72.01% | lr=5.16e-04 peak_mem=142MB time=22.0s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.27it/s, acc=45.54%, loss=2.8737]
Validation: 100%|██████████| 157/157 [00:01<00:00, 127.49it/s, loss=2.9006, top1=46.26%, top5=71.58%]
Epoch  50/100 | train_loss=2.8737 train_acc=45.54% | val_loss=2.9006 val_acc=46.26% val_top5=71.58% | lr=5.00e-04 peak_mem=142MB time=22.2s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.41it/s, acc=45.80%, loss=2.8643]
Validation: 100%|██████████| 157/157 [00:01<00:00, 135.78it/s, loss=2.8439, top1=47.57%, top5=73.03%]
Epoch  51/100 | train_loss=2.8643 train_acc=45.80% | val_loss=2.8439 val_acc=47.57% val_top5=73.03% | lr=4.84e-04 peak_mem=142MB time=22.7s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 63.11it/s, acc=46.25%, loss=2.8551]
Validation: 100%|██████████| 157/157 [00:01<00:00, 145.99it/s, loss=2.8530, top1=47.43%, top5=72.77%]
Epoch  52/100 | train_loss=2.8551 train_acc=46.25% | val_loss=2.8530 val_acc=47.43% val_top5=72.77% | lr=4.69e-04 peak_mem=142MB time=23.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.78it/s, acc=46.27%, loss=2.8474]
Validation: 100%|██████████| 157/157 [00:01<00:00, 120.32it/s, loss=2.8686, top1=46.99%, top5=72.57%]
Epoch  53/100 | train_loss=2.8474 train_acc=46.27% | val_loss=2.8686 val_acc=46.99% val_top5=72.57% | lr=4.53e-04 peak_mem=142MB time=23.1s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.99it/s, acc=46.66%, loss=2.8373]
Validation: 100%|██████████| 157/157 [00:01<00:00, 143.47it/s, loss=2.8531, top1=47.04%, top5=73.09%]
Epoch  54/100 | train_loss=2.8373 train_acc=46.66% | val_loss=2.8531 val_acc=47.04% val_top5=73.09% | lr=4.37e-04 peak_mem=142MB time=22.5s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.17it/s, acc=46.64%, loss=2.8321]
Validation: 100%|██████████| 157/157 [00:01<00:00, 148.82it/s, loss=2.8314, top1=47.86%, top5=73.16%]
Epoch  55/100 | train_loss=2.8321 train_acc=46.64% | val_loss=2.8314 val_acc=47.86% val_top5=73.16% | lr=4.22e-04 peak_mem=142MB time=23.0s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.86it/s, acc=46.75%, loss=2.8279]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.47it/s, loss=2.8436, top1=47.66%, top5=72.81%]
Epoch  56/100 | train_loss=2.8279 train_acc=46.75% | val_loss=2.8436 val_acc=47.66% val_top5=72.81% | lr=4.06e-04 peak_mem=142MB time=22.9s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 58.83it/s, acc=47.01%, loss=2.8238]
Validation: 100%|██████████| 157/157 [00:01<00:00, 119.48it/s, loss=2.8480, top1=47.74%, top5=73.12%]
Epoch  57/100 | train_loss=2.8238 train_acc=47.01% | val_loss=2.8480 val_acc=47.74% val_top5=73.12% | lr=3.91e-04 peak_mem=142MB time=25.3s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 63.52it/s, acc=47.46%, loss=2.8069]
Validation: 100%|██████████| 157/157 [00:01<00:00, 129.63it/s, loss=2.8417, top1=47.90%, top5=73.13%]
Epoch  58/100 | train_loss=2.8069 train_acc=47.46% | val_loss=2.8417 val_acc=47.90% val_top5=73.13% | lr=3.76e-04 peak_mem=142MB time=23.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.43it/s, acc=47.47%, loss=2.8027]
Validation: 100%|██████████| 157/157 [00:01<00:00, 147.72it/s, loss=2.8273, top1=48.28%, top5=73.53%]
Epoch  59/100 | train_loss=2.8027 train_acc=47.47% | val_loss=2.8273 val_acc=48.28% val_top5=73.53% | lr=3.61e-04 peak_mem=142MB time=22.3s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.01it/s, acc=47.51%, loss=2.7995]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.72it/s, loss=2.8461, top1=47.76%, top5=73.37%]
Epoch  60/100 | train_loss=2.7995 train_acc=47.51% | val_loss=2.8461 val_acc=47.76% val_top5=73.37% | lr=3.45e-04 peak_mem=142MB time=22.5s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.13it/s, acc=47.81%, loss=2.7897]

========================================================================
Training: alexnet_final_bottleneck_residual  lr=0.001  epochs=100
========================================================================

Training: 100%|██████████| 1406/1406 [00:26<00:00, 52.43it/s, acc=4.32%, loss=4.9270]
Validation: 100%|██████████| 157/157 [00:01<00:00, 122.44it/s, loss=4.5971, top1=8.43%, top5=24.35%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/100 | train_loss=4.9270 train_acc=4.32% | val_loss=4.5971 val_acc=8.43% val_top5=24.35% | lr=1.00e-03 peak_mem=187MB time=28.2s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 61.67it/s, acc=9.35%, loss=4.5258]
Validation: 100%|██████████| 157/157 [00:01<00:00, 126.63it/s, loss=4.2712, top1=13.30%, top5=33.89%]
Epoch   2/100 | train_loss=4.5258 train_acc=9.35% | val_loss=4.2712 val_acc=13.30% val_top5=33.89% | lr=9.99e-04 peak_mem=187MB time=24.1s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 63.51it/s, acc=13.12%, loss=4.2996]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.34it/s, loss=4.1172, top1=16.98%, top5=39.30%]
Epoch   3/100 | train_loss=4.2996 train_acc=13.12% | val_loss=4.1172 val_acc=16.98% val_top5=39.30% | lr=9.98e-04 peak_mem=187MB time=23.3s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.22it/s, acc=16.30%, loss=4.1309]
Validation: 100%|██████████| 157/157 [00:01<00:00, 124.43it/s, loss=3.8895, top1=20.86%, top5=45.88%]
Epoch   4/100 | train_loss=4.1309 train_acc=16.30% | val_loss=3.8895 val_acc=20.86% val_top5=45.88% | lr=9.96e-04 peak_mem=187MB time=22.6s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 63.45it/s, acc=18.67%, loss=4.0139]
Validation: 100%|██████████| 157/157 [00:01<00:00, 115.14it/s, loss=3.7985, top1=22.85%, top5=48.88%]
Epoch   5/100 | train_loss=4.0139 train_acc=18.67% | val_loss=3.7985 val_acc=22.85% val_top5=48.88% | lr=9.94e-04 peak_mem=187MB time=23.6s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 62.92it/s, acc=20.82%, loss=3.9101]
Validation: 100%|██████████| 157/157 [00:01<00:00, 143.77it/s, loss=3.7753, top1=24.05%, top5=49.34%]
Epoch   6/100 | train_loss=3.9101 train_acc=20.82% | val_loss=3.7753 val_acc=24.05% val_top5=49.34% | lr=9.91e-04 peak_mem=187MB time=23.5s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.83it/s, acc=22.54%, loss=3.8261]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.66it/s, loss=3.6840, top1=26.19%, top5=52.59%]
Epoch   7/100 | train_loss=3.8261 train_acc=22.54% | val_loss=3.6840 val_acc=26.19% val_top5=52.59% | lr=9.88e-04 peak_mem=187MB time=22.9s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 62.45it/s, acc=24.09%, loss=3.7556]
Validation: 100%|██████████| 157/157 [00:01<00:00, 126.00it/s, loss=3.5603, top1=29.37%, top5=55.80%]
Epoch   8/100 | train_loss=3.7556 train_acc=24.09% | val_loss=3.5603 val_acc=29.37% val_top5=55.80% | lr=9.84e-04 peak_mem=187MB time=23.8s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 56.30it/s, acc=25.79%, loss=3.6777]
Validation: 100%|██████████| 157/157 [00:01<00:00, 106.90it/s, loss=3.4261, top1=31.66%, top5=59.32%]
Epoch   9/100 | train_loss=3.6777 train_acc=25.79% | val_loss=3.4261 val_acc=31.66% val_top5=59.32% | lr=9.80e-04 peak_mem=187MB time=26.5s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 58.80it/s, acc=27.18%, loss=3.6203]
Validation: 100%|██████████| 157/157 [00:01<00:00, 117.45it/s, loss=3.3946, top1=32.72%, top5=59.81%]
Epoch  10/100 | train_loss=3.6203 train_acc=27.18% | val_loss=3.3946 val_acc=32.72% val_top5=59.81% | lr=9.76e-04 peak_mem=187MB time=25.3s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.49it/s, acc=28.55%, loss=3.5595]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.00it/s, loss=3.3366, top1=33.98%, top5=62.11%]
Epoch  11/100 | train_loss=3.5595 train_acc=28.55% | val_loss=3.3366 val_acc=33.98% val_top5=62.11% | lr=9.70e-04 peak_mem=187MB time=24.4s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.00it/s, acc=29.72%, loss=3.5171]
Validation: 100%|██████████| 157/157 [00:01<00:00, 135.06it/s, loss=3.3525, top1=34.13%, top5=61.29%]
Epoch  12/100 | train_loss=3.5171 train_acc=29.72% | val_loss=3.3525 val_acc=34.13% val_top5=61.29% | lr=9.65e-04 peak_mem=187MB time=24.7s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.82it/s, acc=30.59%, loss=3.4773]
Validation: 100%|██████████| 157/157 [00:01<00:00, 122.09it/s, loss=3.2731, top1=35.78%, top5=63.44%]
Epoch  13/100 | train_loss=3.4773 train_acc=30.59% | val_loss=3.2731 val_acc=35.78% val_top5=63.44% | lr=9.59e-04 peak_mem=187MB time=24.9s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.18it/s, acc=31.37%, loss=3.4338]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.87it/s, loss=3.2567, top1=36.64%, top5=63.61%]
Epoch  14/100 | train_loss=3.4338 train_acc=31.37% | val_loss=3.2567 val_acc=36.64% val_top5=63.61% | lr=9.52e-04 peak_mem=187MB time=25.8s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 63.05it/s, acc=32.46%, loss=3.3962]
Validation: 100%|██████████| 157/157 [00:01<00:00, 124.70it/s, loss=3.2878, top1=35.66%, top5=62.70%]
Epoch  15/100 | train_loss=3.3962 train_acc=32.46% | val_loss=3.2878 val_acc=35.66% val_top5=62.70% | lr=9.46e-04 peak_mem=187MB time=23.6s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.97it/s, acc=33.28%, loss=3.3605]
Validation: 100%|██████████| 157/157 [00:01<00:00, 126.54it/s, loss=3.1758, top1=38.35%, top5=65.38%]
Epoch  16/100 | train_loss=3.3605 train_acc=33.28% | val_loss=3.1758 val_acc=38.35% val_top5=65.38% | lr=9.38e-04 peak_mem=187MB time=25.6s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 58.12it/s, acc=34.20%, loss=3.3286]
Validation: 100%|██████████| 157/157 [00:01<00:00, 108.68it/s, loss=3.2101, top1=37.40%, top5=64.32%]
Epoch  17/100 | train_loss=3.3286 train_acc=34.20% | val_loss=3.2101 val_acc=37.40% val_top5=64.32% | lr=9.30e-04 peak_mem=187MB time=25.7s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 57.76it/s, acc=34.62%, loss=3.3021]
Validation: 100%|██████████| 157/157 [00:01<00:00, 113.34it/s, loss=3.1169, top1=39.37%, top5=67.06%]
Epoch  18/100 | train_loss=3.3021 train_acc=34.62% | val_loss=3.1169 val_acc=39.37% val_top5=67.06% | lr=9.22e-04 peak_mem=187MB time=25.8s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 56.85it/s, acc=35.33%, loss=3.2744]
Validation: 100%|██████████| 157/157 [00:01<00:00, 137.14it/s, loss=3.1123, top1=40.22%, top5=67.07%]
Epoch  19/100 | train_loss=3.2744 train_acc=35.33% | val_loss=3.1123 val_acc=40.22% val_top5=67.07% | lr=9.14e-04 peak_mem=187MB time=25.9s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 61.02it/s, acc=35.97%, loss=3.2466]
Validation: 100%|██████████| 157/157 [00:01<00:00, 129.31it/s, loss=3.0964, top1=40.22%, top5=67.33%]
Epoch  20/100 | train_loss=3.2466 train_acc=35.97% | val_loss=3.0964 val_acc=40.22% val_top5=67.33% | lr=9.05e-04 peak_mem=187MB time=24.3s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 61.76it/s, acc=36.55%, loss=3.2253]
Validation: 100%|██████████| 157/157 [00:01<00:00, 110.54it/s, loss=3.0969, top1=40.58%, top5=67.70%]
Epoch  21/100 | train_loss=3.2253 train_acc=36.55% | val_loss=3.0969 val_acc=40.58% val_top5=67.70% | lr=8.95e-04 peak_mem=187MB time=24.3s
Training: 100%|██████████| 1406/1406 [00:25<00:00, 54.81it/s, acc=37.23%, loss=3.1996]
Validation: 100%|██████████| 157/157 [00:01<00:00, 120.74it/s, loss=3.0381, top1=42.17%, top5=68.79%]
Epoch  22/100 | train_loss=3.1996 train_acc=37.23% | val_loss=3.0381 val_acc=42.17% val_top5=68.79% | lr=8.85e-04 peak_mem=187MB time=27.0s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 58.28it/s, acc=37.63%, loss=3.1828]
Validation: 100%|██████████| 157/157 [00:01<00:00, 128.52it/s, loss=3.0625, top1=41.15%, top5=67.99%]
Epoch  23/100 | train_loss=3.1828 train_acc=37.63% | val_loss=3.0625 val_acc=41.15% val_top5=67.99% | lr=8.75e-04 peak_mem=187MB time=25.4s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.04it/s, acc=38.03%, loss=3.1610]
Validation: 100%|██████████| 157/157 [00:01<00:00, 116.12it/s, loss=3.0259, top1=42.33%, top5=68.80%]
Epoch  24/100 | train_loss=3.1610 train_acc=38.03% | val_loss=3.0259 val_acc=42.33% val_top5=68.80% | lr=8.64e-04 peak_mem=187MB time=25.2s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 61.25it/s, acc=38.60%, loss=3.1416]
Validation: 100%|██████████| 157/157 [00:01<00:00, 144.06it/s, loss=3.0308, top1=42.38%, top5=68.83%]
Epoch  25/100 | train_loss=3.1416 train_acc=38.60% | val_loss=3.0308 val_acc=42.38% val_top5=68.83% | lr=8.54e-04 peak_mem=187MB time=24.1s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.39it/s, acc=39.18%, loss=3.1189]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.44it/s, loss=3.0159, top1=42.49%, top5=69.30%]
Epoch  26/100 | train_loss=3.1189 train_acc=39.18% | val_loss=3.0159 val_acc=42.49% val_top5=69.30% | lr=8.42e-04 peak_mem=187MB time=23.1s
Training: 100%|██████████| 1406/1406 [00:26<00:00, 53.76it/s, acc=39.61%, loss=3.1043]
Validation: 100%|██████████| 157/157 [00:01<00:00, 105.96it/s, loss=3.0062, top1=43.20%, top5=69.14%]
Epoch  27/100 | train_loss=3.1043 train_acc=39.61% | val_loss=3.0062 val_acc=43.20% val_top5=69.14% | lr=8.31e-04 peak_mem=187MB time=27.7s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.91it/s, acc=40.04%, loss=3.0883]
Validation: 100%|██████████| 157/157 [00:01<00:00, 113.26it/s, loss=2.9691, top1=43.97%, top5=70.38%]
Epoch  28/100 | train_loss=3.0883 train_acc=40.04% | val_loss=2.9691 val_acc=43.97% val_top5=70.38% | lr=8.19e-04 peak_mem=187MB time=24.5s
Training: 100%|██████████| 1406/1406 [00:24<00:00, 58.20it/s, acc=40.42%, loss=3.0668]
Validation: 100%|██████████| 157/157 [00:01<00:00, 132.72it/s, loss=2.9813, top1=43.29%, top5=69.71%]
Epoch  29/100 | train_loss=3.0668 train_acc=40.42% | val_loss=2.9813 val_acc=43.29% val_top5=69.71% | lr=8.06e-04 peak_mem=187MB time=25.4s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 61.46it/s, acc=40.87%, loss=3.0551]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.00it/s, loss=2.9657, top1=43.81%, top5=69.86%]
Epoch  30/100 | train_loss=3.0551 train_acc=40.87% | val_loss=2.9657 val_acc=43.81% val_top5=69.86% | lr=7.94e-04 peak_mem=187MB time=24.1s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.35it/s, acc=41.21%, loss=3.0382]
Validation: 100%|██████████| 157/157 [00:01<00:00, 132.77it/s, loss=2.9994, top1=43.17%, top5=69.24%]
Epoch  31/100 | train_loss=3.0382 train_acc=41.21% | val_loss=2.9994 val_acc=43.17% val_top5=69.24% | lr=7.81e-04 peak_mem=187MB time=22.8s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.11it/s, acc=41.51%, loss=3.0247]
Validation: 100%|██████████| 157/157 [00:01<00:00, 137.28it/s, loss=2.9452, top1=44.17%, top5=70.91%]
Epoch  32/100 | train_loss=3.0247 train_acc=41.51% | val_loss=2.9452 val_acc=44.17% val_top5=70.91% | lr=7.68e-04 peak_mem=187MB time=23.1s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 62.27it/s, acc=42.10%, loss=3.0073]
Validation: 100%|██████████| 157/157 [00:01<00:00, 123.15it/s, loss=2.9309, top1=45.12%, top5=71.09%]
Epoch  33/100 | train_loss=3.0073 train_acc=42.10% | val_loss=2.9309 val_acc=45.12% val_top5=71.09% | lr=7.55e-04 peak_mem=187MB time=23.9s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.57it/s, acc=42.39%, loss=2.9968]
Validation: 100%|██████████| 157/157 [00:01<00:00, 129.54it/s, loss=2.9880, top1=43.42%, top5=69.31%]
Epoch  34/100 | train_loss=2.9968 train_acc=42.39% | val_loss=2.9880 val_acc=43.42% val_top5=69.31% | lr=7.41e-04 peak_mem=187MB time=22.7s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.45it/s, acc=42.74%, loss=2.9827]
Validation: 100%|██████████| 157/157 [00:01<00:00, 122.72it/s, loss=2.9488, top1=44.26%, top5=70.48%]
Epoch  35/100 | train_loss=2.9827 train_acc=42.74% | val_loss=2.9488 val_acc=44.26% val_top5=70.48% | lr=7.27e-04 peak_mem=187MB time=25.0s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 62.34it/s, acc=42.84%, loss=2.9720]
Validation: 100%|██████████| 157/157 [00:01<00:00, 132.76it/s, loss=2.9569, top1=44.43%, top5=70.69%]
Epoch  36/100 | train_loss=2.9720 train_acc=42.84% | val_loss=2.9569 val_acc=44.43% val_top5=70.69% | lr=7.13e-04 peak_mem=187MB time=23.8s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 62.09it/s, acc=43.27%, loss=2.9508]
Validation: 100%|██████████| 157/157 [00:01<00:00, 148.51it/s, loss=2.9519, top1=44.37%, top5=70.81%]
Epoch  37/100 | train_loss=2.9508 train_acc=43.27% | val_loss=2.9519 val_acc=44.37% val_top5=70.81% | lr=6.99e-04 peak_mem=187MB time=23.8s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.01it/s, acc=43.70%, loss=2.9376]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.98it/s, loss=2.9287, top1=45.05%, top5=70.96%]
Epoch  38/100 | train_loss=2.9376 train_acc=43.70% | val_loss=2.9287 val_acc=45.05% val_top5=70.96% | lr=6.84e-04 peak_mem=187MB time=22.5s
Early stopping at epoch 38

================= Run Summary =================
Model          : alexnet_final_bottleneck_residual
Epochs         : 38
Best Val Top-1 : 45.12%
Best Val Top-5 : 71.09%
Final Val Top-1: 45.05%
Final Val Top-5: 70.96%
Best Val Loss  : 2.9309
Total Time     : 00:15:34
===============================================

========================================================================
Training: alexnet_final_depthwise_fire  lr=0.001  epochs=100
========================================================================

Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.50it/s, acc=2.99%, loss=5.0146]
Validation: 100%|██████████| 157/157 [00:01<00:00, 154.87it/s, loss=4.7133, top1=5.87%, top5=19.74%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/100 | train_loss=5.0146 train_acc=2.99% | val_loss=4.7133 val_acc=5.87% val_top5=19.74% | lr=1.00e-03 peak_mem=106MB time=21.3s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.14it/s, acc=6.46%, loss=4.7165]
Validation: 100%|██████████| 157/157 [00:01<00:00, 147.10it/s, loss=4.4891, top1=9.53%, top5=27.38%]
Epoch   2/100 | train_loss=4.7165 train_acc=6.46% | val_loss=4.4891 val_acc=9.53% val_top5=27.38% | lr=9.99e-04 peak_mem=106MB time=21.5s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.14it/s, acc=9.41%, loss=4.5181]
Validation: 100%|██████████| 157/157 [00:01<00:00, 140.63it/s, loss=4.2617, top1=13.92%, top5=34.95%]
Epoch   3/100 | train_loss=4.5181 train_acc=9.41% | val_loss=4.2617 val_acc=13.92% val_top5=34.95% | lr=9.98e-04 peak_mem=106MB time=21.5s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.79it/s, acc=11.91%, loss=4.3775]
Validation: 100%|██████████| 157/157 [00:00<00:00, 158.48it/s, loss=4.0669, top1=17.09%, top5=41.10%]
Epoch   4/100 | train_loss=4.3775 train_acc=11.91% | val_loss=4.0669 val_acc=17.09% val_top5=41.10% | lr=9.96e-04 peak_mem=106MB time=21.2s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.56it/s, acc=13.90%, loss=4.2699]
Validation: 100%|██████████| 157/157 [00:01<00:00, 150.08it/s, loss=3.9989, top1=18.44%, top5=43.02%]
Epoch   5/100 | train_loss=4.2699 train_acc=13.90% | val_loss=3.9989 val_acc=18.44% val_top5=43.02% | lr=9.94e-04 peak_mem=106MB time=21.3s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.22it/s, acc=15.72%, loss=4.1785]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.00it/s, loss=3.8477, top1=21.96%, top5=47.20%]
Epoch   6/100 | train_loss=4.1785 train_acc=15.72% | val_loss=3.8477 val_acc=21.96% val_top5=47.20% | lr=9.91e-04 peak_mem=106MB time=21.5s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.21it/s, acc=17.13%, loss=4.1064]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.71it/s, loss=3.8040, top1=23.16%, top5=48.87%]
Epoch   7/100 | train_loss=4.1064 train_acc=17.13% | val_loss=3.8040 val_acc=23.16% val_top5=48.87% | lr=9.88e-04 peak_mem=106MB time=21.5s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.83it/s, acc=18.39%, loss=4.0428]
Validation: 100%|██████████| 157/157 [00:01<00:00, 137.73it/s, loss=3.7394, top1=24.63%, top5=50.92%]
Epoch   8/100 | train_loss=4.0428 train_acc=18.39% | val_loss=3.7394 val_acc=24.63% val_top5=50.92% | lr=9.84e-04 peak_mem=106MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.17it/s, acc=19.59%, loss=3.9889]
Validation: 100%|██████████| 157/157 [00:01<00:00, 152.38it/s, loss=3.6733, top1=26.33%, top5=52.86%]
Epoch   9/100 | train_loss=3.9889 train_acc=19.59% | val_loss=3.6733 val_acc=26.33% val_top5=52.86% | lr=9.80e-04 peak_mem=106MB time=21.4s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.58it/s, acc=20.65%, loss=3.9366]
Validation: 100%|██████████| 157/157 [00:01<00:00, 156.37it/s, loss=3.6553, top1=26.85%, top5=53.42%]
Epoch  10/100 | train_loss=3.9366 train_acc=20.65% | val_loss=3.6553 val_acc=26.85% val_top5=53.42% | lr=9.76e-04 peak_mem=106MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.79it/s, acc=21.49%, loss=3.8936]
Validation: 100%|██████████| 157/157 [00:01<00:00, 142.37it/s, loss=3.6051, top1=28.11%, top5=54.78%]
Epoch  11/100 | train_loss=3.8936 train_acc=21.49% | val_loss=3.6051 val_acc=28.11% val_top5=54.78% | lr=9.70e-04 peak_mem=106MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.54it/s, acc=22.39%, loss=3.8547]
Validation: 100%|██████████| 157/157 [00:01<00:00, 143.11it/s, loss=3.5670, top1=29.34%, top5=55.86%]
Epoch  12/100 | train_loss=3.8547 train_acc=22.39% | val_loss=3.5670 val_acc=29.34% val_top5=55.86% | lr=9.65e-04 peak_mem=106MB time=21.4s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.27it/s, acc=23.02%, loss=3.8186]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.39it/s, loss=3.5472, top1=29.21%, top5=56.66%]
Epoch  13/100 | train_loss=3.8186 train_acc=23.02% | val_loss=3.5472 val_acc=29.21% val_top5=56.66% | lr=9.59e-04 peak_mem=106MB time=22.4s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.66it/s, acc=23.81%, loss=3.7842]
Validation: 100%|██████████| 157/157 [00:01<00:00, 126.89it/s, loss=3.4808, top1=31.14%, top5=57.98%]
Epoch  14/100 | train_loss=3.7842 train_acc=23.81% | val_loss=3.4808 val_acc=31.14% val_top5=57.98% | lr=9.52e-04 peak_mem=106MB time=22.1s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 66.77it/s, acc=24.37%, loss=3.7591]
Validation: 100%|██████████| 157/157 [00:01<00:00, 151.86it/s, loss=3.4624, top1=31.57%, top5=58.33%]
Epoch  15/100 | train_loss=3.7591 train_acc=24.37% | val_loss=3.4624 val_acc=31.57% val_top5=58.33% | lr=9.46e-04 peak_mem=106MB time=22.2s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.37it/s, acc=25.14%, loss=3.7282]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.99it/s, loss=3.4266, top1=32.33%, top5=59.56%]
Epoch  16/100 | train_loss=3.7282 train_acc=25.14% | val_loss=3.4266 val_acc=32.33% val_top5=59.56% | lr=9.38e-04 peak_mem=106MB time=21.5s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 62.07it/s, acc=25.56%, loss=3.7057]
Validation: 100%|██████████| 157/157 [00:01<00:00, 130.24it/s, loss=3.4195, top1=32.72%, top5=59.94%]
Epoch  17/100 | train_loss=3.7057 train_acc=25.56% | val_loss=3.4195 val_acc=32.72% val_top5=59.94% | lr=9.30e-04 peak_mem=106MB time=23.9s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.11it/s, acc=26.11%, loss=3.6792]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.86it/s, loss=3.3773, top1=33.46%, top5=60.85%]
Epoch  18/100 | train_loss=3.6792 train_acc=26.11% | val_loss=3.3773 val_acc=33.46% val_top5=60.85% | lr=9.22e-04 peak_mem=106MB time=23.1s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.84it/s, acc=26.68%, loss=3.6582]
Validation: 100%|██████████| 157/157 [00:01<00:00, 132.53it/s, loss=3.3722, top1=33.94%, top5=60.85%]
Epoch  19/100 | train_loss=3.6582 train_acc=26.68% | val_loss=3.3722 val_acc=33.94% val_top5=60.85% | lr=9.14e-04 peak_mem=106MB time=22.9s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.20it/s, acc=27.10%, loss=3.6334]
Validation: 100%|██████████| 157/157 [00:01<00:00, 142.27it/s, loss=3.3637, top1=33.95%, top5=60.74%]
Epoch  20/100 | train_loss=3.6334 train_acc=27.10% | val_loss=3.3637 val_acc=33.95% val_top5=60.74% | lr=9.05e-04 peak_mem=106MB time=22.7s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.15it/s, acc=27.76%, loss=3.6142]
Validation: 100%|██████████| 157/157 [00:01<00:00, 135.72it/s, loss=3.3556, top1=34.40%, top5=61.03%]
Epoch  21/100 | train_loss=3.6142 train_acc=27.76% | val_loss=3.3556 val_acc=34.40% val_top5=61.03% | lr=8.95e-04 peak_mem=106MB time=23.1s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 64.85it/s, acc=28.22%, loss=3.5927]
Validation: 100%|██████████| 157/157 [00:01<00:00, 129.52it/s, loss=3.3256, top1=35.12%, top5=62.18%]
Epoch  22/100 | train_loss=3.5927 train_acc=28.22% | val_loss=3.3256 val_acc=35.12% val_top5=62.18% | lr=8.85e-04 peak_mem=106MB time=23.0s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 59.95it/s, acc=28.43%, loss=3.5777]
Validation: 100%|██████████| 157/157 [00:01<00:00, 122.74it/s, loss=3.3501, top1=34.17%, top5=61.45%]
Epoch  23/100 | train_loss=3.5777 train_acc=28.43% | val_loss=3.3501 val_acc=34.17% val_top5=61.45% | lr=8.75e-04 peak_mem=106MB time=24.8s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 66.97it/s, acc=28.96%, loss=3.5611]
Validation: 100%|██████████| 157/157 [00:01<00:00, 133.65it/s, loss=3.3064, top1=35.11%, top5=62.13%]
Epoch  24/100 | train_loss=3.5611 train_acc=28.96% | val_loss=3.3064 val_acc=35.11% val_top5=62.13% | lr=8.64e-04 peak_mem=106MB time=22.2s
Training: 100%|██████████| 1406/1406 [00:21<00:00, 65.51it/s, acc=29.29%, loss=3.5461]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.90it/s, loss=3.2805, top1=36.29%, top5=63.17%]
Epoch  25/100 | train_loss=3.5461 train_acc=29.29% | val_loss=3.2805 val_acc=36.29% val_top5=63.17% | lr=8.54e-04 peak_mem=106MB time=22.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 70.26it/s, acc=29.97%, loss=3.5273]
Validation: 100%|██████████| 157/157 [00:01<00:00, 141.42it/s, loss=3.3001, top1=36.26%, top5=62.77%]
Epoch  26/100 | train_loss=3.5273 train_acc=29.97% | val_loss=3.3001 val_acc=36.26% val_top5=62.77% | lr=8.42e-04 peak_mem=106MB time=21.2s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.13it/s, acc=30.18%, loss=3.5068]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.94it/s, loss=3.2636, top1=36.86%, top5=63.15%]
Epoch  27/100 | train_loss=3.5068 train_acc=30.18% | val_loss=3.2636 val_acc=36.86% val_top5=63.15% | lr=8.31e-04 peak_mem=106MB time=21.8s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.42it/s, acc=30.39%, loss=3.5008]
Validation: 100%|██████████| 157/157 [00:01<00:00, 129.39it/s, loss=3.2558, top1=36.57%, top5=63.49%]
Epoch  28/100 | train_loss=3.5008 train_acc=30.39% | val_loss=3.2558 val_acc=36.57% val_top5=63.49% | lr=8.19e-04 peak_mem=106MB time=22.1s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.52it/s, acc=30.82%, loss=3.4870]
Validation: 100%|██████████| 157/157 [00:01<00:00, 151.70it/s, loss=3.2574, top1=36.94%, top5=64.03%]
Epoch  29/100 | train_loss=3.4870 train_acc=30.82% | val_loss=3.2574 val_acc=36.94% val_top5=64.03% | lr=8.06e-04 peak_mem=106MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.92it/s, acc=31.04%, loss=3.4724]
Validation: 100%|██████████| 157/157 [00:01<00:00, 136.38it/s, loss=3.2444, top1=36.88%, top5=64.05%]
Epoch  30/100 | train_loss=3.4724 train_acc=31.04% | val_loss=3.2444 val_acc=36.88% val_top5=64.05% | lr=7.94e-04 peak_mem=106MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.56it/s, acc=31.26%, loss=3.4602]
Validation: 100%|██████████| 157/157 [00:01<00:00, 148.99it/s, loss=3.2229, top1=37.69%, top5=64.71%]
Epoch  31/100 | train_loss=3.4602 train_acc=31.26% | val_loss=3.2229 val_acc=37.69% val_top5=64.71% | lr=7.81e-04 peak_mem=106MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.94it/s, acc=31.42%, loss=3.4532]
Validation: 100%|██████████| 157/157 [00:01<00:00, 145.07it/s, loss=3.2236, top1=37.80%, top5=64.34%]
Epoch  32/100 | train_loss=3.4532 train_acc=31.42% | val_loss=3.2236 val_acc=37.80% val_top5=64.34% | lr=7.68e-04 peak_mem=106MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.78it/s, acc=31.69%, loss=3.4405]
Validation: 100%|██████████| 157/157 [00:01<00:00, 150.49it/s, loss=3.1936, top1=38.38%, top5=65.26%]
Epoch  33/100 | train_loss=3.4405 train_acc=31.69% | val_loss=3.1936 val_acc=38.38% val_top5=65.26% | lr=7.55e-04 peak_mem=106MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.20it/s, acc=32.06%, loss=3.4271]
Validation: 100%|██████████| 157/157 [00:01<00:00, 128.88it/s, loss=3.1927, top1=38.45%, top5=65.45%]
Epoch  34/100 | train_loss=3.4271 train_acc=32.06% | val_loss=3.1927 val_acc=38.45% val_top5=65.45% | lr=7.41e-04 peak_mem=106MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.55it/s, acc=32.37%, loss=3.4185]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.31it/s, loss=3.1789, top1=39.11%, top5=65.62%]
Epoch  35/100 | train_loss=3.4185 train_acc=32.37% | val_loss=3.1789 val_acc=39.11% val_top5=65.62% | lr=7.27e-04 peak_mem=106MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.90it/s, acc=32.78%, loss=3.4048]
Validation: 100%|██████████| 157/157 [00:01<00:00, 132.24it/s, loss=3.2053, top1=38.15%, top5=64.77%]
Epoch  36/100 | train_loss=3.4048 train_acc=32.78% | val_loss=3.2053 val_acc=38.15% val_top5=64.77% | lr=7.13e-04 peak_mem=106MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 67.06it/s, acc=33.09%, loss=3.3877]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.48it/s, loss=3.1777, top1=38.57%, top5=65.35%]
Epoch  37/100 | train_loss=3.3877 train_acc=33.09% | val_loss=3.1777 val_acc=38.57% val_top5=65.35% | lr=6.99e-04 peak_mem=106MB time=22.2s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.13it/s, acc=33.15%, loss=3.3816]
Validation: 100%|██████████| 157/157 [00:01<00:00, 142.76it/s, loss=3.1654, top1=38.83%, top5=65.88%]
Epoch  38/100 | train_loss=3.3816 train_acc=33.15% | val_loss=3.1654 val_acc=38.83% val_top5=65.88% | lr=6.84e-04 peak_mem=106MB time=21.8s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.95it/s, acc=33.41%, loss=3.3731]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.34it/s, loss=3.1636, top1=39.37%, top5=65.47%]
Epoch  39/100 | train_loss=3.3731 train_acc=33.41% | val_loss=3.1636 val_acc=39.37% val_top5=65.47% | lr=6.69e-04 peak_mem=106MB time=21.2s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.41it/s, acc=33.58%, loss=3.3633]
Validation: 100%|██████████| 157/157 [00:01<00:00, 145.90it/s, loss=3.1545, top1=39.00%, top5=65.82%]
Epoch  40/100 | train_loss=3.3633 train_acc=33.58% | val_loss=3.1545 val_acc=39.00% val_top5=65.82% | lr=6.55e-04 peak_mem=106MB time=21.1s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 70.10it/s, acc=33.52%, loss=3.3592]
Validation: 100%|██████████| 157/157 [00:01<00:00, 154.80it/s, loss=3.1335, top1=40.13%, top5=66.61%]
Epoch  41/100 | train_loss=3.3592 train_acc=33.52% | val_loss=3.1335 val_acc=40.13% val_top5=66.61% | lr=6.39e-04 peak_mem=106MB time=21.1s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.85it/s, acc=33.84%, loss=3.3473]
Validation: 100%|██████████| 157/157 [00:01<00:00, 143.16it/s, loss=3.1405, top1=39.58%, top5=66.41%]
Epoch  42/100 | train_loss=3.3473 train_acc=33.84% | val_loss=3.1405 val_acc=39.58% val_top5=66.41% | lr=6.24e-04 peak_mem=106MB time=21.3s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.73it/s, acc=34.22%, loss=3.3370]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.29it/s, loss=3.1215, top1=40.23%, top5=66.66%]
Epoch  43/100 | train_loss=3.3370 train_acc=34.22% | val_loss=3.1215 val_acc=40.23% val_top5=66.66% | lr=6.09e-04 peak_mem=106MB time=21.3s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.31it/s, acc=34.41%, loss=3.3307]
Validation: 100%|██████████| 157/157 [00:01<00:00, 150.34it/s, loss=3.1576, top1=39.27%, top5=65.68%]
Epoch  44/100 | train_loss=3.3307 train_acc=34.41% | val_loss=3.1576 val_acc=39.27% val_top5=65.68% | lr=5.94e-04 peak_mem=106MB time=21.1s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.97it/s, acc=34.63%, loss=3.3199]
Validation: 100%|██████████| 157/157 [00:01<00:00, 151.39it/s, loss=3.1165, top1=40.40%, top5=67.13%]
Epoch  45/100 | train_loss=3.3199 train_acc=34.63% | val_loss=3.1165 val_acc=40.40% val_top5=67.13% | lr=5.78e-04 peak_mem=106MB time=20.9s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.45it/s, acc=34.76%, loss=3.3156]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.76it/s, loss=3.1235, top1=40.27%, top5=66.28%]
Epoch  46/100 | train_loss=3.3156 train_acc=34.76% | val_loss=3.1235 val_acc=40.27% val_top5=66.28% | lr=5.63e-04 peak_mem=106MB time=21.1s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.88it/s, acc=35.08%, loss=3.3045]
Validation: 100%|██████████| 157/157 [00:01<00:00, 150.57it/s, loss=3.1020, top1=40.51%, top5=66.93%]
Epoch  47/100 | train_loss=3.3045 train_acc=35.08% | val_loss=3.1020 val_acc=40.51% val_top5=66.93% | lr=5.47e-04 peak_mem=106MB time=20.7s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.98it/s, acc=35.17%, loss=3.2967]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.28it/s, loss=3.0959, top1=40.99%, top5=67.37%]
Epoch  48/100 | train_loss=3.2967 train_acc=35.17% | val_loss=3.0959 val_acc=40.99% val_top5=67.37% | lr=5.31e-04 peak_mem=106MB time=21.0s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.58it/s, acc=35.44%, loss=3.2912]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.53it/s, loss=3.0911, top1=40.71%, top5=67.54%]
Epoch  49/100 | train_loss=3.2912 train_acc=35.44% | val_loss=3.0911 val_acc=40.71% val_top5=67.54% | lr=5.16e-04 peak_mem=106MB time=21.1s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.55it/s, acc=35.40%, loss=3.2865]
Validation: 100%|██████████| 157/157 [00:01<00:00, 148.81it/s, loss=3.0740, top1=41.38%, top5=67.82%]
Epoch  50/100 | train_loss=3.2865 train_acc=35.40% | val_loss=3.0740 val_acc=41.38% val_top5=67.82% | lr=5.00e-04 peak_mem=106MB time=21.1s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.48it/s, acc=35.78%, loss=3.2733]
Validation: 100%|██████████| 157/157 [00:01<00:00, 150.10it/s, loss=3.0759, top1=41.29%, top5=67.71%]
Epoch  51/100 | train_loss=3.2733 train_acc=35.78% | val_loss=3.0759 val_acc=41.29% val_top5=67.71% | lr=4.84e-04 peak_mem=106MB time=20.8s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.61it/s, acc=35.81%, loss=3.2664]
Validation: 100%|██████████| 157/157 [00:01<00:00, 139.14it/s, loss=3.0788, top1=41.41%, top5=67.46%]
Epoch  52/100 | train_loss=3.2664 train_acc=35.81% | val_loss=3.0788 val_acc=41.41% val_top5=67.46% | lr=4.69e-04 peak_mem=106MB time=21.1s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 70.86it/s, acc=36.06%, loss=3.2600]
Validation: 100%|██████████| 157/157 [00:01<00:00, 146.78it/s, loss=3.0756, top1=41.52%, top5=67.95%]
Epoch  53/100 | train_loss=3.2600 train_acc=36.06% | val_loss=3.0756 val_acc=41.52% val_top5=67.95% | lr=4.53e-04 peak_mem=106MB time=21.0s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 72.29it/s, acc=36.18%, loss=3.2498]
Validation: 100%|██████████| 157/157 [00:01<00:00, 149.51it/s, loss=3.0756, top1=41.26%, top5=67.55%]
Epoch  54/100 | train_loss=3.2498 train_acc=36.18% | val_loss=3.0756 val_acc=41.26% val_top5=67.55% | lr=4.37e-04 peak_mem=106MB time=20.6s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.40it/s, acc=36.60%, loss=3.2460]
Validation: 100%|██████████| 157/157 [00:01<00:00, 143.22it/s, loss=3.0737, top1=41.49%, top5=67.86%]
Epoch  55/100 | train_loss=3.2460 train_acc=36.60% | val_loss=3.0737 val_acc=41.49% val_top5=67.86% | lr=4.22e-04 peak_mem=106MB time=20.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.79it/s, acc=36.68%, loss=3.2435]
Validation: 100%|██████████| 157/157 [00:01<00:00, 144.64it/s, loss=3.0641, top1=41.63%, top5=68.07%]
Epoch  56/100 | train_loss=3.2435 train_acc=36.68% | val_loss=3.0641 val_acc=41.63% val_top5=68.07% | lr=4.06e-04 peak_mem=106MB time=21.3s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.25it/s, acc=36.47%, loss=3.2391]
Validation: 100%|██████████| 157/157 [00:01<00:00, 138.90it/s, loss=3.0478, top1=42.23%, top5=68.39%]
Epoch  57/100 | train_loss=3.2391 train_acc=36.47% | val_loss=3.0478 val_acc=42.23% val_top5=68.39% | lr=3.91e-04 peak_mem=106MB time=20.9s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.25it/s, acc=37.05%, loss=3.2274]
Validation: 100%|██████████| 157/157 [00:01<00:00, 141.19it/s, loss=3.0491, top1=42.33%, top5=68.66%]
Epoch  58/100 | train_loss=3.2274 train_acc=37.05% | val_loss=3.0491 val_acc=42.33% val_top5=68.66% | lr=3.76e-04 peak_mem=106MB time=20.9s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.00it/s, acc=36.97%, loss=3.2240]
Validation: 100%|██████████| 157/157 [00:01<00:00, 154.07it/s, loss=3.0558, top1=41.96%, top5=67.93%]
Epoch  59/100 | train_loss=3.2240 train_acc=36.97% | val_loss=3.0558 val_acc=41.96% val_top5=67.93% | lr=3.61e-04 peak_mem=106MB time=20.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 70.16it/s, acc=37.27%, loss=3.2164]
Validation: 100%|██████████| 157/157 [00:01<00:00, 155.87it/s, loss=3.0418, top1=42.83%, top5=68.44%]
Epoch  60/100 | train_loss=3.2164 train_acc=37.27% | val_loss=3.0418 val_acc=42.83% val_top5=68.44% | lr=3.45e-04 peak_mem=106MB time=21.1s
Training: 100%|██████████| 1406/1406 [00:19<00:00, 71.15it/s, acc=37.43%, loss=3.2087]

FP32 training complete.

## 6. Quantization-Aware Training (QAT)

All four Phase 4 models are QAT-compatible (no Sigmoid, `FloatFunctional` adds).
QAT trains on GPU; `convert` and INT8 inference run on CPU (fbgemm).

In [7]:
qat_train_cfg = replace(
    fp32_cfg,
    epochs=qat_cfg.epochs,
    lr=qat_cfg.lr,
    weight_decay=qat_cfg.weight_decay,
    use_amp=False,  # AMP incompatible with fake-quant observers
)

qat_models = {}
qat_training_results = {}

for name in MODEL_REGISTRY:
    resume_from = auto_resume_path(SAVE_DIR, f"qat_{name}")

    run_id = None
    if resume_from:
        meta_path = SAVE_DIR / f"qat_{name}_meta.json"
        if meta_path.exists():
            run_id = json.loads(meta_path.read_text()).get("wandb_run_id")

    print("=" * 72)
    print(f"QAT fine-tuning: {name}")
    if resume_from:
        print("(Resuming from checkpoint)")
    print("=" * 72)

    qat_model = build_qat(name, save_dir=SAVE_DIR, device=device)
    cb = make_qat_callback(qat_cfg.freeze_bn_epoch, qat_cfg.disable_observer_epoch)

    run = wandb.init(
        project="alexnet-phase4",
        group="qat-phase4",
        name=f"{name}_qat",
        id=run_id,
        resume="allow" if run_id else None,
        config={
            **asdict(qat_train_cfg),
            "arch": name,
            "phase": "qat",
            "freeze_bn_epoch": qat_cfg.freeze_bn_epoch,
            "disable_observer_epoch": qat_cfg.disable_observer_epoch,
            "num_classes": data_cfg.num_classes, "img_size": data_cfg.img_size,
            "dataset": "tiny-imagenet-200",
        },
        tags=["phase4", "final-architecture", "tiny-imagenet", "qat"],
        mode="offline",
    )

    trainer = Trainer(
        qat_model, train_loader, val_loader, qat_train_cfg,
        device, SAVE_DIR, f"qat_{name}", num_classes=data_cfg.num_classes,
        wandb_run=run,
        epoch_callback=cb,
        log_file=SAVE_DIR / f"qat_{name}.log",
    )
    results = trainer.fit(resume_from=resume_from)
    wandb.finish()

    qat_training_results[name] = results
    qat_models[name] = qat_model.cpu()

    del qat_model
    torch.cuda.empty_cache()

print("\nQAT training complete.")

/home/rafael/Documents/alexnet_rafael/.venv/lib/python3.12/site-packages/torch/ao/quantization/observer.py:229: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(

========================================================================
QAT fine-tuning: alexnet_final_bottleneck_fire
========================================================================

Training: 100%|██████████| 1406/1406 [00:28<00:00, 49.36it/s, acc=39.41%, loss=3.1132]
Validation: 100%|██████████| 157/157 [00:01<00:00, 105.96it/s, loss=2.9903, top1=43.59%, top5=69.75%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=3.1132 train_acc=39.41% | val_loss=2.9903 val_acc=43.59% val_top5=69.75% | lr=9.94e-06 peak_mem=454MB time=30.0s
Training: 100%|██████████| 1406/1406 [00:28<00:00, 49.94it/s, acc=40.27%, loss=3.0828]
Validation: 100%|██████████| 157/157 [00:01<00:00, 105.60it/s, loss=2.9755, top1=43.95%, top5=69.98%]
Epoch   2/20 | train_loss=3.0828 train_acc=40.27% | val_loss=2.9755 val_acc=43.95% val_top5=69.98% | lr=9.76e-06 peak_mem=454MB time=29.7s
Training: 100%|██████████| 1406/1406 [00:28<00:00, 49.68it/s, acc=40.73%, loss=3.0671]
Validation: 100%|██████████| 157/157 [00:01<00:00, 105.86it/s, loss=2.9745, top1=43.93%, top5=69.96%]
Epoch   3/20 | train_loss=3.0671 train_acc=40.73% | val_loss=2.9745 val_acc=43.93% val_top5=69.96% | lr=9.46e-06 peak_mem=454MB time=29.9s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.30it/s, acc=41.86%, loss=3.0109]
Validation: 100%|██████████| 157/157 [00:01<00:00, 106.94it/s, loss=2.9663, top1=44.21%, top5=70.36%]
Epoch   4/20 | train_loss=3.0109 train_acc=41.86% | val_loss=2.9663 val_acc=44.21% val_top5=70.36% | lr=9.05e-06 peak_mem=454MB time=29.5s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.23it/s, acc=42.12%, loss=3.0042]
Validation: 100%|██████████| 157/157 [00:01<00:00, 106.05it/s, loss=2.9676, top1=44.11%, top5=70.28%]
Epoch   5/20 | train_loss=3.0042 train_acc=42.12% | val_loss=2.9676 val_acc=44.11% val_top5=70.28% | lr=8.54e-06 peak_mem=454MB time=29.5s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.37it/s, acc=42.10%, loss=3.0036]
Validation: 100%|██████████| 157/157 [00:01<00:00, 105.69it/s, loss=2.9654, top1=44.10%, top5=70.40%]
Epoch   6/20 | train_loss=3.0036 train_acc=42.10% | val_loss=2.9654 val_acc=44.10% val_top5=70.40% | lr=7.94e-06 peak_mem=454MB time=29.5s
Training: 100%|██████████| 1406/1406 [00:28<00:00, 50.20it/s, acc=42.12%, loss=3.0030]
Validation: 100%|██████████| 157/157 [00:01<00:00, 107.05it/s, loss=2.9715, top1=44.14%, top5=70.13%]
Epoch   7/20 | train_loss=3.0030 train_acc=42.12% | val_loss=2.9715 val_acc=44.14% val_top5=70.13% | lr=7.27e-06 peak_mem=454MB time=29.5s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.76it/s, acc=42.32%, loss=2.9964]
Validation: 100%|██████████| 157/157 [00:01<00:00, 106.01it/s, loss=2.9639, top1=44.30%, top5=70.47%]
Epoch   8/20 | train_loss=2.9964 train_acc=42.32% | val_loss=2.9639 val_acc=44.30% val_top5=70.47% | lr=6.55e-06 peak_mem=454MB time=29.3s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.29it/s, acc=42.49%, loss=2.9947]
Validation: 100%|██████████| 157/157 [00:01<00:00, 107.23it/s, loss=2.9690, top1=44.12%, top5=70.15%]
Epoch   9/20 | train_loss=2.9947 train_acc=42.49% | val_loss=2.9690 val_acc=44.12% val_top5=70.15% | lr=5.78e-06 peak_mem=454MB time=29.5s
Training: 100%|██████████| 1406/1406 [00:28<00:00, 50.18it/s, acc=42.36%, loss=3.0013]
Validation: 100%|██████████| 157/157 [00:01<00:00, 106.41it/s, loss=2.9694, top1=44.31%, top5=70.23%]
Epoch  10/20 | train_loss=3.0013 train_acc=42.36% | val_loss=2.9694 val_acc=44.31% val_top5=70.23% | lr=5.00e-06 peak_mem=454MB time=29.6s
Training: 100%|██████████| 1406/1406 [00:28<00:00, 50.07it/s, acc=42.49%, loss=2.9903]
Validation: 100%|██████████| 157/157 [00:01<00:00, 104.30it/s, loss=2.9667, top1=44.36%, top5=70.23%]
Epoch  11/20 | train_loss=2.9903 train_acc=42.49% | val_loss=2.9667 val_acc=44.36% val_top5=70.23% | lr=4.22e-06 peak_mem=454MB time=29.7s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.35it/s, acc=42.40%, loss=2.9969]
Validation: 100%|██████████| 157/157 [00:01<00:00, 106.26it/s, loss=2.9639, top1=44.26%, top5=70.53%]
Epoch  12/20 | train_loss=2.9969 train_acc=42.40% | val_loss=2.9639 val_acc=44.26% val_top5=70.53% | lr=3.45e-06 peak_mem=454MB time=29.5s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.49it/s, acc=42.50%, loss=2.9901]
Validation: 100%|██████████| 157/157 [00:01<00:00, 106.14it/s, loss=2.9689, top1=44.22%, top5=70.25%]
Epoch  13/20 | train_loss=2.9901 train_acc=42.50% | val_loss=2.9689 val_acc=44.22% val_top5=70.25% | lr=2.73e-06 peak_mem=454MB time=29.4s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.71it/s, acc=42.60%, loss=2.9935]
Validation: 100%|██████████| 157/157 [00:01<00:00, 108.15it/s, loss=2.9640, top1=44.46%, top5=70.36%]
Epoch  14/20 | train_loss=2.9935 train_acc=42.60% | val_loss=2.9640 val_acc=44.46% val_top5=70.36% | lr=2.06e-06 peak_mem=454MB time=29.3s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.49it/s, acc=42.33%, loss=2.9914]
Validation: 100%|██████████| 157/157 [00:01<00:00, 105.72it/s, loss=2.9676, top1=44.38%, top5=70.37%]
Epoch  15/20 | train_loss=2.9914 train_acc=42.33% | val_loss=2.9676 val_acc=44.38% val_top5=70.37% | lr=1.46e-06 peak_mem=454MB time=29.4s
Training: 100%|██████████| 1406/1406 [00:28<00:00, 50.11it/s, acc=42.53%, loss=2.9914]
Validation: 100%|██████████| 157/157 [00:01<00:00, 102.76it/s, loss=2.9655, top1=44.33%, top5=70.39%]
Epoch  16/20 | train_loss=2.9914 train_acc=42.53% | val_loss=2.9655 val_acc=44.33% val_top5=70.39% | lr=9.55e-07 peak_mem=454MB time=29.7s
Training: 100%|██████████| 1406/1406 [00:28<00:00, 49.96it/s, acc=42.40%, loss=2.9928]
Validation: 100%|██████████| 157/157 [00:01<00:00, 102.19it/s, loss=2.9662, top1=44.43%, top5=70.38%]
Epoch  17/20 | train_loss=2.9928 train_acc=42.40% | val_loss=2.9662 val_acc=44.43% val_top5=70.38% | lr=5.45e-07 peak_mem=454MB time=29.8s
Training: 100%|██████████| 1406/1406 [00:28<00:00, 50.03it/s, acc=42.32%, loss=2.9899]
Validation: 100%|██████████| 157/157 [00:01<00:00, 106.64it/s, loss=2.9648, top1=44.35%, top5=70.41%]
Epoch  18/20 | train_loss=2.9899 train_acc=42.32% | val_loss=2.9648 val_acc=44.35% val_top5=70.41% | lr=2.45e-07 peak_mem=454MB time=29.6s
Training: 100%|██████████| 1406/1406 [00:27<00:00, 50.23it/s, acc=42.54%, loss=2.9905]
Validation: 100%|██████████| 157/157 [00:01<00:00, 106.59it/s, loss=2.9638, top1=44.26%, top5=70.58%]
Epoch  19/20 | train_loss=2.9905 train_acc=42.54% | val_loss=2.9638 val_acc=44.26% val_top5=70.58% | lr=6.16e-08 peak_mem=454MB time=29.5s
Early stopping at epoch 19

================= Run Summary =================
Model          : qat_alexnet_final_bottleneck_fire
Epochs         : 19
Best Val Top-1 : 44.46%
Best Val Top-5 : 70.36%
Final Val Top-1: 44.26%
Final Val Top-5: 70.58%
Best Val Loss  : 2.9640
Total Time     : 00:09:22
===============================================

/home/rafael/Documents/alexnet_rafael/.venv/lib/python3.12/site-packages/torch/ao/quantization/observer.py:229: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(

========================================================================
QAT fine-tuning: alexnet_final_fire_residual
========================================================================

Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.81it/s, acc=49.69%, loss=2.7156]
Validation: 100%|██████████| 157/157 [00:01<00:00, 117.44it/s, loss=2.7837, top1=49.59%, top5=74.45%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=2.7156 train_acc=49.69% | val_loss=2.7837 val_acc=49.59% val_top5=74.45% | lr=9.94e-06 peak_mem=332MB time=24.5s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 61.04it/s, acc=50.00%, loss=2.7040]
Validation: 100%|██████████| 157/157 [00:01<00:00, 113.16it/s, loss=2.7679, top1=49.46%, top5=74.78%]
Epoch   2/20 | train_loss=2.7040 train_acc=50.00% | val_loss=2.7679 val_acc=49.46% val_top5=74.78% | lr=9.76e-06 peak_mem=331MB time=24.5s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 60.49it/s, acc=50.06%, loss=2.7039]
Validation: 100%|██████████| 157/157 [00:01<00:00, 120.48it/s, loss=2.7790, top1=49.32%, top5=74.75%]
Epoch   3/20 | train_loss=2.7039 train_acc=50.06% | val_loss=2.7790 val_acc=49.32% val_top5=74.75% | lr=9.46e-06 peak_mem=331MB time=24.6s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 61.30it/s, acc=51.86%, loss=2.6401]
Validation: 100%|██████████| 157/157 [00:01<00:00, 114.35it/s, loss=2.7732, top1=49.65%, top5=74.78%]
Epoch   4/20 | train_loss=2.6401 train_acc=51.86% | val_loss=2.7732 val_acc=49.65% val_top5=74.78% | lr=9.05e-06 peak_mem=331MB time=24.4s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 61.79it/s, acc=51.92%, loss=2.6420]
Validation: 100%|██████████| 157/157 [00:01<00:00, 117.20it/s, loss=2.7756, top1=49.28%, top5=74.64%]
Epoch   5/20 | train_loss=2.6420 train_acc=51.92% | val_loss=2.7756 val_acc=49.28% val_top5=74.64% | lr=8.54e-06 peak_mem=331MB time=24.2s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 61.52it/s, acc=51.87%, loss=2.6414]
Validation: 100%|██████████| 157/157 [00:01<00:00, 116.44it/s, loss=2.7794, top1=49.41%, top5=74.52%]
Epoch   6/20 | train_loss=2.6414 train_acc=51.87% | val_loss=2.7794 val_acc=49.41% val_top5=74.52% | lr=7.94e-06 peak_mem=331MB time=24.3s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 61.91it/s, acc=51.81%, loss=2.6410]
Validation: 100%|██████████| 157/157 [00:01<00:00, 111.91it/s, loss=2.7747, top1=49.59%, top5=74.68%]
Epoch   7/20 | train_loss=2.6410 train_acc=51.81% | val_loss=2.7747 val_acc=49.59% val_top5=74.68% | lr=7.27e-06 peak_mem=331MB time=24.2s
Training: 100%|██████████| 1406/1406 [00:23<00:00, 61.10it/s, acc=51.99%, loss=2.6352]
Validation: 100%|██████████| 157/157 [00:01<00:00, 115.43it/s, loss=2.7800, top1=49.47%, top5=74.63%]
Epoch   8/20 | train_loss=2.6352 train_acc=51.99% | val_loss=2.7800 val_acc=49.47% val_top5=74.63% | lr=6.55e-06 peak_mem=331MB time=24.4s
Training: 100%|██████████| 1406/1406 [00:22<00:00, 62.59it/s, acc=51.97%, loss=2.6334]
Validation: 100%|██████████| 157/157 [00:01<00:00, 111.62it/s, loss=2.7792, top1=49.25%, top5=74.58%]
Epoch   9/20 | train_loss=2.6334 train_acc=51.97% | val_loss=2.7792 val_acc=49.25% val_top5=74.58% | lr=5.78e-06 peak_mem=331MB time=23.9s
Early stopping at epoch 9

================= Run Summary =================
Model          : qat_alexnet_final_fire_residual
Epochs         : 9
Best Val Top-1 : 49.65%
Best Val Top-5 : 74.78%
Final Val Top-1: 49.25%
Final Val Top-5: 74.58%
Best Val Loss  : 2.7732
Total Time     : 00:03:39
===============================================

========================================================================
QAT fine-tuning: alexnet_final_bottleneck_residual
========================================================================

/home/rafael/Documents/alexnet_rafael/.venv/lib/python3.12/site-packages/torch/ao/quantization/observer.py:229: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(

Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.21it/s, acc=43.48%, loss=2.9515]
Validation: 100%|██████████| 157/157 [00:01<00:00, 86.21it/s, loss=2.8932, top1=45.57%, top5=71.57%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=2.9515 train_acc=43.48% | val_loss=2.8932 val_acc=45.57% val_top5=71.57% | lr=9.94e-06 peak_mem=532MB time=37.8s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.14it/s, acc=44.31%, loss=2.9203]
Validation: 100%|██████████| 157/157 [00:01<00:00, 87.71it/s, loss=2.8887, top1=45.78%, top5=71.74%]
Epoch   2/20 | train_loss=2.9203 train_acc=44.31% | val_loss=2.8887 val_acc=45.78% val_top5=71.74% | lr=9.76e-06 peak_mem=532MB time=37.8s
Training: 100%|██████████| 1406/1406 [00:36<00:00, 38.98it/s, acc=44.51%, loss=2.9104]
Validation: 100%|██████████| 157/157 [00:01<00:00, 87.42it/s, loss=2.8782, top1=46.05%, top5=72.15%]
Epoch   3/20 | train_loss=2.9104 train_acc=44.51% | val_loss=2.8782 val_acc=46.05% val_top5=72.15% | lr=9.46e-06 peak_mem=532MB time=37.9s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.58it/s, acc=45.81%, loss=2.8568]
Validation: 100%|██████████| 157/157 [00:01<00:00, 86.86it/s, loss=2.8741, top1=46.34%, top5=72.29%]
Epoch   4/20 | train_loss=2.8568 train_acc=45.81% | val_loss=2.8741 val_acc=46.34% val_top5=72.29% | lr=9.05e-06 peak_mem=532MB time=37.4s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.53it/s, acc=46.02%, loss=2.8499]
Validation: 100%|██████████| 157/157 [00:01<00:00, 88.92it/s, loss=2.8715, top1=46.56%, top5=72.31%]
Epoch   5/20 | train_loss=2.8499 train_acc=46.02% | val_loss=2.8715 val_acc=46.56% val_top5=72.31% | lr=8.54e-06 peak_mem=532MB time=37.4s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.53it/s, acc=46.31%, loss=2.8416]
Validation: 100%|██████████| 157/157 [00:01<00:00, 87.00it/s, loss=2.8692, top1=46.45%, top5=72.47%]
Epoch   6/20 | train_loss=2.8416 train_acc=46.31% | val_loss=2.8692 val_acc=46.45% val_top5=72.47% | lr=7.94e-06 peak_mem=532MB time=37.4s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.68it/s, acc=46.45%, loss=2.8392]
Validation: 100%|██████████| 157/157 [00:01<00:00, 88.37it/s, loss=2.8687, top1=46.59%, top5=72.41%]
Epoch   7/20 | train_loss=2.8392 train_acc=46.45% | val_loss=2.8687 val_acc=46.59% val_top5=72.41% | lr=7.27e-06 peak_mem=532MB time=37.3s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.71it/s, acc=46.49%, loss=2.8370]
Validation: 100%|██████████| 157/157 [00:01<00:00, 86.21it/s, loss=2.8708, top1=46.67%, top5=72.56%]
Epoch   8/20 | train_loss=2.8370 train_acc=46.49% | val_loss=2.8708 val_acc=46.67% val_top5=72.56% | lr=6.55e-06 peak_mem=532MB time=37.3s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.63it/s, acc=46.63%, loss=2.8361]
Validation: 100%|██████████| 157/157 [00:01<00:00, 87.71it/s, loss=2.8679, top1=46.70%, top5=72.33%]
Epoch   9/20 | train_loss=2.8361 train_acc=46.63% | val_loss=2.8679 val_acc=46.70% val_top5=72.33% | lr=5.78e-06 peak_mem=532MB time=37.3s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.58it/s, acc=46.74%, loss=2.8321]
Validation: 100%|██████████| 157/157 [00:01<00:00, 87.48it/s, loss=2.8658, top1=46.98%, top5=72.39%]
Epoch  10/20 | train_loss=2.8321 train_acc=46.74% | val_loss=2.8658 val_acc=46.98% val_top5=72.39% | lr=5.00e-06 peak_mem=532MB time=37.4s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.74it/s, acc=46.75%, loss=2.8356]
Validation: 100%|██████████| 157/157 [00:01<00:00, 88.11it/s, loss=2.8656, top1=46.80%, top5=72.48%]
Epoch  11/20 | train_loss=2.8356 train_acc=46.75% | val_loss=2.8656 val_acc=46.80% val_top5=72.48% | lr=4.22e-06 peak_mem=532MB time=37.2s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.72it/s, acc=46.65%, loss=2.8291]
Validation: 100%|██████████| 157/157 [00:01<00:00, 88.37it/s, loss=2.8634, top1=46.94%, top5=72.51%]
Epoch  12/20 | train_loss=2.8291 train_acc=46.65% | val_loss=2.8634 val_acc=46.94% val_top5=72.51% | lr=3.45e-06 peak_mem=532MB time=37.2s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.64it/s, acc=46.46%, loss=2.8320]
Validation: 100%|██████████| 157/157 [00:01<00:00, 87.06it/s, loss=2.8669, top1=46.66%, top5=72.51%]
Epoch  13/20 | train_loss=2.8320 train_acc=46.46% | val_loss=2.8669 val_acc=46.66% val_top5=72.51% | lr=2.73e-06 peak_mem=532MB time=37.4s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.71it/s, acc=46.60%, loss=2.8307]
Validation: 100%|██████████| 157/157 [00:01<00:00, 87.02it/s, loss=2.8646, top1=46.94%, top5=72.63%]
Epoch  14/20 | train_loss=2.8307 train_acc=46.60% | val_loss=2.8646 val_acc=46.94% val_top5=72.63% | lr=2.06e-06 peak_mem=532MB time=37.3s
Training: 100%|██████████| 1406/1406 [00:35<00:00, 39.80it/s, acc=46.63%, loss=2.8316]
Validation: 100%|██████████| 157/157 [00:01<00:00, 87.50it/s, loss=2.8649, top1=46.86%, top5=72.66%]
Epoch  15/20 | train_loss=2.8316 train_acc=46.63% | val_loss=2.8649 val_acc=46.86% val_top5=72.66% | lr=1.46e-06 peak_mem=532MB time=37.2s
Early stopping at epoch 15

================= Run Summary =================
Model          : qat_alexnet_final_bottleneck_residual
Epochs         : 15
Best Val Top-1 : 46.98%
Best Val Top-5 : 72.39%
Final Val Top-1: 46.86%
Final Val Top-5: 72.66%
Best Val Loss  : 2.8658
Total Time     : 00:09:22
===============================================

/home/rafael/Documents/alexnet_rafael/.venv/lib/python3.12/site-packages/torch/ao/quantization/observer.py:229: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(

========================================================================
QAT fine-tuning: alexnet_final_depthwise_fire
========================================================================

Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.28it/s, acc=38.53%, loss=3.1617]
Validation: 100%|██████████| 157/157 [00:01<00:00, 125.61it/s, loss=3.0076, top1=43.13%, top5=69.03%]
wandb: WARNING Symlinked 1 file into the W&B run directory; call wandb.save again to sync new files.
Epoch   1/20 | train_loss=3.1617 train_acc=38.53% | val_loss=3.0076 val_acc=43.13% val_top5=69.03% | lr=9.94e-06 peak_mem=276MB time=21.9s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.71it/s, acc=38.57%, loss=3.1534]
Validation: 100%|██████████| 157/157 [00:01<00:00, 134.05it/s, loss=3.0125, top1=43.09%, top5=68.59%]
Epoch   2/20 | train_loss=3.1534 train_acc=38.57% | val_loss=3.0125 val_acc=43.09% val_top5=68.59% | lr=9.76e-06 peak_mem=276MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.60it/s, acc=38.91%, loss=3.1539]
Validation: 100%|██████████| 157/157 [00:01<00:00, 131.18it/s, loss=3.0067, top1=43.30%, top5=69.23%]
Epoch   3/20 | train_loss=3.1539 train_acc=38.91% | val_loss=3.0067 val_acc=43.30% val_top5=69.23% | lr=9.46e-06 peak_mem=276MB time=21.8s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.44it/s, acc=40.13%, loss=3.1007]
Validation: 100%|██████████| 157/157 [00:01<00:00, 127.34it/s, loss=3.0040, top1=43.82%, top5=69.29%]
Epoch   4/20 | train_loss=3.1007 train_acc=40.13% | val_loss=3.0040 val_acc=43.82% val_top5=69.29% | lr=9.05e-06 peak_mem=276MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.07it/s, acc=40.17%, loss=3.0962]
Validation: 100%|██████████| 157/157 [00:01<00:00, 128.08it/s, loss=3.0021, top1=43.57%, top5=69.26%]
Epoch   5/20 | train_loss=3.0962 train_acc=40.17% | val_loss=3.0021 val_acc=43.57% val_top5=69.26% | lr=8.54e-06 peak_mem=276MB time=21.7s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.20it/s, acc=40.24%, loss=3.0921]
Validation: 100%|██████████| 157/157 [00:01<00:00, 125.78it/s, loss=3.0031, top1=43.74%, top5=69.38%]
Epoch   6/20 | train_loss=3.0921 train_acc=40.24% | val_loss=3.0031 val_acc=43.74% val_top5=69.38% | lr=7.94e-06 peak_mem=276MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.08it/s, acc=40.28%, loss=3.0906]
Validation: 100%|██████████| 157/157 [00:01<00:00, 131.05it/s, loss=3.0063, top1=43.42%, top5=69.12%]
Epoch   7/20 | train_loss=3.0906 train_acc=40.28% | val_loss=3.0063 val_acc=43.42% val_top5=69.12% | lr=7.27e-06 peak_mem=276MB time=21.6s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 68.62it/s, acc=40.18%, loss=3.0915]
Validation: 100%|██████████| 157/157 [00:01<00:00, 129.85it/s, loss=3.0044, top1=43.38%, top5=69.28%]
Epoch   8/20 | train_loss=3.0915 train_acc=40.18% | val_loss=3.0044 val_acc=43.38% val_top5=69.28% | lr=6.55e-06 peak_mem=276MB time=21.8s
Training: 100%|██████████| 1406/1406 [00:20<00:00, 69.00it/s, acc=40.36%, loss=3.0896]
Validation: 100%|██████████| 157/157 [00:01<00:00, 129.53it/s, loss=3.0016, top1=43.55%, top5=69.12%]
Epoch   9/20 | train_loss=3.0896 train_acc=40.36% | val_loss=3.0016 val_acc=43.55% val_top5=69.12% | lr=5.78e-06 peak_mem=276MB time=21.7s
Early stopping at epoch 9

================= Run Summary =================
Model          : qat_alexnet_final_depthwise_fire
Epochs         : 9
Best Val Top-1 : 43.82%
Best Val Top-5 : 69.29%
Final Val Top-1: 43.55%
Final Val Top-5: 69.12%
Best Val Loss  : 3.0040
Total Time     : 00:03:15
===============================================

QAT training complete.

## 7. INT8 conversion & CPU evaluation

`torch.ao.quantization.convert` materialises true quantised ops and must run on CPU.

In [ ]:
val_loader_cpu = torch.utils.data.DataLoader(
    val_ds, batch_size=data_cfg.batch_size, shuffle=False, num_workers=0, pin_memory=False,
)
cpu_device = torch.device("cpu")

int8_models = {name: convert_to_int8(m.cpu().eval()) for name, m in qat_models.items()}

for name, m in int8_models.items():
    torch.save(m.state_dict(), SAVE_DIR / f"{name}.pth")
    compress_checkpoint(SAVE_DIR / f"{name}.pth")
print("INT8 conversion done.")

int8_metrics = {}
for name, m in int8_models.items():
    dummy_cfg = replace(fp32_cfg, use_amp=False)
    trainer = Trainer(
        m.cpu().eval(), val_loader_cpu, val_loader_cpu, dummy_cfg,
        cpu_device, SAVE_DIR, name, num_classes=data_cfg.num_classes,
    )
    metrics = trainer.evaluate(topk=(1, 5))
    int8_metrics[name] = metrics
    print(f"{name:32s} | loss={metrics['loss']:.4f} | top1={metrics['top1']:.2f}% | top5={metrics['top5']:.2f}%")

## 8. FP32 evaluation — reload best checkpoints

In [9]:
CTORS = {
    "alexnet_final_bottleneck_fire":     AlexNetFinalBottleneckFire,
    "alexnet_final_fire_residual":       AlexNetFinalFireResidual,
    "alexnet_final_bottleneck_residual": AlexNetFinalBottleneckResidual,
    "alexnet_final_depthwise_fire":      AlexNetFinalDepthwiseFire,
}

fp32_best = {name: load_best_model(name, ctor, SAVE_DIR, device) for name, ctor in CTORS.items()}

fp32_metrics = {}
for name, m in fp32_best.items():
    dummy_cfg = replace(fp32_cfg, use_amp=False)
    trainer = Trainer(
        m, train_loader, val_loader, dummy_cfg,
        device, SAVE_DIR, name, num_classes=data_cfg.num_classes,
    )
    metrics = trainer.evaluate(topk=(1, 5))
    fp32_metrics[name] = metrics
    print(f"{name:32s} | loss={metrics['loss']:.4f} | top1={metrics['top1']:.2f}% | top5={metrics['top5']:.2f}%")

alexnet_final_bottleneck_fire    | loss=2.4907 | top1=42.29% | top5=68.54%
alexnet_final_fire_residual      | loss=2.1318 | top1=49.79% | top5=74.80%
alexnet_final_bottleneck_residual | loss=2.3388 | top1=45.10% | top5=71.15%
alexnet_final_depthwise_fire     | loss=2.4434 | top1=43.46% | top5=69.02%

## 9. Final comparison table, benchmarks & per-model summaries

In [10]:
rows = []

for name, m in fp32_best.items():
    info = torchinfo.summary(m, input_size=(1, 3, data_cfg.img_size, data_cfg.img_size), verbose=0)
    rows.append({
        "model": name, "precision": "FP32",
        "top1_%": fp32_metrics[name]["top1"],
        "top5_%": fp32_metrics[name]["top5"],
        "loss":   fp32_metrics[name]["loss"],
        "params_M": info.total_params / 1e6,
        "size_MB":  disk_mb(SAVE_DIR / f"{name}_best.pth"),
    })

for name, m in int8_models.items():
    info = torchinfo.summary(fp32_best[name], input_size=(1, 3, data_cfg.img_size, data_cfg.img_size), verbose=0)
    rows.append({
        "model": f"{name}_INT8", "precision": "INT8",
        "top1_%": int8_metrics[name]["top1"],
        "top5_%": int8_metrics[name]["top5"],
        "loss":   int8_metrics[name]["loss"],
        "params_M": info.total_params / 1e6,
        "size_MB":  disk_mb(SAVE_DIR / f"{name}.pth"),
    })

df = build_comparison_table(rows)
df.to_csv(RESULTS_DIR / "final_comparison.csv", index=False)
df

,model,precision,top1_%,top5_%,loss,params_M,size_MB
0,alexnet_final_fire_residual,FP32,49.793291,74.802184,2.131824,0.698664,8.093657
1,alexnet_final_bottleneck_residual,FP32,45.099601,71.151185,2.338797,0.571304,6.653960
2,alexnet_final_depthwise_fire,FP32,43.455875,69.023257,2.443448,0.474921,5.511263
3,alexnet_final_bottleneck_fire,FP32,42.286080,68.539512,2.490701,0.506408,5.882781
4,alexnet_final_fire_residual_INT8,INT8,49.201027,74.387586,2.153559,0.698664,0.746309
5,alexnet_final_bottleneck_residual_INT8,INT8,45.980674,72.328943,2.280574,0.571304,0.637690
6,alexnet_final_bottleneck_fire_INT8,INT8,44.001037,70.151949,2.381651,0.506408,0.545216
7,alexnet_final_depthwise_fire_INT8,INT8,42.789248,68.953073,2.452214,0.474921,0.509390

In [ ]:
# --- Benchmark FP32 models (GPU) ---
fp32_benchmarks = {}
for name, m in fp32_best.items():
    dummy_cfg = replace(fp32_cfg, use_amp=False)
    t = Trainer(m, train_loader, val_loader, dummy_cfg, device, SAVE_DIR, name,
                num_classes=data_cfg.num_classes)
    fp32_benchmarks[name] = t.benchmark()
    print(f"{name:32s} FP32 | {fp32_benchmarks[name]['latency_ms_per_image']:.3f} ms/img")

# --- Benchmark INT8 models (CPU) ---
int8_benchmarks = {}
for name, m in int8_models.items():
    dummy_cfg = replace(fp32_cfg, use_amp=False)
    t = Trainer(m.cpu().eval(), val_loader_cpu, val_loader_cpu, dummy_cfg, cpu_device, SAVE_DIR, name,
                num_classes=data_cfg.num_classes)
    int8_benchmarks[name] = t.benchmark(warmup=50)
    print(f"{name:32s} INT8 | {int8_benchmarks[name]['latency_ms_per_image']:.3f} ms/img")

# --- FLOPs ---
fp32_flops = {}
for name, m in fp32_best.items():
    fp32_flops[name] = compute_flops(m.cpu().eval())
    print(f"{name:32s} | {fp32_flops[name]['macs']/1e9:.3f} GMACs")

# --- Per-model summary JSONs ---
for name in fp32_best:
    compress_checkpoint(SAVE_DIR / f"{name}_best.pth")
    info = torchinfo.summary(fp32_best[name], input_size=(1, 3, data_cfg.img_size, data_cfg.img_size), verbose=0)
    summary = make_run_summary(
        name=name,
        mode="fp32+qat+int8",
        fit_results=fp32_training_results.get(name, {}),
        fp32_eval=fp32_metrics[name],
        params_m=info.total_params / 1e6,
        fp32_size_mb=disk_mb(SAVE_DIR / f"{name}_best.pth"),
        int8_size_mb=disk_mb(SAVE_DIR / f"{name}.pth"),
        fp32_benchmark=fp32_benchmarks[name],
        flops_results=fp32_flops[name],
        int8_eval=int8_metrics.get(name),
        int8_benchmark=int8_benchmarks.get(name),
        fp32_gzip_mb=gzip_mb(SAVE_DIR / f"{name}_best.pth"),
        int8_gzip_mb=gzip_mb(SAVE_DIR / f"{name}.pth"),
    )
    out = RESULTS_DIR / f"{name}_summary.json"
    with open(out, "w") as f:
        json.dump(summary, f, indent=2, default=str)
    print(f"Saved: {out.name}")

In [12]:
print("=" * 72)
print("RANKING BY TOP-1 ACCURACY (all precisions)")
print("=" * 72)
ranked = df.sort_values("top1_%", ascending=False).reset_index(drop=True)
for i, row in ranked.iterrows():
    print(f"{i+1:2d}. {row['model']:34s} [{row['precision']}] | "
          f"top1={row['top1_%']:6.2f}% | top5={row['top5_%']:6.2f}% | "
          f"params={row['params_M']:6.2f}M | size={row['size_MB']:6.2f}MB")

========================================================================
RANKING BY TOP-1 ACCURACY (all precisions)
========================================================================
 1. alexnet_final_fire_residual        [FP32] | top1= 49.79% | top5= 74.80% | params=  0.70M | size=  8.09MB
 2. alexnet_final_fire_residual_INT8   [INT8] | top1= 49.20% | top5= 74.39% | params=  0.70M | size=  0.75MB
 3. alexnet_final_bottleneck_residual_INT8 [INT8] | top1= 45.98% | top5= 72.33% | params=  0.57M | size=  0.64MB
 4. alexnet_final_bottleneck_residual  [FP32] | top1= 45.10% | top5= 71.15% | params=  0.57M | size=  6.65MB
 5. alexnet_final_bottleneck_fire_INT8 [INT8] | top1= 44.00% | top5= 70.15% | params=  0.51M | size=  0.55MB
 6. alexnet_final_depthwise_fire       [FP32] | top1= 43.46% | top5= 69.02% | params=  0.47M | size=  5.51MB
 7. alexnet_final_depthwise_fire_INT8  [INT8] | top1= 42.79% | top5= 68.95% | params=  0.47M | size=  0.51MB
 8. alexnet_final_bottleneck_fire      [FP32] | top1= 42.29% | top5= 68.54% | params=  0.51M | size=  5.88MB

## 10. Ablation study

Each Phase 4 model already isolates a *pair* of mechanisms. This section
compares each hybrid against its two single-mechanism Phase 3 parents (already
trained in `results/phase_3_compensation_and_hybrids_training/`) to see whether combining mechanisms
compounds or cancels their individual effects — no retraining needed.

In [13]:
PHASE3_DIR = project_root / "results" / "phase_3_compensation_and_hybrids_training"

ABLATION_PARENTS = {
    "alexnet_final_bottleneck_fire":     ["alexnet_bottleneck", "alexnet_fire"],
    "alexnet_final_fire_residual":       ["alexnet_fire", "alexnet_residual"],
    "alexnet_final_bottleneck_residual": ["alexnet_bottleneck", "alexnet_residual"],
    "alexnet_final_depthwise_fire":      ["alexnet_depthwisesep", "alexnet_fire"],
}

def _load_phase3_top1(name):
    p = PHASE3_DIR / f"{name}_summary.json"
    if not p.exists():
        return None
    return json.loads(p.read_text()).get("fp32_top1")

ablation_rows = []
for hybrid_name, parents in ABLATION_PARENTS.items():
    hybrid_top1 = fp32_metrics[hybrid_name]["top1"]
    parent_top1s = {p: _load_phase3_top1(p) for p in parents}
    best_parent_top1 = max((v for v in parent_top1s.values() if v is not None), default=None)
    ablation_rows.append({
        "hybrid": hybrid_name,
        "hybrid_top1": hybrid_top1,
        **{f"parent_{p}_top1": v for p, v in parent_top1s.items()},
        "best_parent_top1": best_parent_top1,
        "delta_vs_best_parent": (hybrid_top1 - best_parent_top1) if best_parent_top1 is not None else None,
    })

ablation_df = pd.DataFrame(ablation_rows)
ablation_df.to_csv(RESULTS_DIR / "ablation_results.csv", index=False)
ablation_df

,hybrid,hybrid_top1,parent_alexnet_bottleneck_top1,parent_alexnet_fire_top1,best_parent_top1,delta_vs_best_parent,parent_alexnet_residual_top1,parent_alexnet_depthwisesep_top1
0,alexnet_final_bottleneck_fire,42.286080,44.622979,43.976474,44.622979,-2.336898,NaN,NaN
1,alexnet_final_fire_residual,49.793291,NaN,43.976474,48.012939,1.780352,48.012939,NaN
2,alexnet_final_bottleneck_residual,45.099601,44.622979,NaN,48.012939,-2.913338,48.012939,NaN
3,alexnet_final_depthwise_fire,43.455875,NaN,43.976474,44.390011,-0.934136,NaN,44.390011

## 11. Cross-phase comparison

Aggregate every phase's per-model summary JSON (Phase 1 baselines, Phase 2
kernel restriction, Phase 3 compensation, Phase 4 final architectures) into a
single ranking.

In [14]:
phase_dirs = {
    "Phase 1": project_root / "results" / "phase_1_baseline_training",
    "Phase 2": project_root / "results" / "phase_2_kernel_restriction_training",
    "Phase 3": project_root / "results" / "phase_3_compensation_and_hybrids_training",
    "Phase 4": RESULTS_DIR,
}

all_rows = []
for phase_name, phase_dir in phase_dirs.items():
    if not phase_dir.exists():
        continue
    for summary_file in phase_dir.glob("*_summary.json"):
        data = json.loads(summary_file.read_text())
        data["phase"] = phase_name
        all_rows.append(data)

cross_phase_df = pd.DataFrame(all_rows)
cross_phase_cols = [c for c in [
    "phase", "model_name", "fp32_top1", "int8_top1", "params_m",
    "fp32_size_mb", "int8_size_mb", "param_efficiency_top1_per_m",
    "quantization_drop_top1",
] if c in cross_phase_df.columns]
cross_phase_display = cross_phase_df[cross_phase_cols].sort_values("fp32_top1", ascending=False)
cross_phase_display.to_csv(RESULTS_DIR / "cross_phase_comparison.csv", index=False)
cross_phase_display

,phase,model_name,fp32_top1,int8_top1,params_m,fp32_size_mb,int8_size_mb,param_efficiency_top1_per_m,quantization_drop_top1
2,Phase 1,mobilenetv2,57.995582,NaN,2.480072,28.751925,NaN,23.414643,NaN
1,Phase 1,resnet18_tv,53.913635,NaN,11.279112,129.208681,NaN,4.785838,NaN
4,Phase 1,vgg_style,51.814806,51.188743,2.405288,27.584812,2.376703,21.556670,0.626063
22,Phase 4,alexnet_final_fire_residual,49.793291,49.201027,0.698664,8.093657,0.746309,71.250272,0.592265
20,Phase 3,alexnet_residual,48.012939,47.273704,60.670280,694.414034,58.102711,0.792151,0.739235
8,Phase 2,alexnet_small_kernel,45.836565,35.946080,1.602376,18.353315,1.561041,28.607518,9.890485
24,Phase 4,alexnet_final_bottleneck_residual,45.099601,45.980674,0.571304,6.653960,0.637690,78.977217,-0.881073
12,Phase 3,alexnet_bottleneck,44.622979,44.539082,0.385000,4.491745,0.431780,116.051948,0.083897
6,Phase 2,alexnet_stacked,44.559684,42.792845,60.483976,692.254669,57.941553,0.737881,1.766840
16,Phase 3,alexnet_depthwisesep,44.390011,41.469061,0.313641,3.654016,0.399755,141.818193,2.920949
15,Phase 3,alexnet_fire,43.976474,44.303995,0.516152,5.989412,0.551374,85.381826,-0.327522
21,Phase 4,alexnet_final_depthwise_fire,43.455875,42.789248,0.474921,5.511263,0.509390,91.657349,0.666627
17,Phase 3,alexnet_factorized,42.890143,42.597890,57.066760,653.148672,54.683115,0.754204,0.292253
23,Phase 4,alexnet_final_bottleneck_fire,42.286080,44.001037,0.506408,5.882781,0.545216,83.568980,-1.714957
9,Phase 2,alexnet_mixed,38.740057,37.993860,1.750024,20.042604,1.705048,22.113982,0.746197
14,Phase 3,alexnet_gap,38.738528,37.599918,2.302984,26.370630,2.232311,16.873760,1.138610
7,Phase 2,alexnet_3x3,35.787162,36.190116,57.605128,659.258051,55.124596,0.622340,-0.402954
0,Phase 1,alexnet_tv,32.887921,31.903201,57.823240,661.754141,55.332613,0.569667,0.984719
10,Phase 2,alexnet_2x2,30.023813,30.888581,1.052744,12.062769,1.039989,28.582447,-0.864768
13,Phase 3,alexnet_groupconv,29.181999,27.707005,55.919752,639.990591,53.538496,0.522356,1.474994
5,Phase 2,alexnet_tv,24.288143,26.276261,57.823240,661.754141,55.332613,0.419727,-1.988117
18,Phase 3,alexnet_se,0.500000,NaN,57.646288,659.752306,NaN,0.007459,NaN
3,Phase 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Phase 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Phase 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 12. Persist experiment summary

In [15]:
create_results_summary(
    results={
        "fp32_metrics": fp32_metrics,
        "int8_metrics": int8_metrics,
        "fp32_training_results": fp32_training_results,
        "qat_training_results": qat_training_results,
        "ablation": ablation_rows,
    },
    config=asdict(fp32_cfg),
    output_path=RESULTS_DIR / "experiment_summary.json",
)

## W&B — syncing offline runs

All runs were saved locally with `mode="offline"`. Two run groups are tracked:
- **`fp32-phase4`** — one run per architecture, FP32 training
- **`qat-phase4`** — one run per architecture, QAT fine-tuning

When ready, sync to the W&B dashboard from a terminal:

```bash
wandb sync --sync-all
```